### ISSUE TITLE
Payment Failed: The merchant does not accept payments of this type.

### ISSUE THREAD

**Issue by ManojBehera** [paypal/PayPal-Android-SDK#104]
![unnamed](https://cloud.githubusercontent.com/assets/5081280/4554023/5fcddd16-4ea5-11e4-9481-18a6b7c4ccdf.png)

Doubt: Is Paypal Merchant account only for some specific countries ????

Solutions May be: Please correct me if I am wrong.

Solution of the issue:

1:Be sure the merchant account has Pro permissions. Also, be sure the app has gone through the developer-approval process.

2: Also, be sure the app has been approved. The app has basic permissions until you submit it for approval.

3: You may have a Business account  but to accept credit card payments in the live environment your account must be approved for Paypal.

4: You should contact PayPal Developer Support. File a ticket at PayPal merchant technical Support. Click on the Contact Technical Support link to file a ticket.

5: You can call to PayPal Customer Care , They will verified your name , DOB, Verification Code (Code will be shown in your PayPal  Dashboard in Customer support page) etc , then will fix your issue in a minute or they will help you to fix your issue .

**Comment by BeingHumanhelper5** [comment]
To make the CC payment work on Paypal library you need to upgrade your merchant/business account to PRO type.
