### ISSUE TITLE
request failure with http statusCode:500,exception:org.apache.http.client.HttpResponseException: Internal Server Error     INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by GirishBhat** [paypal/PayPal-Android-SDK#105]
Hi I am testing my app using 2.3.5 Sdk with Live Environment for single payment,but every time I am getting this message
![capture](https://cloud.githubusercontent.com/assets/8476888/4590470/eca9eb38-505f-11e4-929f-df1224051324.PNG)

```
E/paypal.sdk(15311): request failure with http statusCode:500,exception:org.apache.http.client.HttpResponseException: Internal Server Error E/paypal.sdk(15311): request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","debug_id":"3e284a3cfb391","message":"Payment approval returned: {\"id\":\"\",\"state\":\"NON_PAYABLE\",\"cart_id\":\"\",\"payer\":{\"payment_method\":\"paypal\",\"payer_info\":{\"email\":\"\",\"payer_id\":\"\",\"shipping_address\":{\"recipient_name\":\"\",\"id\":\"\",\"line1\":\"\",\"line2\":\"\",\"city\":\"\",\"state\":\"\",\"postal_code\":\"\",\"country_code\":\"US\",\"default_address\":true,\"preferred_address\":false},\"phone\":\"\",\"phone_type\":\"MOBILE\"}},\"payment_approved\":false,\"offers\":[{\"offer_intensity\":\"STRONG\"}],\"payment_contingency\":{\"name\":\"PAYER_ACTION_REQUIRED\",\"cause_name\":\"VERIFY_USER_IDENTITY\",\"resolutions\"[{\"name\":\"STEP_UP_AUTH_NEEDED\"}]}}","information_link":"https://api.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}
E/paypal.sdk(15311): INTERNAL_SERVICE_ERROR
```

**Comment by girlmeetsdroid** [comment]
Hi,

I'm getting the same error:

request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"06d2f1415dc34","message":"checkout-session not created","information_link":"https://api-m.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

I've tried Code-Crash's fix but that didn't work. It's very difficult to debug this as the error codes are not very descriptive re: what makes the payment unprocesseable. Please advise. This is a USD transaction being paid with a USD account.

**Comment by roberto-m** [comment]
@girlmeetsdroid copied from some previous comments...

Looks like the logged-in payer does not have a valid way to fund the payment at this time in their PayPal account.

I think you should set a valid payment method, or verify your account. It isn't a code problem. I had the same issue. After your validation, your code should work fine.

**Comment by Zhandongdu** [comment]
I have same issue now.
05-29 09:59:26.471 23185-23845/com.puma.chateaued E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
05-29 09:59:26.471 23185-23845/com.puma.chateaued E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"69ffb54d9654a","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
05-29 09:59:26.471 23185-23185/com.puma.chateaued E/paypal.sdk: PAYMENT_CREATION_ERROR
05-29 09:59:26.646 23185-23185/com.puma.chateaued E/ViewRootImpl: sendUserActionEvent() mView == null

If it is available, please help me.

**Comment by sunil-singh-chaudhary** [comment]
I hv create a Sandbox with new Client_id using Paypal sdk 2.14.2, but when i am trying to access it, it showing error I have made client id with the same user name and password which i am using to login from android paypal ,pls help

.therock.paymentgateway E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
therock.paymentgateway E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"47b126f7c178","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
06-03 16:08:12.643 32357-32357/com.example.therock.paymentgateway E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by bluk** [comment]
@Zhandongdu @sunil-singh-chaudhary You need to create a PayPal sandbox account as a business/facilitator and then a different PayPal sandbox account (personal/buyer). You cannot use the same account to pay yourself. If this isn't your issue, can you please open a new issue in this repository?

**Comment by anandraj16992** [comment]
What is solution for this ? I have updated library as well code also still not working in live. Please short out this problem as soon as possible. I am not able to upload my app cause of this issue.

**Comment by ppmtscory** [comment]
@anandraj16992 this issue was closed some time ago.  Please open a new issue with the details of your issue.  As this issue suggests, please make sure you are not doing domestic payments in India and/or trying to login to pay with the same account that's receiving the funds.  Once you file your new issue, somebody will have a look.

**Comment by anandraj16992** [comment]
I am trying to pay in UK from India using debit card of Australia . So is it working in this scenario ?

**Comment by ppmtscory** [comment]
Cross-border payments should work fine, but I can't look into anything further unless you file a separate issue with a detailed explanation of your issue - which would include debug ID's from your error messages.
