### ISSUE TITLE
paypal verification by server

### ISSUE THREAD

**Issue by charlyloic** [paypal/PayPal-Android-SDK#112]
I am trying to integrate paypal payment in my android application. Does anyone know the java code to send the paypal response from your android application to your server for verification??

**Comment by dahawkish** [comment]
Dear Jesse-yan,

This problem is not resolved. I am emailing you through innovation@goldendata.org

**Comment by jesse-yan** [comment]
ok,tks. let me have a look.

**Comment by tomwhipple** [comment]
This is more of a how-to question which may be better answered on [Stackoverflow](https://stackoverflow.com) where there is a larger community.
