### ISSUE TITLE
Request: Collect and validate name/address for CC transactions

### ISSUE THREAD

**Issue by CunningLogic** [paypal/PayPal-Android-SDK#122]
Collecting the card holder name and billing address for credit cards is basic fraud prevention.

At this time I can find no way to have the SDK collect and validate this information. It would be nice to see this. It would also allow me to look up transactions, as at this time I get no name with CC transactions.

**Comment by tomwhipple** [comment]
We are now recommending [Braintree](https://braintreepayments.com) for general payment acceptance. Since these fields are not supported by the underlying REST API, it is unlikely that we'll be adding them to the SDK.

see also: https://github.com/paypal/PayPal-iOS-SDK/issues/252
