### ISSUE TITLE
There was a problem processing your payment. Please try again.

### ISSUE THREAD

**Issue by solution24hourexplorer** [paypal/PayPal-Android-SDK#126]
HI, 

When I try to make payment via paypal android sdk then it show  error in "ENVIRONMENT_PRODUCTION" but it is working in "ENVIRONMENT_SANDBOX".

"There was a problem processing your payment. Please try again."

Here is my code.

PayPalPayment payment = new PayPalPayment(new BigDecimal("3.9"),"TRY", "Sample Product", PayPalPayment.PAYMENT_INTENT_SALE);
     Intent intentPayment = new Intent(this, PaymentActivity.class);
     intentPayment.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
     intentPayment.putExtra(PaymentActivity.EXTRA_PAYMENT, payment);
     startActivityForResult(intentPayment, 0);

![unnamed](https://cloud.githubusercontent.com/assets/8382187/5557140/e79f3842-8d1c-11e4-83dd-0605c8a60156.png)

**Comment by tomwhipple** [comment]
Most issues of this form have to do with an account specific problem. They can best be solved by recording the log cat transcript (especially the DebugID) and contacting the [merchant technical support team](https://www.paypal.com/mts) that has access to account specific records.
