### ISSUE TITLE
  Request failed with server response 

### ISSUE THREAD

**Issue by ItsRajesh4uguys** [paypal/PayPal-Android-SDK#138]
Dear Team, 

I am new to Paypal SDK. I have created the Developer account and got Sandbox Client ID as well. When I try to do the my first sandbox transaction always getting below response. 

02-11 23:25:55.034: E/paypal.sdk(11770): request failure with http statusCode:400,exception:org.apache.http.client.HttpResponseException: Bad Request

02-11 23:25:55.034: E/paypal.sdk(11770): request failed with server response:
{"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"c9768bab5daf0"}

02-11 23:25:55.035: E/paypal.sdk(11770): UNKNOWN_ERROR

Will you please advice to get rid of this issue ? 
Awaiting for your feedback. 

Thanks
Rajesh K

**Comment by ppmtscory** [comment]
@ItsRajesh4uguys There's a couple of issues that I find with this:

1 - Your account is not eligible to process credit card payments.  Direct credit card eligibility can be found [here.](https://developer.paypal.com/webapps/developer/docs/integration/direct/rest_api_payment_country_currency_support/#direct-credit-card-payments)  Instructions for disabling credit card acceptance can be found [here.](https://github.com/paypal/PayPal-Android-SDK#international-support)

2 - Domestic payments are currently not allowed for India.  When switching to PayPal payments for your testing, be sure that your buyer account is not an Indian account.

**Comment by pankaj89** [comment]
Hello,
Same issue i got in Paypal PayPalAndroidSDK-2.11.0, But when i checked same transaction with same secret with IOS SDK it works fine

Will you please advice how to resolve this issue on android side?
Thanks
Pankaj Sharma

**Comment by ppmtscory** [comment]
@pankaj89 are you referring to the "unknown error"?  If so, please provide a debug ID that I can look up to see what's happening in your instance.  Also, please verify that your account is eligible to process CC payments and also that you are not attempting a domestic payment (India -> India).

**Comment by pankaj89** [comment]
@ppmtscory yes issue is for "unknown error".
debug_id is 014bebb3a54ec
Response : 
{"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"014bebb3a54ec"}

**Comment by ppmtscory** [comment]
@pankaj89 my initial response of country eligibility and India domestic payments, matches exactly to your error.  You need to review the links about for country eligibility of direct credit card payments as well as make sure that your "buyer" account is not registered in India if that's where the merchant account is registered.
