### ISSUE TITLE
checkout-session not created paypal

### ISSUE THREAD

**Issue by chucuo1** [paypal/PayPal-Android-SDK#139]
request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"3e684e22f3739","message":"checkout-session not created","information_link":"https://api.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

help me

	private static PayPalConfiguration config = new PayPalConfiguration()
			.environment(CONFIG_ENVIRONMENT)
			.clientId(CONFIG_CLIENT_ID)
			.merchantName("Hipster Store")
			.acceptCreditCards(false)
			.merchantPrivacyPolicyUri(
					Uri.parse("https://www.paypal.com/privacy"))
			.merchantUserAgreementUri(Uri.parse("https://www.paypal.com/legal"));;

**Comment by ppmtscory** [comment]
@chucuo1 After looking at the logs, I'm seeing a standard payment decline for your attempts.
