### ISSUE TITLE
2. Problem setting up the payment- Error PAYMENT_CREATION_ERROR - HELP!

### ISSUE THREAD

**Issue by PhilipBH** [paypal/PayPal-Android-SDK#144]
I have 2 PayPal accounts, both are Business Accounts.

Receiver has a balance of US$1.95 but the card attached to the account has expired.

Sender is set up with valid card attached to account.

The LogCat warning and errors I am receiveing is shown below:
W/paypal.sdk(28630): ae SN:17 PayPal Debug-ID: d63824e38c124 [live, 2.8.5;release]
E/paypal.sdk(28630): request failure with http statusCode:422,exception:org.apache.http.client.HttpResponseException: Unprocessable Entity
E/paypal.sdk(28630): request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"d63824e38c124","message":"checkout-session not [link removed]
E/paypal.sdk(28630):
E/paypal.sdk(28630): PAYMENT_CREATION_ERROR

** Is there a problem with the application sdk integration or is it just because the receiver doesn't have a valid bank account or card attached to the account?

Screenshot:
![screenshot_2015-02-19-20-00-25](https://cloud.githubusercontent.com/assets/11082948/6278993/412e6254-b872-11e4-8e21-e39ef92fbcd0.png)

**Comment by ppmtscory** [comment]
@PhilipBH You are right about the receiver account.  Since the receiving account is not allowed to hold a balance, it needs to have a method to withdraw the funds attached to it.

**Comment by PhilipBH** [comment]
Thanks for confirming.
