### ISSUE TITLE
Live Transaction can't be created

### ISSUE THREAD

**Issue by johnsonhedou** [paypal/PayPal-Android-SDK#151]
Hi Team,

I constantly got the following error when switch to live mode. please help.

Paypal SDK version: 2.8.5

03-19 11:15:49.994: E/paypal.sdk(1252): request failure with http statusCode:422,exception:org.apache.http.client.HttpResponseException: Unprocessable Entity
03-19 11:15:49.994: E/paypal.sdk(1252): request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"8292e36aa3a97","message":"checkout-session not created","information_link":"https://api.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

**Comment by mattjacunski** [comment]
@johnsonhedou - It looks like you may be trying to pay with the same account that would be receiving the funds.  This is not supported by PayPal - CANNOT_PAY_SELF.  Please try the payment with a different payer account.

We will investigate why this error is not making it out to the calling app.  Thanks for reporting this.

**Comment by mattjacunski** [comment]
Update - we are still waiting for a valid error to be returned by internal PayPal services so the SDK can display a more meaningful error.

**Comment by tomwhipple** [comment]
I'm going to close this since the problem has been identified and resolved. Once error messaging is fixed on the backend, the change will be included.
