### ISSUE TITLE
Request fails (400), 2 decimal places needed

### ISSUE THREAD

**Issue by flavienlaurent** [paypal/PayPal-Android-SDK#158]
When I build a PayPalItem with a price of "16.2", it fails with a bad request error from the backend because 2 decimal places are required.

1. I think it could fail before trying to send the payload to the backend.
2. It could be better to format "16.2" as "16.20" before sending the payload, no?

Thanks :)

**Comment by mattjacunski** [comment]
@flavienlaurent - There is lots of request validation that the PayPal payments REST API does. We have chosen not to duplicate that verification in the SDK.  Rather, we hope to pass through the useful error messages that the payments backend produces.  Even the specific case you cite here is not true for all currencies.

**Comment by flavienlaurent** [comment]
@mattjacunski Thanks for your response but I'm curious of which currency doesn't consider "16.2" as "16.20".

**Comment by mattjacunski** [comment]
@flavienlaurent - Sorry, I was not clear.  I meant that it is not simply a matter of forcing the amount to 2 decimal places.  The Japanese yen currency, for example, supports no decimal places.

**Comment by flavienlaurent** [comment]
What I mean is that the PayPal SDK should format correctly the request payload if there is not any ambiguity.

**Comment by mattjacunski** [comment]
Yes, you have a point.  In fact, I believe we handled this better at one point.  Let me investigate a little.

**Comment by mattjacunski** [comment]
@flavienlaurent - I have verified with the current release that an app request for payment of 2.8 USD to the SDK results in server-side requests of "2.80" USD, properly formatted with 2 decimal places.  Please reopen this if you still see this issue.
