### ISSUE TITLE
Invalid Auth Code

### ISSUE THREAD

**Issue by meet2011** [paypal/PayPal-Android-SDK#164]
When implementing Future Payments it generates refresh token/access token for the first time thereafter it throws invalid auth code with new authorization code. Please refer below for the server side code.

$auth_code ='XXXXXXXXXXXXXXXXXXXXXXX';
$clientId ='XXXXXXXXXXXXXXXXXXXXXXXXX';
$clientSecret ='XXXXXXXXXXXXXXXXXXXXXX';

$host = 'https://api.sandbox.paypal.com/v1/oauth2/token/';
$post_data = 'grant_type=authorization_code&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code='.$auth_code;

    $curl = curl_init($host);
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

    curl_setopt($curl, CURLOPT_USERPWD, $clientId.":".$clientSecret);
    curl_setopt($curl, CURLOPT_HEADER, false);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

    curl_setopt($curl, CURLOPT_POSTFIELDS, $post_data );
    curl_setopt($curl, CURLOPT_VERBOSE, TRUE);

    $response = curl_exec( $curl );

    curl_close($curl); // close cURL handler
    echo $response;

This returns 'Invalid Auth Code'

**Comment by ppmtscory** [comment]
@meet2011 please see my last email to you this morning.
