### ISSUE TITLE
Websocket adress error

### ISSUE THREAD

**Issue by nwidal** [paypal/PayPal-Android-SDK#168]
Got that log after switing to sandbox / production mode from noNetwork
java.lang.IllegalStateException: Cannot get websocket address
Updated IDE (netbeans) and also build with commandline tool.
Error keeps on killing the app running on Android 4.2, 4.3, 4.4

Did I made a mistake in configuration?

Here my Angular wrapped code:

app.factory('Wallet', function ($q, $window) {
        var service = {
            initPaymentUI: initPaymentUI,
            onSuccesfulPayment: onSuccesfulPayment,
            onFuturePaymentAuthorization: onFuturePaymentAuthorization,
            createPayment: createPayment,
            configuration: configuration,
            onPrepareRender: onPrepareRender,
            onPayPalMobileInit: onPayPalMobileInit,
            onUserCanceled: onUserCanceled,
            makePayment: makePayment
        };

        function initPaymentUI() {
            var clientIDs = {
                "PayPalEnvironmentProduction": "APP-XXXXXXXX",
                "PayPalEnvironmentSandbox": "APP-XXXXXXXX"
            };
            PayPalMobile.init(clientIDs, onPayPalMobileInit());

        }

        function onSuccesfulPayment(payment) {
            console.log("payment success: " + JSON.stringify(payment, null, 4));
            //alert("Zahlung erfolgreich");
        }

        function onFuturePaymentAuthorization(authorization) {
            console.log("authorization: " + JSON.stringify(authorization, null, 4));
        }
        function createPayment(summe,id,art) {
            // for simplicity use predefined amount
            var netto = summe/1.19;
            var mwst = summe-netto;
            var paymentDetails = new PayPalPaymentDetails(netto, mwst);
            var payment = new PayPalPayment(summe, "EUR", id, art, paymentDetails);
            return payment;
        }
        function configuration() {
            // for more options see `paypal-mobile-js-helper.js`
            var config = new PayPalConfiguration({merchantName: "HK photographics", merchantPrivacyPolicyURL: "https://mytestshop.com/policy", merchantUserAgreementURL: "https://mytestshop.com/agreement"});
            return config;
        }
        function onPayPalMobileInit() {
            // must be called
            // use PayPalEnvironmentNoNetwork mode to get look and feel of the flow
            PayPalMobile.prepareToRender("PayPalEnvironmentSandbox", configuration(), onPrepareRender());
        }
        function onUserCanceled(result) {
            console.log(result);
            //alert("Zahlung nicht erfolgreich.");
        }
        function onPrepareRender() {}

        function makePayment(summe,id,art) {
            PayPalMobile.renderSinglePaymentUI(createPayment(summe,id,art), onSuccesfulPayment(), onUserCanceled());
        }

        return service;
    });

Thanks a lot :)!

**Comment by mattjacunski** [comment]
@nwidal -- Could you please share a stacktrace or other logging?  One thing I notice from what you have posted here is that "APP-xxxxxxx" is the format of legacy credentials.  Are these really the client_id values you see when you select your app from https://developer.paypal.com/developer/applications ?

**Comment by nwidal** [comment]
H! Thanks for the reply. I also took the client_id from the page you mentioned.

Netbeans log says: 

SEVERE [org.netbeans.modules.cordova.platforms.api.ProcessUtilities]: No output when executing C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe [forward, tcp:9222, localabstract:webview_devtools_remote_25881]
INFO [org.netbeans.modules.cordova.platforms.android.AndroidDebugTransport]: Cannot get websocket address.

And former log said:

java.lang.IllegalStateException: Cannot get websocket address
   at org.netbeans.modules.cordova.platforms.android.AndroidDebugTransport.getURI(AndroidDebugTransport.java:118)
   at org.netbeans.modules.cordova.platforms.android.AndroidDebugTransport.createWebSocket(AndroidDebugTransport.java:77)
   at org.netbeans.modules.cordova.platforms.MobileDebugTransport.attach(MobileDebugTransport.java:78)
   at org.netbeans.modules.cordova.platforms.android.AndroidDebugTransport.attach(AndroidDebugTransport.java:87)
   at org.netbeans.modules.cordova.CordovaPerformer.startDebugging(CordovaPerformer.java:225)
   at org.netbeans.modules.cordova.platforms.android.AndroidActionProvider$1.run(AndroidActionProvider.java:141)

**Comment by nwidal** [comment]
Is there a possibilty that I haven't confugered the websocket or do I even need to do that?

**Comment by mattjacunski** [comment]
Some of this looked unfamiliar to me because it is Cordova, not the Android SDK.  You may do better to post this question in the [PayPal-Cordova-Plugin repo](https://github.com/paypal/PayPal-Cordova-Plugin).
