### ISSUE TITLE
There was a problem setting up this payment. Please visit the paypal website to check your account.

### ISSUE THREAD

**Issue by kgautam053** [paypal/PayPal-Android-SDK#181]
I am getting the following error while making the payment through paypal using sendbox.

There was a problem setting up this payment. Please visit the paypal website to check your account.

Logcat error : 
07-08 16:58:03.114: E/paypal.sdk(28614): request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"4ec87f1d038d2","message":"checkout-session not created","information_link":"https://api-m.sandbox.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

Please let me know the solution for this, Thanks in advance.

**Comment by jziaja** [comment]
Hi @kgautam053, it looks like you're trying to create a payment using an account whose country (India in this case) is not currently supported for PayPal REST payments.  Please refer to [Country & Currency Support for PayPal REST API Payments](https://developer.paypal.com/webapps/developer/docs/integration/direct/rest_api_payment_country_currency_support/) for specific country support.  Also note that domestic payments are currently not allowed for India.

**Comment by kgautam053** [comment]
Thanks for the information. It is really very helpful for me. I will try
send payment to PayPal supported country.

**Comment by muzammilmodan** [comment]
Hello,

Please open this url, your transactions show all data, 
https://www.sandbox.paypal.com/businessexp/summary

Thanks.

**Comment by s-pra** [comment]
There was a problem setting up this payment. Please visit the paypal website to check your account.

Log I am getting;-  W/ResourceType: Failure getting entry for 0x010802c9 (t=7 e=713) in package 0 (error -75)  and {"name":"PAYMENT_CREATION_ERROR","debug_id":"5d2b220863e65","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
E/paypal.sdk: PAYMENT_CREATION_ERROR
