### ISSUE TITLE
Mobile SDK Failing With Internal Service Error

### ISSUE THREAD

**Issue by tarekf** [paypal/PayPal-Android-SDK#185]
We are unable to process payments through the mobile SDK on Android and iOS (prod environment) due to an Internal Service Error happening when logging in from the SDK screens.

The logs we are seeing:
W/paypal.sdk( 8554): bW SN:43 PayPal Debug-ID: 302a3ee8bec49 [live, 2.9.1;release]
E/paypal.sdk( 8554): request failure with http statusCode:500,exception:org.apache.http.client.HttpResponseException: Internal Server Error
E/paypal.sdk( 8554): request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","debug_id":"302a3ee8bec49","message":"An internal service error has occurred","information_link":"https://api-m.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}
E/paypal.sdk( 8554): 
E/paypal.sdk( 8554): INTERNAL_SERVICE_ERROR

**Comment by mattjacunski** [comment]
Looking into it...

**Comment by mattjacunski** [comment]
This was caused by an internal service change in PayPal.  Working on a remedy now.

**Comment by tarekf** [comment]
Is there an ETA on a fix? This is causing an almost complete outage for us.

**Comment by mattjacunski** [comment]
The responsible team is working on scheduling a rollback now - I expect is should be fairly soon.

**Comment by tomwhipple** [comment]
The rollback is complete and the error rate appears to have dropped back down to ~0.
