### ISSUE TITLE
Unable to make credit card payment

### ISSUE THREAD

**Issue by formatBCE** [paypal/PayPal-Android-SDK#186]
Hi guys!
I'm having an issue with CardIO part of SDK.
Now i'm coding in sandbox environment.
I managed to pay with paypal account successfully.
But i cannot make a payment with credit card (no matter, "dumb" or real). After entering card data and payment confirmation window just closes, leaving me with payment method choosing screen.
No logs or errors there too.
Can you help me?
P.S. 
BTW, i tried to make same payment on SampleApp, included into SDK. Same situation.
My test accounts are OK - US-based and with PRO license, that was confirmed by PayPal Support.

**Comment by matuzenko88** [comment]
I'm having same issue. Hope for your help guys.

**Comment by tomwhipple** [comment]
Hmm... sounds like there could be a bug. 

We'll need a little more information to resolve:

- What version of Android are you developing against? 
- What devices are giving you trouble? 
- Does it work to enter card numbers manually?
- Is anything printed in the LogCat?

**Comment by formatBCE** [comment]
Hi Tom! Thanks for response.
I'm using two devices, 5.0 and 5.1. Compiling against API 21.
I didn't try to launch on older versions as i don't have such devices now.
It's Asus Zenfone 2 and Google Nexus 10.
No, the issue exists for both card info enterimg cases.
No any word in logcat on all levels.

чт, 13 авг. 2015, 0:59, Tom Whipple <notifications@github.com>:

**Comment by jaypatel512** [comment]
Hey @formatBCE !

We have been able to reproduce this issue on our end. We are working on the fix. It should be on your way really soon. :)

**Comment by formatBCE** [comment]
Hi Jay! Thanks a lot!

чт, 13 авг. 2015, 2:37, Jay <notifications@github.com>:

**Comment by jaypatel512** [comment]
The latest release include the fix for the issue. Let me know if that resolves the issue. 

Thanks.

**Comment by formatBCE** [comment]
@jaypatel512 Thank you, confirm solving.
