### ISSUE TITLE
PayPal Service Exception

### ISSUE THREAD

**Issue by alexandrakosh** [paypal/PayPal-Android-SDK#187]
We are using the newest PayPal SDK, and recently received the following exception:

java.lang.RuntimeException
line -1 in PayPalService.onStartCommand()
Service extras required. Please see the docs.

I read it can be from leaving the paypal opened for a long time, but think it was solved. Are there any other insights?

**Comment by jaypatel512** [comment]
Are you using the latest version of SDK ? 
If so, did you saw this exception when you kept the paypal opened for a long time ? 

Any context behind it would help.

Android Version:
Device:
SDK Version:

Also, are you receiving this exception consistently, or intermittently ?

**Comment by jaypatel512** [comment]
A relatable stackoverflow question: http://stackoverflow.com/a/18154106/486784

**Comment by ppmtscory** [comment]
Assuming this is resolved based on inactivity.  Feel free to reopen or open another issue if needed.
