### ISSUE TITLE
PaymentActivity not closed after enter credit card info

### ISSUE THREAD

**Issue by fcruzsbtv** [paypal/PayPal-Android-SDK#189]
We are using the "PayPalPayment.PAYMENT_INTENT_ORDER" but after the user enter it's credit card info and confirms the payment, the app remains in the initial chooser screen ( the one that let you choose between "Paypal" and "Credit card") if I hit the back button it closes but I get the cancel activity result

**Comment by jaypatel512** [comment]
Are you using the final release ? We found an issue where the Credit Card flow was automatically returning back to chooser screen. 

Related Issue: https://github.com/paypal/PayPal-Android-SDK/issues/186

Please re-open if this is not the case.
