### ISSUE TITLE
Redirect URL_ issue

### ISSUE THREAD

**Issue by ashishsakarkar2020** [paypal/PayPal-Android-SDK#190]
```json
"body": {
		"message": "Invalid request - see details",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR",
		"details": [
			{
				"field": "redirect_urls",
				"issue": "This field required when payment_method is \\u0027paypal\\u0027"

```

Earlier the payments were being processed. The app suddenly stopped excepting paymetns and i get the above response. #Help ASAP

**Comment by mattjacunski** [comment]
@ashishsakarkar2020 Another line of the log you posted above should include a `debug_id`.  Can you post that here too?

**Comment by ashishsakarkar2020** [comment]
{
	"status": 400,
	"duration_time": 441,
	"body": {
		"message": "Invalid request - see details",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR",
		"details": [
			{
				"field": "redirect_urls",
				"issue": "This field required when payment_method is \\u0027paypal\\u0027"
			}
		],
		"name": "VALIDATION_ERROR",
		"debug_id": "3f3177845638b"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "291",
		"Content-Language": "*",
		"CORRELATION-ID": "3f3177845638b",
		"Date": "Mon, 31 Aug 2015 05:30:43 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "3f3177845638b",
		"PROXY_SERVER_INFO": "host\\u003ddcg11javapapi3842.dcg11.slc.paypalinc.com;threadId\\u003d12966",
		"Content-Type": "application/json"
	}



Here is the complete response.

**Comment by jaypatel512** [comment]
It seems like you are currently using `PayPalSDK/PayPal-Android-SDK 2.0.2` version of SDK based on the user agent. Can you please update the SDK to latest version, and let us know if you are still facing this issue ? 

The latest version is [v2.9.11](https://github.com/paypal/PayPal-Android-SDK/releases/tag/2.9.11)

**Comment by ppmtscory** [comment]
@ashishsakarkar2020 this error happens when you are trying to pay yourself.  You aren't allowed to use the same email address that's tied to your client ID, to go through the checkout flow in your app.
