### ISSUE TITLE
request failure with http statusCode:422,exception:org.apache.http.client.HttpResponseException: Unprocessable Entity

### ISSUE THREAD

**Issue by josefgrunig-seac02** [paypal/PayPal-Android-SDK#199]
Hi,
in the sandbox environment I get this error:

```
request failure with http statusCode:422,exception:org.apache.http.client.HttpResponseException: Unprocessable Entity
request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"a9f83ee62c843","message":"checkout-session not created","information_link":"https://api-m.sandbox.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
```
I tried also to change sandbox test account with another country:
```
request failure with http statusCode:422,exception:org.apache.http.client.HttpResponseException: Unprocessable Entity
09-29 12:42:41.984  18662-28531/com.panini.collectors E/paypal.sdk﹕ request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"d01cdb052de1b","message":"checkout-session not created","information_link":"https://api-m.sandbox.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
```

do you have more feedback from the debug ids?

**Comment by ppmtscory** [comment]
@josefgrunig-seac02 there were a lot of issues within the sandbox environment yesterday on our end.  Can you please try again and let me know if you're still getting the same error?  If so, please let me know the debug ID.

**Comment by Archieeeeee** [comment]
Hi,
Have the same issues since Sep 27, trying to update to the latest SDK does not work,

E/paypal.sdk: request failure with http statusCode:422,exception:org.apache.http.client.HttpResponseException: Unprocessable Entity
E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"b6dxxxxxxc18","message":"checkout-session not created","information_link":"https://api-m.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

**Comment by ppmtscory** [comment]
@Archieeeeee your error is stemming from trying to use the same account to pay for the funds that you are using to receive the funds.  The error I see internally is "ERR=CANNOT_PAY_SELF".  Please use a different "buyer" account than the one you are using to receive funds.

**Comment by mickyarun** [comment]
Hi
I facing followin error in sandbox
11-03 00:02:36.622 898-2250/com.jamhub.samyakk E/paypal.sdk: request failure with http statusCode:422,exception:org.apache.http.client.HttpResponseException: Unprocessable Entity
11-03 00:02:36.632 898-2250/com.jamhub.samyakk E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"eab940d08fc7f","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
11-03 00:02:36.632 898-2250/com.jamhub.samyakk E/paypal.sdk: 
11-03 00:02:36.632 898-898/com.jamhub.samyakk E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by ppmtscory** [comment]
@mickyarun you are exceeding your per transaction limit which is $10K for USD.

**Comment by mickyarun** [comment]
@ppmtscory Thank you it worked

**Comment by PankajSavaliyaGit** [comment]
Hii..
I have same error like this
How to solve this error?
paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity

paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"7ce6661cd51a","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by ppmtscory** [comment]
@PankajSavaliyaGit this issue is likely account related or account setup related.  Please file a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team to have them take a look at the accounts being used.

**Comment by Tejpandya** [comment]
hello .. 
i'm facing the same error and stuck at my end ..

 E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
 E/paypal.sdk: request failed with server response {"name":"PAYMENT_CREATION_ERROR","debug_id":"51ffb3f97915a","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
 E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by xiaoleih41** [comment]
@Tejpandya It looks like you were trying to pay yourself. Sender and receiver cannot be the same account. I can see other transactions on your account went through successfully. I am locking the conversation of this thread as the original issue should have been solved.
