### ISSUE TITLE
Alternate view for adaptive chained payment

### ISSUE THREAD

**Issue by meet2011** [paypal/PayPal-Android-SDK#202]
We are using adaptive chained payment method using server code and it works perfectly but we don't want whole user interface to be web view compatible.

Is there any option to have native screen instead of web view/external browser?? We need to have credit card and Paypal payment options.

We tried through Mobile Payment Library but it doesn't provide credit card option so we have opted through server

Please provide possible solution

**Comment by ppmtscory** [comment]
Unfortunately there is no true mobile flow for Adaptive Payments aside from the Mobile Payments Library.  However, as you pointed out, MPL doesn't offer support for credit card or guest payments - only PayPal payments.  It's possible that there may be a more mobile friendly situation when Adaptive Payments gets built into the REST APIs, but I can't guarantee anything specific.  For the time being, if you want mobile, it will need to be within a webview or external browser.

**Comment by sparra1000** [comment]
What about using Embedded Payment Flow in Android webview?  Will that work?  It looks mobile friendly. https://developer.paypal.com/webapps/developer/docs/classic/adaptive-payments/ht_ap-embeddedPayment-curl-etc/
