### ISSUE TITLE
Embedded Payment Flow for Adaptive Chained Payments in native Android webview

### ISSUE THREAD

**Issue by sparra1000** [paypal/PayPal-Android-SDK#203]
We have successfully implemented Adaptive chained payments with server code but the user interface in the native Android webview isn't mobile friendly.  Embedded Payment Flow looks mobile friendly, is it compatible with Android webview for native apps?

**Comment by ppmtscory** [comment]
You can sure give it a try!  I believe some developers have went that route.  The embedded flow is the closest to mobile friendly as you'll get so if you can get it to work correctly within the webview, it's definitely a viable solution.
