### ISSUE TITLE
 request failure with http statusCode:422,exception:org.apache.http.client.HttpResponseException: Unprocessable Entity

### ISSUE THREAD

**Issue by pkhutal** [paypal/PayPal-Android-SDK#204]
Hello,
I am integrating Paypal android sdk.i have two accounts as buyer and facilitator.But when purshase is done it is giving me error in while using sandbox ids.
Below is the error I am getting as:

10-14 16:16:54.081: E/paypal.sdk(3342): request failure with http statusCode:422,exception:org.apache.http.client.HttpResponseException: Unprocessable Entity
10-14 16:16:54.082: E/paypal.sdk(3342): request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"b3e3626f549a4","message":"checkout-session not created","information_link":"https://api-m.sandbox.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
10-14 16:16:54.082: E/paypal.sdk(3342): 
10-14 16:16:54.089: E/paypal.sdk(3342): PAYMENT_CREATION_ERROR
10-14 16:16:54.099: E/Surface(3342): getSlotFromBufferLocked: unknown buffer: 0x9bd69420

Please let me know what problem is.

**Comment by bluk** [comment]
Can you try again now? There was an issue with sandbox earlier but it should be fixed.

**Comment by pkhutal** [comment]
No, again getting same error

**Comment by pkhutal** [comment]
In fact i tried with two different sandbox client ids.I am Using Sample For andriod Application and i just change client id and CONFIG_ENVIRONMENT to PayPalConfiguration.ENVIRONMENT_SANDBOX rest all code is same provide in sample.
Thank you for quick response.

**Comment by jaypatel512** [comment]
Hey @pkhutal !

I just tested the sample app on sandbox environment, and was able to successfully create a payment. We realized this bug yesterday, and was fixed today morning. I will investigate further into this, however, please see if you are able to replicate this issue again ? And if so, can you please share its `debug_id` ? This will help us investigate a bit further.

**Comment by ppmtscory** [comment]
@pkhutal you are getting this error because you are testing with an Indian buyer and Indian seller account.  Domestic payments are not currently available for India - only international payments.  If you are going to test with an Indian merchant account, please use a buyer account that's not registered in India.

**Comment by pkhutal** [comment]
yes i am testing with Indian buyer and seller account.But i dont have any country account other than India.

**Comment by ppmtscory** [comment]
You can create different sandbox accounts for different countries in the developer portal.  Login at developer.paypal.com > click dashboard > click sandbox accounts on left menu > click create > choose the country you want the account registered in.

**Comment by pkhutal** [comment]
ok...let me check...thank you

**Comment by pkhutal** [comment]
thank you..its working :)

**Comment by ppmtscory** [comment]
Awesome!  Glad to hear it!

**Comment by ShivangiAgrawal** [comment]
Hey i am using sandbox client id with environment being set to sandbox only. I created sandbox account with US as country not India but still its showing same error.

**Comment by ppmtscory** [comment]
@ShivangiAgrawal this issue has been closed for some time.  Please file a separate issue with a detailed explanation of your error, which would include debug ID's.

**Comment by daniramdan74** [comment]
please help me,
i have a proble for my application and this my error : 

09-20 13:05:57.446 22077-22646/com.dani.skripsi.paypal_integration W/paypal.sdk: ff SN:11 PayPal Debug-ID: c7f73ea73e4a2 [sandbox, 2.14.5;release]
09-20 13:05:57.447 22077-22646/com.dani.skripsi.paypal_integration E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
09-20 13:05:57.447 22077-22646/com.dani.skripsi.paypal_integration E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"c7f73ea73e4a2","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
09-20 13:05:57.452 22077-22077/com.dani.skripsi.paypal_integration E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by sagarikadas91** [comment]
I have the below problem. Please help me out. 
11-10 15:05:49.828 30851-8987/example.paypal.paymentsample E/paypal.sdk: request failure with http statusCode:422,exception:
11-10 15:05:49.828 30851-8987/example.paypal.paymentsample E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"1bf5738f5f74","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
11-10 15:05:49.829 30851-30851/example.paypal.paymentsample E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by pp-randy** [comment]
@sagarikadas91 I have updated you in a different issue.  

Locking this thread, for anyone experiencing this please create a new issue as it will most likely have a different cause.
