### ISSUE TITLE
Payment to this merchant is not allowed (invalid clientid)

### ISSUE THREAD

**Issue by MrXlebNick** [paypal/PayPal-Android-SDK#210]
Payment to this merchant is not allowed (invalid clientid) 
Exactly this message I see when I'm trying to pay via Paypal Android SDK

Here is the fragments of code where Paypal logic is situated
https://gist.github.com/MrXlebNick/07cf84beeddcba40caf8
And as adding to this, onActivityResult is also connected with Paypal. What should I do to make it work?
I made sure that The AppId is correct, mode is correct. What can be wrong?

**Comment by tomwhipple** [comment]
Based on your gist you might be using the wrong `client_id`. If the real one starts with `APP-` you're using a credential from an older API. Go to https://developer.paypal.com/developer/applications/ to create an app and use the credentials you get from that dashboard.

**Comment by MrXlebNick** [comment]
So I should use that long clientid without -APP, shouldn't I?

**Comment by ppmtscory** [comment]
@MrXlebNick yes, the client ID should *not* contain "App-".

**Comment by ikuriel** [comment]
i already created App from https://developer.paypal.com/developer/applications/

And copied Client ID to my app, but im getting same error window.

**Comment by ikuriel** [comment]
my bad, i was ussing Client ID from sandbox, i changed to Live and everything is working.
