### ISSUE TITLE
unable to pay auth anymore

### ISSUE THREAD

**Issue by bahacan19** [paypal/PayPal-Android-SDK#215]
I am stuck to this error :
10-30 16:28:47.208  17317-28957/com.nomad.basefy E/paypal.sdk﹕ request failure with http statusCode:422,exception:org.apache.http.client.HttpResponseException: Unprocessable Entity
10-30 16:28:47.208  17317-28957/com.nomad.basefy E/paypal.sdk﹕ request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"26064546f7b05","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
10-30 16:28:47.216  17317-17317/com.nomad.basefy E/paypal.sdk﹕ PAYMENT_CREATION_ERROR

**Comment by bluk** [comment]
@bahacan19  Is this on sandbox? If so, please refer to paypal/PayPal-iOS-SDK#355 for further updates for that error. If not, please reopen the issue.

**Comment by bahacan19** [comment]
this is on sandbox. 
thx
