### ISSUE TITLE
PayPal goods vs. services

### ISSUE THREAD

**Issue by grembek** [paypal/PayPal-Android-SDK#216]
Hi,

How can I make the transaction marked as goods always so that all the users will specify their address?

Thanks

**Comment by ppmtscory** [comment]
@grembek you would simply tell the SDK whether you are supplying the shipping address or you want them to choose it.  To provide a shipping address for the payment, see addAppProvidedShippingAddress(...) in the sample app. To enable retrieval of shipping address from the user's PayPal account, see enableShippingAddressRetrieval(...) in the sample app.

**Comment by grembek** [comment]
I do get the shipping address once in a while, but only if the user provides it, is there a way to make it mandatory for him to provide it? I cannot ship the goods if I don't have the address

**Comment by ppmtscory** [comment]
If you enable the retrieval of the shipping address from their PayPal account, then you should get an address every time.  It will either be their default address or they can select a different one on their account.

**Comment by grembek** [comment]
Thanks
