### ISSUE TITLE
Problems with REST API with android app.

### ISSUE THREAD

**Issue by Palle-Technologies** [paypal/PayPal-Android-SDK#220]
I am integrating paypal with android sdk with the help of https://github.com/paypal/PayPal-Android-SDK. Sandbox testing went fine without any issue. My merchant account is set up in India.
But when I moved to production and tested, I am facing an issue.

Issue : I asked my friend in USA to test with USA credit card with pay with card option, which is failing with error "Payment failed" with error information "The merchant does not accept payments of this type".
My friend used USA bank of america credit card.
On searching more about this issue, I found out that since my merchant account is set up in India and since I am using rest api, direct credit card transactions are not possible. I want to know if this is true? But since credit card is USA credit card, it should work. Is n't it?

Is there any workaround for Indian merchants to accept direct credit card payments in android application with paypal?

**Comment by jaypatel512** [comment]
Direct Credit Card Payment is only available for US and UK currently. Also, for UK, you need to have a Pro account. It is not possible currently to accept direct credit card for Indian account.
