### ISSUE TITLE
System Error. Please try again later

### ISSUE THREAD

**Issue by pavitramirraw** [paypal/PayPal-Android-SDK#222]
12-04 19:47:56.020 2969-3170/com.paypal.example.paypalandroidsdkexample.debug W/paypal.sdk: fk SN:8 PayPal Debug-ID: 277e041ec4a68 [sandbox, 2.12.1;release]
12-04 19:47:56.020 2969-3170/com.paypal.example.paypalandroidsdkexample.debug E/paypal.sdk: request failure with http statusCode:400,exception:Bad Request
12-04 19:47:56.025 2969-3170/com.paypal.example.paypalandroidsdkexample.debug E/paypal.sdk: request failed with server response:{"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"277e041ec4a68"}
12-04 19:47:56.035 2969-2969/com.paypal.example.paypalandroidsdkexample.debug E/paypal.sdk: UNKNOWN_ERROR
12-04 19:47:56.170 2969-2969/com.paypal.example.paypalandroidsdkexample.debug D/mali_winsys: new_window_surface returns 0x3000
12-04 19:47:56.180 2969-2969/com.paypal.example.paypalandroidsdkexample.debug E/ViewRootImpl: sendUserActionEvent() mView == null

**Comment by ppmtscory** [comment]
@pavitramirraw there's 2 things here:

1. DCC (direct credit card) transactions are not allowed for India merchants.  Please disable the credit card section if you are going to be utilizing the mSDK with an Indian merchant account.
2. Domestic payments are not allowed for India.  If you're using an Indian merchant account, then you will need to use an international account as the buyer for testing. 

I've previously filed the ticket internally to get the error message to be more meaningful, but if you make the above corrections, that will resolve your issue.
