### ISSUE TITLE
Unauthorised Payment Issue

### ISSUE THREAD

**Issue by pavitramirraw** [paypal/PayPal-Android-SDK#224]
12-07 12:35:11.200 9903-11696/com.paypal.example.paypalandroidsdkexample.debug W/paypal.sdk: fk SN:8 PayPal Debug-ID: f4174b7179b04 [live, 2.12.1;release]
12-07 12:35:11.200 9903-11696/com.paypal.example.paypalandroidsdkexample.debug E/paypal.sdk: request failure with http statusCode:401,exception:Unauthorized
12-07 12:35:11.205 9903-11696/com.paypal.example.paypalandroidsdkexample.debug E/paypal.sdk: request failed with server response:{"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT","debug_id":"f4174b7179b04"}
12-07 12:35:11.220 9903-9903/com.paypal.example.paypalandroidsdkexample.debug E/paypal.sdk: UNAUTHORIZED_PAYMENT

**Comment by ppmtscory** [comment]
@pavitramirraw you are getting that message because you are attempting to process direct credit card payments with a merchant account registered in a country where it's not available.  Direct Credit Card transactions with the mSDK (and REST API in general) is available in US and UK only.
