### ISSUE TITLE
please update the documentation after maven version library release 

### ISSUE THREAD

**Issue by Folyd** [paypal/PayPal-Android-SDK#227]
maven central version is aar file include a AndroidManifest file, developer should not declear duplicate activity stuffs...

here is the aar file AndroidManifest file:

    <?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
         package="com.paypal.android.sdk.payments" >

    <uses-sdk
        android:minSdkVersion="10"
        android:targetSdkVersion="23" />

    
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />

    <application android:allowBackup="true" >
        <activity android:name="com.paypal.android.sdk.payments.PaymentActivity" />
        <activity android:name="com.paypal.android.sdk.payments.PaymentMethodActivity" />
        <activity android:name="com.paypal.android.sdk.payments.PaymentConfirmActivity" />
        <activity
            android:name="io.card.payment.CardIOActivity"
            android:configChanges="keyboardHidden|orientation" />
        <activity android:name="io.card.payment.DataEntryActivity" />
        <activity android:name="com.paypal.android.sdk.payments.LoginActivity" />
        <activity android:name="com.paypal.android.sdk.payments.PayPalFuturePaymentActivity" />
        <activity android:name="com.paypal.android.sdk.payments.FuturePaymentConsentActivity" />
        <activity android:name="com.paypal.android.sdk.payments.FuturePaymentInfoActivity" />
        <activity android:name="com.paypal.android.sdk.payments.PayPalProfileSharingActivity" />
        <activity android:name="com.paypal.android.sdk.payments.ProfileSharingConsentActivity" />

        <service
            android:name="com.paypal.android.sdk.payments.PayPalService"
            android:exported="false" />
    </application>

</manifest>

**Comment by jaypatel512** [comment]
You are correct @Folyd !

We will remove that from the docs very soon. Thanks for pointing it out.

**Comment by jaypatel512** [comment]
Fixed in [2.12.4](https://github.com/paypal/PayPal-Android-SDK/releases/tag/2.12.4) release.
