### ISSUE TITLE
PAYMENT_CREATION_ERROR on Production Server

### ISSUE THREAD

**Issue by bernardoassis** [paypal/PayPal-Android-SDK#229]
Hi guys,

Yesterday me and some people are testing our app in the paypal production environment and a part of our testers (and myself) are receiving the response below while trying to make a simple payment using PayPal Android SDK. This error is intermittent, don't occur every time.

I've read some issues with the same error, but these cases aren't similar to that. The receiver account is different from the payer account, the value of the payment is less than a USD $1.

The details of the operations are below:

12-15 02:31:45.195 14211-16529/br.com.apppago.android E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
12-15 02:31:45.196 14211-16529/br.com.apppago.android E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"2b29e6343f367","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
12-15 02:31:45.198 14211-14211/br.com.apppago.android E/paypal.sdk: PAYMENT_CREATION_ERROR

12-15 02:31:58.712 14211-16529/br.com.apppago.android E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
12-15 02:31:58.714 14211-16529/br.com.apppago.android E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"b2da60e578671","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
12-15 02:31:58.715 14211-14211/br.com.apppago.android E/paypal.sdk: PAYMENT_CREATION_ERROR

We are ready to publish on Google Play. However i'm concerned with this recurring error. Can you guys get the error details based on these debug_ids and give me a solution?

Thanks in advance.

**Comment by ppmtscory** [comment]
@bernardoassis from everything I'm seeing with the debug_id, these are generic PayPal declines.  Unfortunately I can't see much more information than that but I don't see anything integration related to these errors.
