### ISSUE TITLE
PayPal 2.12.4 aar includes card.io AndroidManifest.xml components

### ISSUE THREAD

**Issue by cyrilmottier** [paypal/PayPal-Android-SDK#233]
When looking at the exploded aar `paypal-android-sdk:2.12.4`, we have 

```
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />

    <activity
        android:name="io.card.payment.CardIOActivity"
        android:configChanges="keyboardHidden|orientation" />
```

But this is also included as part of the transitive dependency of `io.card:android-sdk:5.1.2`. I would expect only having it in the Card io library.

**Comment by ChristianBecker** [comment]
Kind of related to #226.

**Comment by jaypatel512** [comment]
Hey @cyrilmottier !

Thanks for pointing this out. I will go ahead and make the appropriate changes right away. :+1:

**Comment by jaypatel512** [comment]
Hey @cyrilmottier !

We have pushed the [2.12.5](https://github.com/paypal/PayPal-Android-SDK/releases/tag/2.12.5) release, that should fix this problem.
