### ISSUE TITLE
Update OkHttp to 3.0.0

### ISSUE THREAD

**Issue by ChristianBecker** [paypal/PayPal-Android-SDK#236]
Do you plan to update the bundled OkHttp to 3.0.0?

As OkHttp 3.0.0 changes its Maven group ID (see http://jakewharton.com/java-interoperability-policy-for-major-version-updates/ ) an application can bundle now both OkHttp 2.x.x and OkHttp 3.x.x, which will result in a bloated APK size and DEX method count.

**Comment by jaypatel512** [comment]
Yes. We plan to update okhttp to 3.0.0 soon.

**Comment by ChristianBecker** [comment]
You're right, but it shouldn't be your library that still depends on OkHttp 2.x.x while all the other libraries migrated to OkHttp 3.x.x. ;)

And if this is the only change in the next version each developer can decide if he wants to upgrade to the new version.
