### ISSUE TITLE
Android Paypal sanbox is not working

### ISSUE THREAD

**Issue by giri** [paypal/PayPal-Android-SDK#240]
Getting the below message when using sandbox, below is android studio console log

i am using "com.paypal.sdk:paypal-android-sdk:2.12.5"

 E/paypal.sdk: request failed with server response:Certificate pinning failure!
01-21 14:39:41.610 3062-3140/? E/paypal.sdk:   Peer certificate chain:
01-21 14:39:41.610 3062-3140/? E/paypal.sdk:     sha1/SQ+EdYjo3ZoEORzSEC2JQV3g3L4=: CN=api-m.paypal.com,OU=CDN Support,O=PayPal\, Inc.,L=San Jose,ST=California,C=US
01-21 14:39:41.610 3062-3140/? E/paypal.sdk:     sha1/UCM4nF92oH7yVEZeTyGW+BRFtB4=: CN=Symantec Class 3 Secure Server CA - G4,OU=Symantec Trust Network,O=Symantec Corporation,C=US
01-21 14:39:41.610 3062-3140/? E/paypal.sdk:   Pinned certificates for api-m.sandbox.paypal.com:
01-21 14:39:41.610 3062-3140/? E/paypal.sdk:     sha1/u8I+KQuzKHcdrT6iTb30I70GsD0=
01-21 14:39:41.610 3062-3140/? E/paypal.sdk:     sha1/7Q3I1izTEynYgv4tw/zFENNNuxQ=
01-21 14:39:41.610 3062-3140/? E/paypal.sdk:     sha1/sYEIGhmkwJQf+uiVKMEkyZs0rMc=
01-21 14:39:41.610 3062-3140/? E/paypal.sdk:     sha1/gzF+YoVCU9bXeDGQ7JGQVumRueM=
01-21 14:39:41.670 3062-3062/? E/paypal.sdk: SERVER_COMMUNICATION_ERROR

**Comment by jaypatel512** [comment]
Please refer to @braebot comment as shown here: https://github.com/paypal/PayPal-Android-SDK/issues/228#issuecomment-173440220
