### ISSUE TITLE
Where is Lib folder

### ISSUE THREAD

**Issue by fazal110** [paypal/PayPal-Android-SDK#244]
Where is lib folder

**Comment by jaypatel512** [comment]
We recently introduced aar package that replaces the default jar libraries that were kept in libs/* directory. 

Now, all you need to do is, add a dependency in your build.gradle file as [shown here :](
https://github.com/paypal/PayPal-Android-SDK#add-the-sdk-to-your-project)
```
compile 'com.paypal.sdk:paypal-android-sdk:2.13.0'
```
