### ISSUE TITLE
handshake_failure

### ISSUE THREAD

**Issue by monsharen** [paypal/PayPal-Android-SDK#246]
Hi, 

First of all, sorry if this is the wrong place to raise this issue. If there's another github repo or forum I should turn to, please let me know. 

We've implemented your android SDK + the server side api for verifying purchases and we've just started getting error responses when establishing connections to your platform. This is the url we are connecting to for authentication: 

https://api.sandbox.paypal.com/v1/oauth2/token

When connecting we get the below error:

Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
...

Have you updated any certs recently?

Worth to note: 
* Notice that this is the sandbox environment
* Our production setup works fine

**Comment by bluk** [comment]
Yes, please see issue #228 . Are you having an issue with the Android SDK or the (I assume Java) server side SDK? The latest [Android SDK 2.13.0](https://github.com/paypal/PayPal-Android-SDK/releases) should resolve the certificate issue.

You can find more information about the certificate and TLS changes at the [PayPal 2016 Merchant Security Roadmap Microsite](https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1913&expand=true&locale=en_US). There is also a general [TLS update site](https://github.com/paypal/TLS-update) which contains requirements for the various SDKs.

**Comment by monsharen** [comment]
Thanks for the quick response! 

The issue occurs server side. As far as I can tell there is a certificate change going on for merchant accounts. Found below quote on your site: 

"To avoid any disruption of service, you must verify that your systems are ready for this change between February 4, 2016 and January 1, 2018."

Does this mean that we need to perform the change before Jan 1st 2018, or should we expect issues already?

**Comment by bluk** [comment]
Sandbox has been upgraded to only support TLS v1.2 and new SHA256 certs as part of the `TLS 1.2 and HTTP 1.1 Upgrade` and the `SSL Certificate Upgrade`. Production won't be changed until later this year (June 17th, 2016), but you can upgrade anytime now for production. You must upgrade your environment to support TLS v1.2 for sandbox. I think this is what you need to do given the endpoint you shared.

The quote you stated is for the Classic API which uses a different authentication method and has a different date.

Hope that helps.

**Comment by monsharen** [comment]
Superb, thanks bluk
