### ISSUE TITLE
CONFUSION related to so many library

### ISSUE THREAD

**Issue by mwshubham** [paypal/PayPal-Android-SDK#257]
I have a confusion that there are so many libraries like core MP MECL paypal sdk etc. 
Also there are so many type of payment gateway like paypal standard, paypal express checkout,
paypla mobile express checkout.

Actually i want to implement paypal mobile express checkout. How should i implement it in mobile application.

**Comment by ppmtscory** [comment]
I definitely understand the smorgasbord of information that's out there.  For your question directly, if you want a native app, then I'd recommend this [Android SDK](https://github.com/paypal/PayPal-Android-SDK) for PayPal payments.  If you are looking for something for a mobile optimized site, then I'd recommend [Mobile Express Checkout](https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECOnMobileDevices/).
