### ISSUE TITLE
Java 6 support

### ISSUE THREAD

**Issue by Chromdioxyde** [paypal/PayPal-Android-SDK#277]
Hi there,

i work for an OEM and we tried to integrate the PayPal SDK into one of the apps we ship with the device.
The Problem is, that we use Android 4.4 and this results in two pitfalls:

1. Our build system does not support Android Library Projects in the AAR format
2. We use Java 6 and the library seems to be compiled witch Java 7 (Java Version in Bytecode)

For the first Problem, we could try to extract the *.aar file and add resources and the classes.jar in the makefile, which would leave card.io non-functional because of the missing JNI libraries, right?

But this effort would be in vain because we cannot compile the library into our app because of Java version mismatch.

Is there any chance to get the SDK running in our environment?

**Comment by ppmtscory** [comment]
With the recent PCI council requirements for TLSv1.2 - we've had to make sure that all of our products are compliant.  With that being said, there isn't support for Java 6 or earlier.  You can find more information about this update, and how it relates to our SDKs, [here](https://github.com/paypal/TLS-update).
