### ISSUE TITLE
Italy - DDC (direct credit card)

### ISSUE THREAD

**Issue by ummo89** [paypal/PayPal-Android-SDK#284]
I'm Italian , How can I enable the DDC payment ?

I have a business account.

> "Direct credit card processing is not available for you when using REST APIs. Your live credentials are inoperable for direct credit card processing for your country but your test credentials are enabled for sandbox testing."

**Comment by bluk** [comment]
@ummo89 Sorry, the Android and iOS mobile SDKs are based on the REST APIs which does not currently process direct credit cards for your country. However, you can look at [Braintree](https://www.braintreepayments.com) which offers credit card, PayPal and other payment method support.
