### ISSUE TITLE
is there any way to  transfer  paypal to another paypal(two way transfer eg. i m giving service to some one they transfer amount on my paypal and i can also transfer amount to main owner. ) using my android app ? like PayPal button click on that if login and transfer amount any other paypal.  

### ISSUE THREAD

**Issue by narendra9593** [paypal/PayPal-Android-SDK#294]
### Required Information

- Mode (Mock/Sandbox/Live):
- PayPal Android SDK Version:
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

**Comment by pp-randy** [comment]
**Option 1:**  Using Classic APIs

I think the easiest solution would be to use Adaptive Payments chained payments: https://developer.paypal.com/docs/classic/api/adaptive-payments/Pay_API_Operation/

Unfortunately, Adaptive Payments  are not part of this particular SDK, at this time, as described here: https://github.com/paypal/PayPal-Android-SDK#older-libraries.  You would want to review the Mobile Payments Library for your use case.
***
**Option 2:** Using REST APIs

You could do this with the REST API and this SDK but could only accept the initial payment.  You would most likely need a server to then send the second part of this payment using the payouts api https://developer.paypal.com/docs/integration/direct/payouts-overview/.

**Comment by narendra9593** [comment]
The PayPal API does not support this kind of case on a mobile device. Instead, you'd need to implement the functionality from a secure backend and call the payout API.

**Comment by pp-randy** [comment]
For a pure mobile solution refer to Option 1 provided earlier. It would use the PayPal Adaptive Payments API.  And this Library https://github.com/paypal/sdk-packages/tree/gh-pages/MPL

You could use a Chained Payment, this payment flow would automatically happen.
Phone User -> Primary Account -> Secondary Account(s).
This is supported by the Mobile Payments Library (MPL). 

If you needed to delay the second payment this use case is not supported by the MPL.  Also I should make you aware we are seeing issues with the MPL in our sandbox environment currently. https://github.com/paypal/sdk-packages/issues/74
