### ISSUE TITLE
When switching to real money: ENVIRONMENT_PRODUCTiON I got this error Unautorized Divece error

### ISSUE THREAD

**Issue by HassanUsman** [paypal/PayPal-Android-SDK#297]
Running the Paypal Sample app, on Samsung Note Edge - 5.1, Using PayPal SDK for Android. 
The sample works perfect with when the below code is added:

CONFIG_ENVIRONMENT = PaymentActivity.ENVIRONMENT_NO_NETWORK;

When switching to real money:

CONFIG_ENVIRONMENT = PaymentActivity.ENVIRONMENT_PRODUCTION;
CONFIG_CLIENT_ID = "Afa................c";

I'm getting next error: "Payment from this device are not allowed",

**Comment by bluk** [comment]
@HassanUsman Can you post anything from the log? Specifically a PayPal-Debug-ID. Thanks.

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
