### ISSUE TITLE
Parallel payments

### ISSUE THREAD

**Issue by erummalik** [paypal/PayPal-Android-SDK#301]
### Required Information

- Mode (Sandbox):
- PayPal Android SDK Version:
- Android Version and Device ( Samsung S7 with Android 5.1):

### Issue Description
> Is there a way to do parallel payments in PayPal-Android-SDK

**Comment by ppmtscory** [comment]
Since this feature is not yet available in the underlying REST API, no, unfortunately there isn't a way to do Parallel payments with this Android SDK currently.
