### ISSUE TITLE
Request failure with http statusCode:422, environment Production

### ISSUE THREAD

**Issue by Simonida** [paypal/PayPal-Android-SDK#306]
### Required Information

- Mode Live
- PayPal Android SDK Version: com.paypal.sdk:paypal-android-sdk:2.14.4
- Android Version and Device (LG G2 with Android 4.4.2):
- PayPal-Debug-ID(s) (from any logs): 28e8ca83ec6a7

### Issue Description
I'm receiving the following error:

E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"28e8ca83ec6a7","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
E/paypal.sdk: PAYMENT_CREATION_ERROR

![screenshot_2](https://cloud.githubusercontent.com/assets/3587102/16741489/bbac7bbc-47a3-11e6-82e8-5bb504382bdf.png)

ClientId is valid, and environment is set to Production.
While testing on sandbox, payment was working fine. This porblem occured when we switched to production environment and set a new clientId.

Here is the complete code that is currently used:

```
public class PayPalActivity extends Activity {

private static final String CONFIG_ENVIRONMENT = PayPalConfiguration.ENVIRONMENT_PRODUCTION;
    private static final int REQUEST_CODE_PAYMENT = 1;
    private static PayPalConfiguration config = new PayPalConfiguration()
            .environment(CONFIG_ENVIRONMENT)
            .clientId(AppConstants.PAYPAL_CLIENT_ID)
            .merchantName("AppName")
            .merchantPrivacyPolicyUri(Uri.parse("http://www.example.com/privacy-policy"))
            .merchantUserAgreementUri(Uri.parse("http://www.example.com/terms-of-service"));

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Intent intent = new Intent(context, PayPalService.class);
        intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
        startService(intent);

        PayPalPayment thingToBuy = getThingToBuy(PayPalPayment.PAYMENT_INTENT_SALE, pivot);
        Intent intentPayment = new Intent(context, PaymentActivity.class);
        intentPayment.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
        intentPayment.putExtra(PaymentActivity.EXTRA_PAYMENT, thingToBuy);
        startActivityForResult(intentPayment, REQUEST_CODE_PAYMENT);

    }
    private PayPalPayment getThingToBuy(String paymentIntent, Pivot pivot) {
        String title = context.getResources().getString(R.string.paypal_order_title) + " " + event.getId();
        double price = pivot.getParticipation_fee_usd();
        return new PayPalPayment(new BigDecimal(price), "USD", title,
                paymentIntent);
    }

@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == REQUEST_CODE_PAYMENT) {
            if (resultCode == Activity.RESULT_OK) {
                PaymentConfirmation confirm =
                        data.getParcelableExtra(PaymentActivity.EXTRA_RESULT_CONFIRMATION);
                if (confirm != null) {
                    confirmPayment(confirm);
                }
            } else if (resultCode == Activity.RESULT_CANCELED) {
                Log.i(TAG, "The user canceled.");
            } else if (resultCode == PaymentActivity.RESULT_EXTRAS_INVALID) {
                Log.i(TAG, "An invalid Payment or PayPalConfiguration was submitted. Please see the docs.");
            }
        }
    }
}
```

Additional note, payment is working in iOS application, with the same clientId and is tested with the same buyer account.

Thanx in advance.

**Comment by sankarbhavanib** [comment]
@Simonida  :  Can you please confirm that you are trying iOS application on Live ? if yes , can you please provide the debug_id for the successful transaction in iOS application

**Comment by Simonida** [comment]
@sankarbhavanib Yes, iOS application is on Live also. But we are unable to detect debug_id of successful transaction, we can only detect debug_id of unsuccessful ones.
But here is the whole response from successful transaction in iOS:

```
{
   client =     {
       environment = live;
       "paypal_sdk_version" = "2.14.3";
       platform = iOS;
       "product_name" = "PayPal iOS SDK";
   };
   "event_user_id" = 387;
   response =     {
       "create_time" = "2016-07-11T19:57:42Z";
       id = "PAY-1R480049K6729703AK6B7UJY";
       intent = sale;
       state = approved;
   };
   "response_type" = payment;
}
```

**Comment by sankarbhavanib** [comment]
@Simonida We are looking into this issue, will update you soon

**Comment by Simonida** [comment]
@sankarbhavanib We've noticed today that PayPal payment is working on another Android device (Samsung Galaxy S7 edge).
On that device, payment flow looks different, because there is option for user to choose a credit card for payment. When the card is selected, user has to click on Pay button:
http://image.prntscr.com/image/e731df7229ee4fd68c05bf46f7781804.png
http://image.prntscr.com/image/37efec27006a402e89de1c2394204593.png
http://image.prntscr.com/image/a2047e3b7d11452397af44c9e8560c1a.png

In LG G2, that option is not showing (dialog with a list of available credit cards), transaction is initialized automaticaly after login (without clicking on Pay button), and then payment creation error happens.
http://image.prntscr.com/image/0abb25f4da3b470a86faae52f494d3b9.png
http://image.prntscr.com/image/4b8bf4ae0cc347b3b03ea0eea81be506.png
http://image.prntscr.com/image/33948814b44f446c93d6e8d1a2e0c112.png
on cancel click (there is no information about credit card) http://image.prntscr.com/image/7cd864607eca4396804620a36618c658.png

**Comment by sankarbhavanib** [comment]
@Simonida  It seems that particular transaction is blocked by risk rules. Can you please reach out to PayPal Merchant Technical Support team for further clarification on how to reduce the risk

**Comment by fcogutierrez** [comment]
@Simonida how could you fix it? I am getting the same error than you:

07-29 11:34:21.315 E/paypal.sdk(31350): request failure with http statusCode:422,exception:Unprocessable Entity
07-29 11:34:21.315 E/paypal.sdk(31350): request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"fd2957722489d","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

**Comment by hamidrv** [comment]
i have found same issue found below log 

{"name":"PAYMENT_CREATION_ERROR","debug_id":"1c6ed5c258cf6","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

**Comment by zenchu** [comment]
Did you find any solutions?

**Comment by ppmtscory** [comment]
Folks, please create tickets to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team for these errors as 99% of the time they are specific to either the accounts being used or the funding being used.
