### ISSUE TITLE
Invalid scope requested [profile]

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [paypal/PayPal-Android-SDK#310]
### Required Information
- Mode (Mock/Sandbox/Live): Sandbox
- PayPal Android SDK Version: 2.14.4
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...): Android 4.4 Redmi Note
- PayPal-Debug-ID(s) (from any logs): 
### Issue Description

Hello. I have checked `Account Information` and `Personal Information` in my dashboard:

![321312](https://cloud.githubusercontent.com/assets/8684688/17134936/d1c3fa72-534e-11e6-99a4-1aa116fcb38a.PNG)

Then in my android app I add that kind of permissions:

```
private PayPalOAuthScopes getOauthScopes() {
        Set<String> scopes = new HashSet<String>(
                Arrays.asList(PayPalOAuthScopes.PAYPAL_SCOPE_OPENID,
                        PayPalOAuthScopes.PAYPAL_SCOPE_PROFILE) );
        return new PayPalOAuthScopes(scopes);
}
```

Then I launch activity with these lines of code:

```
private void payPalLogin() {
    Intent intent = new Intent(this, PayPalProfileSharingActivity.class);
    intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, payPalConfiguration);
    intent.putExtra(PayPalProfileSharingActivity.EXTRA_REQUESTED_SCOPES, getOauthScopes());
    startActivityForResult(intent, REQUEST_CODE_PROFILE_SHARING);
}
```

It opens PayPal login page. I login with my sandbox account, then it opens User agreement page, when I click agree button it throws me this error:

```
request failure with http statusCode:400,exception:Bad Request
request failed with server response:{"error":"invalid_request","error_description":"Invalid scope requested [profile]"}
invalid_request
```

The interesting thing is that when I ask **only OpenID without profile** it works and gives to me authorization code. Why this is happening?

**Comment by bradXie1992** [comment]
My question is the same as yours, did you solve the problem?

**Comment by pp-randy** [comment]
@bradXie1992 you have the attributes checked for profile https://developer.paypal.com/docs/integration/direct/identity/attributes/?  Double check that the client id and secret belong to your app. 

This is working for me in my testing
```
 private PayPalOAuthScopes getOauthScopes() {
        /* create the set of required scopes
         * Note: see https://developer.paypal.com/docs/integration/direct/identity/attributes/ for mapping between the
         * attributes you select for this app in the PayPal developer portal and the scopes required here.
         */
        Set<String> scopes = new HashSet<String>(
                Arrays.asList(PayPalOAuthScopes.PAYPAL_SCOPE_OPENID, PayPalOAuthScopes.PAYPAL_SCOPE_PROFILE) );
        return new PayPalOAuthScopes(scopes);
    }
```

**Comment by pp-randy** [comment]
@bradXie1992 if you are able to get a PayPal-Debug-Id for the error that would be helpful.

**Comment by bradXie1992** [comment]
Thank you very much, I solved this problem, is to set the problem for my account!
