### ISSUE TITLE
INTERNAL_SERVICE_ERROR when creating PAYMENT_INTENT_SALE

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [paypal/PayPal-Android-SDK#313]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal Android SDK Version: 2.14.4
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...): 4.4 KitKat
- PayPal-Debug-ID(s) (from any logs): 19e91f6e70e5d

### Issue Description
I want to make simple testing payment via this code:

    private void onBuyPressed() {
        PayPalPayment payment = new PayPalPayment(new BigDecimal("20.5"), "USD", "Testing Item 1",
                PayPalPayment.PAYMENT_INTENT_SALE);

        Intent intent = new Intent(this, PaymentActivity.class);

        // send the same configuration for restart resiliency
        intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, payPalConfiguration);

        intent.putExtra(PaymentActivity.EXTRA_PAYMENT, payment);

        startActivityForResult(intent, 0);
    }

It opens PayPal authorization window. I authorize with my sandbox account **it has verified status** and has **Card Status activated**. It logins successfully and I then get error message:

    request failure with http statusCode:500,exception:Internal Server Error
    request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","debug_id":"19e91f6e70e5d","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}
    INTERNAL_SERVICE_ERROR

Why this is happening? I use same PayPal configurations and services for profile sharing.

**Comment by SuperMasterBlasterLaser** [comment]
Created new account and still get this error. Debug id is: a1f88c53b7826

**Comment by pp-randy** [comment]
I'm able to complete a sale currently.  Is this issue still occurring for you?  Reviewing the logs it appears a possible internal system timeout; however, if it is still occurring I will have this further investigated by our product engineers.

**Comment by SuperMasterBlasterLaser** [comment]
@pp-randy The main interesting thing is that Payment completed successfully when I used my real credit card in **sandbox mode**, but failed when I use sandbox accounts.

I will check it again today, because sandbox sometimes failes an sometimes not.

**Comment by SuperMasterBlasterLaser** [comment]
@pp-randy Now today Payments started to work. I don't know why. I think there was something in paypal's side and they fixed it.

**Comment by pp-randy** [comment]
@SuperMasterBlasterLaser you can use Step 4 of the FAQ found here to generate test card numbers https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413
