### ISSUE TITLE
Difference between "state": "approved" for paypal login process and "state": "created" for Credit card process?

### ISSUE THREAD

**Issue by ThameemAK** [paypal/PayPal-Android-SDK#314]
I have integrated Paypal in my android application, user can pay by credit card or paypal account.While doing paypal account payment working fine, am getting response as "status" : "approved" then merchant account credited successfully..

while doing Card Payment, am getting response as "status": "created" instead of "approved". and merchant account not credit the specified amount?

Response while doing the card payment:

"response": {
    "state": "created",
    "id": "PAY-92898807R9269472DK6NSSTA",
    "create_time": "2016-07-29T10:00:44Z",
    "intent": "sale"
    },
    "client": {
    "platform": "Android",
    "paypal_sdk_version": "2.14.4",
    "product_name": "PayPal-Android-SDK",
    "environment": "sandbox"
    },
    "response_type": "payment"
    }

**Comment by ppmtscory** [comment]
@ThameemAK can you give me the sale ID from that transaction?  You can get that from doing a GET call on the PAY-ID.

**Comment by ThameemAK** [comment]
@ppmtscory "id": "PAY-92898807R9269472DK6NSSTA" this ID only i got from server.. 
I tried GET call like this 

https://api.paypal.com/v1/payments/sale/PAY-92898807R9269472DK6NSSTA

Is this correct URL?

**Comment by ppmtscory** [comment]
Yes, you'll get an empty response because you're using the Live URL but the pay ID was generated in the sandbox environment.  You'll need to use https://api.sandbox.paypal.com/v1/payments/sale/PAY-92898807R9269472DK6NSSTA.

**Comment by ThameemAK** [comment]
Finally i got the "state": "approved" and merchant account credit with specified amount in sandbox environment for credit card payment. The problem I created the Business account in my sandbox, but we need to create Business-Pro account in sandbox..

but i have one more, what is the meaning of state "approved"? Is the transaction fully completed?

what i have to do, if i get other than "approved" like(pending, failed)?

**Comment by ThameemAK** [comment]
@ppmtscory I got state "approved" and doing the GET Call using tat id "URL https://api.sandbox.paypal.com/v1/payments/sale/PAY-3RB989350V303120NK6RULGA" Still i get the empty response for this.

Why am getting empty response? 
What is the use of sale ID for that transaction?

**Comment by pp-randy** [comment]
Try this way https://developer.paypal.com/docs/api/payments/#payment_get
https://api.sandbox.paypal.com/v1/payments/payment/PAY-3RB989350V303120NK6RULGA

The sale lookup would use a the transaction id example here the transaciton id is  36C38912MN9658832: https://developer.paypal.com/docs/api/payments/#sale_get

**Comment by ppmtscory** [comment]
@ThameemAK that's my fault, I pasted the wrong URL for the payment lookup.  As for the approved state, approved should mean that it's done, yes, but that's why you always want to do the verify payment step with any payment from the mSDK.  Outlined [here](https://developer.paypal.com/webapps/developer/docs/integration/mobile/verify-mobile-payment/), you'll want to double check that the full response was from PayPal and you weren't spoofed.  Since you're up and running now, I'll close this issue.
