### ISSUE TITLE
PAYMENT_CREATION_ERROR (statusCode:422)

### ISSUE THREAD

**Issue by nasirky** [paypal/PayPal-Android-SDK#316]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal Android SDK Version: 2.14.2
- Android Version and Device: Samsung S4 with Android 5.0.1 
- PayPal-Debug-ID(s) (from any logs):  640e80681315

### Issue Description
> I tried to complete a payment using my sandbox account (which was working fine earlier) but now I am getting the following error (log below)

>> _paypal.sdk: fg SN:16 PayPal Debug-ID: 640e80681315 [sandbox, 2.14.2;release]
paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"640e80681315","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
paypal.sdk: PAYMENT_CREATION_ERROR_

**Comment by jaypatel512** [comment]
Hey @nasirky !

Can you please provide us with a bit more information. What currency are you trying to use for this payment ? Also, which country your account is setup in ?

From the looks of it, you are getting this error only when using unsupported currency. Wanted to be sure.

**Comment by jaypatel512** [comment]
Hey @nasirky !

I was able to reproduce and fix the issue on my end, by enabling `Allow payments sent to me in a currency I do not hold:` section to accept all currency. By Default, it will not accept currencies that you do not hold in your sandbox account. 

to fix this, here are the steps you can take. You can reach out to [PayPal Merchant Technical Support](https://developer.paypal.com/support/) related to this:

1. Login to `sandbox.paypal.com` in Icognito window.
2. Login with your `sandbox account`. Make sure that is the same account used for creating the app whose clientId you are using. 
3. Click on "Business Setup" in left bar.
4. Click on "Profile" on the top menu.
5. Click `My selling tools` -> `Getting paid and managing my risk` -> `Block Payments`.
6. Enable 1st option: `Yes, accept and convert them to U.S. Dollars. Additional charges apply.`.

These steps should solve the issue you are facing. I have attached few images at the bottom to help you navigate if you get lost. Please reach out to MTS for more assistance.

![screen shot 2016-08-02 at 12 31 48 pm](https://cloud.githubusercontent.com/assets/1309895/17338678/fa0f04ea-58ad-11e6-8648-60d81215c5ca.png)
![screen shot 2016-08-02 at 12 33 26 pm](https://cloud.githubusercontent.com/assets/1309895/17338686/fea66ae8-58ad-11e6-9164-7ec48fe956df.png)
![screen shot 2016-08-02 at 12 34 05 pm](https://cloud.githubusercontent.com/assets/1309895/17338691/04ef01e4-58ae-11e6-901f-096a07e77de2.png)
![screen shot 2016-08-02 at 12 34 25 pm](https://cloud.githubusercontent.com/assets/1309895/17338693/08e72204-58ae-11e6-833d-603e473d3431.png)
![screen shot 2016-08-02 at 12 35 19 pm](https://cloud.githubusercontent.com/assets/1309895/17338699/0ccf6408-58ae-11e6-8abe-8b1cedc4c602.png)

**Comment by nasirky** [comment]
Hi Jay,
      Our primary currency is Euros and the transaction was also done in Euros. This was working quite fine 2 weeks ago, but when I check it today, it was not working. I will check if the above steps help me.

**Comment by ppmtscory** [comment]
@nasirky you may have been using a different account before or perhaps closed out your EUR currency.  The account you're using in the above error is a US based account and only has a USD currency in it.  If you'd like, you can login and create a EUR currency so that you hold that currency, but as it stands now it's not available.

**Comment by nasirky** [comment]
@ppmtscory - I am not using it with this account but with company account which is a Euro account.

**Comment by ppmtscory** [comment]
Then you'll need to provide the error response from the EUR account.  The account associated with the error you posted above is a US account, without a EUR currency, and therefore the error.
