### ISSUE TITLE
Reference Key

### ISSUE THREAD

**Issue by koustuv-ganguly** [paypal/PayPal-Android-SDK#317]
How to get any reference key while initiating the simple payment transaction with PayPal Android SDK?

I'm connecting my app with PayPal Android SDK for making a payment.
But if any causes is occurring within the payment or after the payment, we should be able to track the transaction with this reference key.

Note: my application is an enterprise application. 
I'm getting Pay-Key from PayPal Android SDK, after the transaction is done.

**Comment by ppmtscory** [comment]
The Pay-ID is the reference that you should be using to check the status.  If you do a GET call on that payment resource, you should be able to tell it's status, and also this is an integral step in verifying the payment response actually came from PayPal.  Please let me know if I'm missing something here.

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
