### ISSUE TITLE
PAYMENT_CREATION_ERROR with statusCode 422

### ISSUE THREAD

**Issue by anderson631** [paypal/PayPal-Android-SDK#319]
Hello,
I'm having trouble generating payments.

PayPal is set to 'Live' and returns the error message: "There was a problem setting up this payment. Please visit the paypal website to check your account."

Using the "logcat" following error details:

Error: PAYMENT_CREATION_ERROR
statusCode: 422
**debug_id: ae96841541cba**
message: checkout-session not created

**Comment by pp-randy** [comment]
@anderson631 is this happening for every buyer account?

**Comment by anderson631** [comment]
Yes, my account is "verified buyer account"
Print: [https://www.diigo.com/file/image/qseadrdzdcepeedaqzcdrpoerq/Minha+conta+-+PayPal.jpg](url)

**Comment by pp-randy** [comment]
@anderson631 are you able to attempt with a different funding source?  I also suggest you contact PayPal Customer Support as they may be better able to troubleshoot this issue. 

The attempt appears to be a decline; however, the API error response does not seem appropriate.
