### ISSUE TITLE
request failure with http statusCode:422,exception:Unprocessable Entity

### ISSUE THREAD

**Issue by mostefaiadel** [paypal/PayPal-Android-SDK#322]
### Required Information

- Mode (Sandbox):
- PayPal Android SDK Version:
- Android Version and Device (LG G3 ):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
Error: PAYMENT_CREATION_ERROR
statusCode: 422 , exception:Unprocessable Entity
debug_id":"625400e03bb39"
message: checkout-session not created

my code is : 

private static PayPalConfiguration config = new PayPalConfiguration()
            .environment(PayPalConfiguration.ENVIRONMENT_SANDBOX)
            .clientId(PAYPAL_ID)
            .acceptCreditCards(false);

@Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View rootView = (View) inflater.inflate(R.layout.fragment_my_balance, container, false);

some code...

        gson = new GsonBuilder()
                .setDateFormat("yyyy-MM-dd'T'HH:mm:ssZ")
                .create();

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("https://api.sandbox.paypal.com")
                .addConverterFactory(GsonConverterFactory.create(gson))
                .build();

        payPal = retrofit.create(PayPal.class);

        Intent intent = new Intent(getContext(), PayPalService.class);
        intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
        getActivity().startService(intent);

    return rootView;
    }

private void onBuyPressed(View v, PayPalPayment payPalPayment){
        unitaire = new PayPalPayment(new BigDecimal(String.valueOf(myBalance)), getString(R.string.moneyCountry), UNITAIRE, PayPalPayment.PAYMENT_INTENT_SALE);
        Intent intent = new Intent(getActivity(), PaymentActivity.class);
        intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
        intent.putExtra(PaymentActivity.EXTRA_PAYMENT, payPalPayment);
        Log.i("--start Intetnt:-- ", " payment activity start");
        startActivityForResult(intent, RESULT_PAYPAL);
    }

@Override
    public void onActivityResult(final int requestCode, int resultCode, Intent data) {
        Log.i("--result activity:-- ", " payment activity result");
        if (resultCode == Activity.RESULT_OK) {
            Log.i("--result code:-- ", String.valueOf(resultCode));
            final PaymentConfirmation confirm = data.getParcelableExtra(PaymentActivity.EXTRA_RESULT_CONFIRMATION);
            if (confirm != null) {
          
some code 
            }
        } else if (resultCode == Activity.RESULT_CANCELED) {
            Log.i("paymentExample", "The user canceled.");
        } else if (resultCode == PaymentActivity.RESULT_EXTRAS_INVALID) {
            Log.i("paymentExample", "An invalid Payment or PayPalConfiguration was submitted. Please see the docs.");
        }
    }

**Comment by mostefaiadel** [comment]
i have this error only for Android, in ios and web paypal work correctly !

**Comment by pp-randy** [comment]
Are any of the accounts used different between the devices?

**Comment by pp-randy** [comment]
This payment looks like it was in USD and that could be blocked by your preferences on currency. Your other transactions appear to be EUR.  Are you setting the currency in the Android require to EUR?

**Comment by mostefaiadel** [comment]
in the PayPalPayement i set the USD as currency and another time i did it with EUR, but both gave me the same error. but in IOS ans web it work correctly for both currency

**Comment by mostefaiadel** [comment]
and when the currency is EUR sometimes i have a 500 error 

E/paypal.sdk: request failure with http statusCode:500,exception:Internal Server Error

E/paypal.sdk: request failed with server response:{"name":"ADDRESS_ADDITION_ERROR","debug_id":"e374dc332a6ab","message":"{\"name\":\"INTERNAL_SERVICE_ERROR\",\"message\":\"An internal service error has occurred\",\"information_link\":\"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR\",\"debug_id\":\"e374dc332a6ab\"}","information_link":"https://developer.paypal.com/docs/api/#ADDRESS_ADDITION_ERROR"}

ADDRESS_ADDITION_ERROR

**Comment by mostefaiadel** [comment]
when i use EUR as currency , sometimes it's work and sometimes i have 500 and i can't find why !!

**Comment by mostefaiadel** [comment]
finally everything work thank you for your help and your time :) my first problem was the currency and the second one was from the server

**Comment by pp-randy** [comment]
@mostefaiadel thank you for the information.  I can use this to help improve the error messaging.  I have submitted an internal request to get a more descriptive error for this use case. 

Internal Tracking:  PPPLPAYPT-11693
