### ISSUE TITLE
INTERNAL SERVICE ERROR

### ISSUE THREAD

**Issue by antonioreyna** [paypal/PayPal-Android-SDK#323]
hi, we are working on an app and we started getting this.

```
E/paypal.sdk: request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","debug_id":"2d652f066e75a","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}
``` 

it was working fine before.

**Comment by allancth** [comment]
Same here.

E/paypal.sdk: request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","debug_id":"54f2cc82eb985","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}

paypal-android-sdk 2.14.4
Android API level 16

**Comment by billytb** [comment]
Hi There
I same error
It was worked fine before.

**Comment by bradXie1992** [comment]
so same error
{"name":"INTERNAL_SERVICE_ERROR","debug_id":"23777a67c30d4","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}
It was worked fine before
How should I deal with it？

**Comment by antonioreyna** [comment]
We are waiting for paypal staff to say a word, I hope they are aware of the problem so they can fix it soon. Maybe they are doing maintenance .

**Comment by luis1987** [comment]
[ERROR] :  E/paypal.sdk: request failure with http statusCode:500,exception:Internal Server Error
[ERROR] :  E/paypal.sdk: request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","debug_id":"fd1bb2b2787b4","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}
[ERROR] :  E/paypal.sdk:
[ERROR] :  E/paypal.sdk: INTERNAL_SERVICE_ERROR

**Comment by sankarbhavanib** [comment]
Thanks for reporting the issue. Let's use [#440] (https://github.com/paypal/PayPal-iOS-SDK/issues/440) to track this current 500 issue.

If you require specific support, please open a ticket with [Merchant Technical Support](https://www.paypal-techsupport.com) who can directly communicate with you.
