### ISSUE TITLE
?

### ISSUE THREAD

**Issue by 2gTayWash** [paypal/PayPal-Android-SDK#327]
### Required Information

- Mode (Mock/Sandbox/Live):
- PayPal Android SDK Version:
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

**Comment by jaypatel512** [comment]
Irrelevant.
