### ISSUE TITLE
request failure with http statusCode:500,exception:Internal Server Error

### ISSUE THREAD

**Issue by mostefaiadel** [paypal/PayPal-Android-SDK#328]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal Android SDK Version:2.14.4
- Android Version and Device (LG G3, samsung S4):
- PayPal-Debug-ID(s) (from any logs): "debug_id":"74f40b8d49b1"

### Issue Description

i had some issue with USD currency  and when i change to EUR i have this error. And one time i had an ADDRESS_ADDITION_ERROR error 500. 

can anyone help me with ?

**Comment by mostefaiadel** [comment]
sometimes it's work and sometimes i have 500 and i can't find why !!

**Comment by abarionos** [comment]
since today I have the same problem, yesterday all was fine

**Comment by mostefaiadel** [comment]
now it's work for me :)

**Comment by abarionos** [comment]
yes, for me too

Am 11.08.2016 um 14:49 schrieb mostefaiadel:

**Comment by pp-randy** [comment]
The issue was in the sandbox only and should be resolve at this time.

**Comment by rodrigobertet** [comment]
I'm having the same issue now

**Comment by ppmtscory** [comment]
@rodrigobertet this issue has been closed for some time and may have been an issue related to that specific point in time.  Please open a brand new issue with all the details of your example for us to look into.

**Comment by DevNigam** [comment]
Getting same error.
request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","debug_id":"f7201ec130e14","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}

**Comment by pp-randy** [comment]
@DevNigam if the issue is still persisting for you can you please create a new issue.  

Thank you
