### ISSUE TITLE
Directly open Card Entry screen

### ISSUE THREAD

**Issue by varunrramani** [paypal/PayPal-Android-SDK#329]
- Mode (Mock/Sandbox/Live): Mock
- PayPal Android SDK Version: 2.14.4
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...): Samsung Galaxy Note 2 running Android 4.4.2
- PayPal-Debug-ID(s) (from any logs):

I'm running the sample app from the repo.
Following the Documentation from https://github.com/paypal/PayPal-Android-SDK#disabling-cardio-card-scanning We should be directly going to the Manual Card Entry screen when clicked on "Pay With card", but it still opens the camera preview to scan the card. Am I missing something?

Also is there a way to directly open the Card Entry screen without going through the normal procedure of opening PaymentActivity?

**Comment by bluk** [comment]
If you look into your bundled application, do you see any of the excluded libraries in the app?

For your second question, I don't believe that is possible.

**Comment by jaypatel512** [comment]
You might be able to set `CardIOActivity.EXTRA_NO_CAMERA` to true to disable camera scanning.

**Comment by jaypatel512** [comment]
About getting the card.io scanning disabled, you need to make sure where you are setting it in `build.gradle`. Please make sure it is as
```
android {
     packagingOptions { 
          ....
    }
}
```
