### ISSUE TITLE
INVALID_RESOURCE_ID in paypal

### ISSUE THREAD

**Issue by adityasd** [paypal/PayPal-Android-SDK#330]
### Required Information

- Mode (Mock/Sandbox/Live):Sandbox
- PayPal Android SDK Version:2.14.4
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...):Android Motorola G4 6.0
- PayPal-Debug-ID(s) (from any logs):"debug_id": "d934b5a373802"

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

  HttpClient httpclient = new DefaultHttpClient();
        HttpGet httppost = new HttpGet("https://api.sandbox.paypal.com/v1/payments/payment/PAY-XXXXXXXXXXXXXXXX);

        try {

            httppost.addHeader("Content-Type", "application/json");
            httppost.addHeader("Authorization", "Bearer " + accesstokens);

            HttpResponse response = httpclient.execute(httppost);
            String responseContent = EntityUtils.toString(response.getEntity());
            Log.d("Final data", responseContent );

        } catch (ClientProtocolException e) {
// TODO Auto-generated catch block
        } catch (IOException e) {
// TODO Auto-generated catch block
        }

**Comment by bluk** [comment]
It doesn't seem like the payment ID exists or you don't have authorization to view it. If this problem reoccurs, then I would open a ticket with the information here at [PayPal Technical Support](https://www.paypal-techsupport.com), who can help verify that the payment ID is correct.

On a sidenote, in general, you should not have your access token in your Android or mobile client code. It could be stolen. If you want to perform an action like this, it is generally advisable to do this only on a controlled and secure server process.

**Comment by adityasd** [comment]
can you tell why i am not able to display invoice number
 private PayPalPayment getStuffToBuy(String paymentIntent) {
        //--- include an item list, payment amount details
        PayPalItem[] items =
            {
                    new PayPalItem("Order Total", 1, new BigDecimal(gradtotal), "AUD",
                            orderid),

            };
        BigDecimal subtotal = PayPalItem.getItemTotal(items);
       // BigDecimal shipping = new BigDecimal("7.21");
      //  BigDecimal tax = new BigDecimal("4.67");
       // PayPalPaymentDetails paymentDetails = new PayPalPaymentDetails(shipping, subtotal, tax);
        BigDecimal amount = subtotal;
        PayPalPayment payment = new PayPalPayment(amount, "AUD", "Order Total", paymentIntent);

        payment.custom(userids);
        payment.invoiceNumber(orderid);
        //payment.items(items).paymentDetails(paymentDetails);

        //--- set other optional fields like invoice_number, custom field, and soft_descriptor
       // payment.custom("This is text that will be associated with the payment that the app can use.");

        return payment;
    }

..................................
 "transactions": [
        {
            "amount": {
                "total": "88.72",
                "currency": "AUD",
                "details": {
                    "subtotal": "88.72"
                }
            },
            "description": "Order Total",
            "custom": "287947",
            "item_list": {
                "items": [],
                "shipping_address": {
                    "recipient_name": "Kartik Bhadoriya"
                }
            },
.........................................
as you can see custom is displaying

**Comment by jaypatel512** [comment]
Hey @adityasd !

We tried to reproduce this issue but, were able to get the invoice number. 
Here are the steps we took: 

1. Create a Single Payment using Android Sample.
2. Logged in as a sandbox user.
3. Clicked on Pay.
4. On return, we got the response from mobile sdk as:
```
PaymentConfirmation: {
	"client": {
		"environment": "sandbox",
		"paypal_sdk_version": "2.14.4-4-g9405f4b-dirty",
		"platform": "Android",
		"product_name": "PayPal-Android-SDK"
	},
	"response": {
		"create_time": "2016-08-17T17:55:43Z",
		"id": "PAY-7PC7737998332173GK62KKFQ",
		"intent": "sale",
		"state": "approved"
	},
	"response_type": "payment"
}

{
	"amount": "0.01",
	"currency_code": "USD",
	"short_description": "Awesome Sauce",
	"intent": "sale",
	"bn_code": "testBnCode1234"
}
```
5. Used the Payment ID to make a call via Server SDK using the same client ID and secret, and got this.
```
{
    "id": "PAY-7PC7737998332173GK62KKFQ",
    "intent": "sale",
    "state": "approved",
    "cart": "5D4924957T1610022",
    "payer": {
        "payment_method": "paypal",
        "status": "VERIFIED",
        "payer_info": {
            "email": "twhipple-consumer2@paypal.com",
            "first_name": "Tom",
            "last_name": "Whipple",
            "payer_id": "58RGL7BVAV33J",
            "shipping_address": {
                "recipient_name": "Tom Whipple"
            },
            "phone": "4083208137",
            "country_code": "US"
        }
    },
    "transactions": [
        {
            "amount": {
                "total": "0.01",
                "currency": "USD",
                "details": {
                    "subtotal": "0.01"
                }
            },
            "description": "Awesome Sauce",
            "invoice_number": "uniq123e",
            "item_list": {
                "items": [],
                "shipping_address": {
                    "recipient_name": "Tom Whipple"
                }
            },
            "related_resources": [
                {
                    "sale": {
                        "id": "9FJ59079WW8663816",
                        "state": "completed",
                        "amount": {
                            "total": "0.01",
                            "currency": "USD",
                            "details": {
                                "subtotal": "0.01"
                            }
                        },
                        "payment_mode": "INSTANT_TRANSFER",
                        "protection_eligibility": "ELIGIBLE",
                        "protection_eligibility_type": "ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE",
                        "transaction_fee": {
                            "value": "0.01",
                            "currency": "USD"
                        },
                        "parent_payment": "PAY-7PC7737998332173GK62KKFQ",
                        "create_time": "2016-08-17T17:55:42Z",
                        "update_time": "2016-08-17T17:55:42Z",
                        "links": [
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/sale/9FJ59079WW8663816",
                                "rel": "self",
                                "method": "GET"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/sale/9FJ59079WW8663816/refund",
                                "rel": "refund",
                                "method": "POST"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-7PC7737998332173GK62KKFQ",
                                "rel": "parent_payment",
                                "method": "GET"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "create_time": "2016-08-17T17:55:42Z",
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-7PC7737998332173GK62KKFQ",
            "rel": "self",
            "method": "GET"
        }
    ]
}
```

**Comment by caiyunxiu** [comment]
<?php
//https://api.sandbox.paypal.com/v1/payments/payment/1111111111111111111111;
include __DIR__.'/bootstrap.php';
include ROOT . 'api/payment_query/PayPal/bootstrap.php';
include ROOT . 'api/payment_query/PayPal/sdk_config.ini';
include '/data/www/caiyx/public/vendor/autoload.php';

$paymentId = 'E0111154176868774369';

//$paymentId = '71S39254R2455303H';


try {


    //$result = \PayPal\Api\Payment::get($paymentId);
    $result = \PayPal\Api\Order::get($paymentId);
    // NOTE: PLEASE DO NOT USE RESULTPRINTER CLASS IN YOUR ORIGINAL CODE. FOR SAMPLE ONLY
   // ResultPrinter::printResult("Get Order", "Order", $result->getId(), null, $result);

   // $params = array('count' => 10, 'start_index' => 5);
   // $payments = \PayPal\Api\Payment::all($params, $apiContext = null);

} catch (Exception $ex) {
    // NOTE: PLEASE DO NOT USE RESULTPRINTER CLASS IN YOUR ORIGINAL CODE. FOR SAMPLE ONLY
   // ResultPrinter::printError("Get Order", "Order", null, null, $ex);
   var_dump($ex);exit;
    //var_dump($ex->getMessage());exit;
    //exit(1);
}

var_dump($result);


["url":"PayPal\Exception\PayPalConnectionException":private]=>
  string(70) "https://api.sandbox.paypal.com/v1/payments/orders/E0111154176868774369"
  ["data":"PayPal\Exception\PayPalConnectionException":private]=>
  string(203) "{"name":"INVALID_RESOURCE_ID","message":"Requested resource ID was not found.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INVALID_RESOURCE_ID","debug_id":"2eb02ed2ccbd"}"
  ["message":protected]=>
  string(113) "Got Http response code 404 when accessing https://api.sandbox.paypal.com/v1/payments/orders/E0111154176868774369."
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>

**Comment by bluk** [comment]
@caiyunxiu The order ID does not seem to be correct. Usually the order is something like `"O-4LN47720P5875901R`. Please see https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/OrderGet.php for an example. If you are still encountering problems, please open a new issue. Thanks.
