### ISSUE TITLE
Sandbox - INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by adityasd** [paypal/PayPal-Android-SDK#332]
### Required Information

- Mode (Mock/Sandbox/Live):SandBox
- PayPal Android SDK Version:2.14.1
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...): Motorola G4 6.0
- PayPal-Debug-ID(s) (from any logs):"debug_id": "31ac939d29e8d",

I am testing sandbox in my app for my app feature,but i am getting this error 

{
    "name": "INTERNAL_SERVICE_ERROR",
    "debug_id": "31ac939d29e8d",
    "message": "An internal service error has occurred",
    "information_link": "https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"
}

**Comment by pp-randy** [comment]
@adityasd looking over the logs, to me this appears to be related to https://github.com/paypal/PayPal-iOS-SDK/issues/446.  

Internal Tracking: SRE-42473

**Comment by bradXie1992** [comment]
[live, 2.14.4;release]
request failure with http statusCode:500,exception:Internal Server Error
request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"2a064d24f0f"}
INTERNAL_SERVICE_ERROR
I am testing ENVIRONMENT_PRODUCTION in my app ，I use a credit card。but i am getting this error

**Comment by pp-randy** [comment]
@bradXie1992 your issue seems more related to https://github.com/paypal/PayPal-Android-SDK/issues/338.  Can you follow up further in that issue?  I am trying to confirm if the REST Apps with this issue have been enabled for Credit Card processing or not.  


The sandbox issue causing the 500 should be resolved at this point.
