### ISSUE TITLE
SERVER_COMMUNICATION_ERROR

### ISSUE THREAD

**Issue by eolverabea** [paypal/PayPal-Android-SDK#337]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal Android SDK Version:  2.14.4
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...): Virtual Machine
- PayPal-Debug-ID(s) (from any logs):
[ERROR] :  E/paypal.sdk: request failed with server response:Unable to resolve host "api-m.sandbox.paypal.com": No address associated with hostname
[ERROR] :  E/paypal.sdk: SERVER_COMMUNICATION_ERROR

### Issue Description
>
The error is displayed when attempting to connect to the API

**Comment by bluk** [comment]
Can you ping `api-m.sandbox.paypal.com` from your machine and/or try a different network? My guess is that your device's network is either firewalled or misconfigured to not resolve the domain name so requests would fail.

**Comment by jaypatel512** [comment]
Are you able to open any website in your virtual mobile browser. It looks like you do not have a working internet connection in your emulator.

**Comment by eolverabea** [comment]
Thanks, I was solved.
