### ISSUE TITLE
PAYMENT_CREATION_ERROR 

### ISSUE THREAD

**Issue by antonio92cop** [paypal/PayPal-Android-SDK#350]
### Required Information

- Mode Sandbox
- PayPal Android SDK Version: 2.14.4
- Android Version and Device (All !!! ):
- PayPal-Debug-ID(s) (from any logs): {"name":"PAYMENT_CREATION_ERROR","debug_id":"d4e54cdbaeae7","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

### Issue Description
For a month Paypal service work very well. !! Today when click Pay with PayPal send this error.. "There was a problem setting up this payment. Please visit the paypal website to check your account". Why!!??

**Comment by pp-randy** [comment]
Closing as a duplicate of https://github.com/paypal/PayPal-Android-SDK/issues/349
