### ISSUE TITLE
An internal service error has occurred

### ISSUE THREAD

**Issue by nileshinfograins** [paypal/PayPal-Android-SDK#360]
paypal.sdk: request failure with http statusCode:500,exception:Internal Server Error
paypal.sdk: request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","debug_id":"39612e53d6965","message":"An internal service error has occurred", "information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}
paypal.sdk: INTERNAL_SERVICE_ERROR

compile 'com.paypal.sdk:paypal-android-sdk:2.14.5'

getting error on Samsung E7 android 5.1 and An Android virtual device 
Details :-  
Name: Nexus_5X_API_23
CPU/ABI: Google APIs Intel Atom (x86_64)
Target: google_apis [Google APIs] (API level 23)
Skin: 1080x1920
runtime.network.speed: full

my paypal configuration  is :- 

private static final String CONFIG_ENVIRONMENT = PayPalConfiguration.ENVIRONMENT_SANDBOX;
private static final String CONFIG_CLIENT_ID = "CLIENT ID";
private static PayPalConfiguration config = new PayPalConfiguration()
            .environment(CONFIG_ENVIRONMENT)
            .clientId(CONFIG_CLIENT_ID)
            .merchantName("merchant name")
            .merchantPrivacyPolicyUri(Uri.parse("privacy url"))
            .merchantUserAgreementUri(Uri.parse(" terms and condition url "));

**Comment by bluk** [comment]
This appears to be the same issue as #361, so I'll close this as a duplicate since there are more people watching that issue. Thanks for reporting the issue.
