### ISSUE TITLE
 Service extras invalid.

### ISSUE THREAD

**Issue by mohamedamineamdouni** [paypal/PayPal-Android-SDK#362]
hi i am getting the same error all the time 

>  Process: com.amdono.herbanutrition, PID: 15466                                                                            java.lang.RuntimeException: Unable to start service com.paypal.android.sdk.payments.PayPalService@41c36110 with Intent { cmp=com.amdono.herbanutrition/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.RuntimeException: Service extras invalid.  Please check the docs.                                                                                at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2987)                                                                                at android.app.ActivityThread.access$2100(ActivityThread.java:166)                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)                                                                                at android.os.Looper.loop(Looper.java:136)                                                                                at android.app.ActivityThread.main(ActivityThread.java:5584)                                                                                at java.lang.reflect.Method.invokeNative(Native Method)                                                                                at java.lang.reflect.Method.invoke(Method.java:515)                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)                                                                                at dalvik.system.NativeStart.main(Native Method)                                                                             Caused by: java.lang.RuntimeException: Service extras invalid.  Please check the docs.                                                                                at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)                                                                                at com.paypal.android.sdk.payments.PayPalService.onStartCommand(Unknown Source)                                                                                at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2970)                                                                                at android.app.ActivityThread.access$2100(ActivityThread.java:166)                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)                                                                                 at android.os.Looper.loop(Looper.java:136)                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5584)                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)                                                                                 at dalvik.system.NativeStart.main(Native Method) 

config = new PayPalConfiguration()
// Start with mock environment.  When ready, switch to sandbox (ENVIRONMENT_SANDBOX)
// or live (ENVIRONMENT_PRODUCTION)
    .environment(PayPalConfiguration.ENVIRONMENT_SANDBOX)
    .clientId(PayPalConfig.PAYPAL_CLIENT_ID)
    .acceptCreditCards(false)
    .rememberUser(true);

Intent intent = new Intent(this, PayPalService.class);
intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION,config);
startService(intent);

**Comment by pp-randy** [comment]
@mohamedamineamdouni I apologize for the delay.  Are you still experiencing an issue?

**Comment by tabrindle** [comment]
We are also experiencing this issue with the cordova plugin, v3.3.1

**Comment by pp-randy** [comment]
@tabrindle can you file an issue in the [Cordova repository](https://github.com/paypal/PayPal-Cordova-Plugin) and provide any debug logging that you are able to?  

Before you do create an issue, ensure the values are being populated.  Looking over similar issues that seems to be the cause: 
https://github.com/paypal/PayPal-Cordova-Plugin/issues/171 
https://github.com/paypal/PayPal-Cordova-Plugin/issues/72

**Comment by tabrindle** [comment]
Thanks for the quick reply - and thanks for posting the related issues. Most of the time we go directly to the Native SDK issues page to look for similar issues because cordova plugin support is so hit and miss. 

That said, those tickets did help us confirm this was nothing more than an occasionally missing clientID. Totally unrelated to your SDK.

I believe this can be closed.

**Comment by harshtanwar29** [comment]
Caused by: java.lang.RuntimeException: Service extras invalid.  Please check the docs.
        at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)
        at com.paypal.android.sdk.payments.PayPalService.onBind(Unknown Source)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3210)
        at android.app.ActivityThread.-wrap3(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
