### ISSUE TITLE
OnActivityResult called immediately after StartActivityForResult

### ISSUE THREAD

**Issue by lepipele** [paypal/PayPal-Android-SDK#363]
Others have mentioned this issue, namely:

https://github.com/paypal/PayPal-Android-SDK/issues/141
https://github.com/paypal/PayPal-Android-SDK/issues/243

In my case, the problem seems to be the fact that I have singleInstance Activity that launches PayPal SDK as described here:

http://stackoverflow.com/questions/6147884/onactivityresult-is-not-being-called-in-fragment
http://stackoverflow.com/questions/15687322/onactivityresult-being-called-instantly

Weird thing is that Facebook SDK integration that has similar onActivityResult call works without issues. I'll take deeper look and if I find any solution will post here. And you PayPal guys - if you are hosting on github, it would be useful if you left source code of your SDK instead of doing this silly distribution hosting.

**Comment by lepipele** [comment]
Yeah, just confirmed this has to do with singleInstance. I have this in my AndroidManifest.xml:

	<activity
	    android:name=".activities.MainActivity"
	    android:launchMode="singleInstance"
	    android:theme="@style/SplashTheme">
	    /* ... */
	</activity>

If I switch launchMode from singleIsntance to singleTop - that resolves the problem. But obviously I shouldn't be forced into this decision so I can make SDK work. I'll see if there is better workaround. Good news is that this seems to only apply to older (Android 4.x) devices; bad news is that those devices hold significant market share.

**Comment by pp-randy** [comment]
@lepipele thank you for making us aware of the issue I have escalated to the SDK team for further review.

**Comment by lepipele** [comment]
@pp-randy Knowing how fast they are I expect response sometimes next year ;).

For anybody stumbling upon this thread, the workaround I ended up using is having "Launcher" activity in between. So it is MainActivity -> LauncherActivity (that's not singleInstance) -> PayPalActivity. That works. If anybody wants exact code for LauncherActivity - let me know.

**Comment by pp-randy** [comment]
@lepipele I found this on StackOverflow which appears to also explain what happened when using singleInstance http://stackoverflow.com/questions/5118525/onactivityresult-do-not-fire-if-launch-mode-of-activity-is-singleinstance/9052079#9052079

**Comment by lepipele** [comment]
@pp-randy yeah... exactly... which is why this is a bug since whoever designed SDK didn't take into account how things work on Android 4.x

But yeah... remove sdk-bug and close issue... if I depended on you guys for help I would be a sorry dev...
