### ISSUE TITLE
Rejected from Google Play due to unsafe implementation of X509TrustManager

### ISSUE THREAD

**Issue by llcan1120** [paypal/PayPal-Android-SDK#364]
### Required Information
- Mode (Mock/Sandbox/Live):
  Both
- PayPal Android SDK Version:
  2.15.0

``` java
compile('com.paypal.sdk:paypal-android-sdk:2.15.0') {
        exclude group: 'io.card'
}
```
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...):
  All
- PayPal-Debug-ID(s) (from any logs):
### Issue Description

Rejected from Google Play due to unsafe implementation of X509TrustManager. We have tested many times and believe it is origined from this SDK

Out testing tool indicates it is from 
Package: com.paypal.android.sdk.cc
Method: checkServerTrusted

Package: com.paypal.android.sdk.cd
Method: verify

**Comment by jaypatel512** [comment]
Hey @llcan1120 !

We do have a X509TrustManager used for internal testing only. I will go ahead and test it out, and remove them to bypass google's security check. I will keep you updated.

**Comment by llcan1120** [comment]
Thanks!

**Comment by llcan1120** [comment]
@jaypatel512 Hi, is there any update?

**Comment by jaypatel512** [comment]
Hey @llcan1120 ! Sorry for the delay. We have completed the changes internally. We will be releasing the latest version with the fixes very soon.

**Comment by jaypatel512** [comment]
The new version has been released with the fix. Please update and let us know if you face any other issues.

**Comment by llcan1120** [comment]
@jaypatel512 Thx, I confirm that new version can be accepted in Google Play.

**Comment by indie-dev** [comment]
FIX DIDNT WORK. ISSUE STILL EXISTS.

**Comment by pp-randy** [comment]
@indie-dev please create a new issue if you are still encountering a problem, as the original report has been resolved.
