### ISSUE TITLE
PAYMENT_CREATION_ERROR

### ISSUE THREAD

**Issue by qwertyezi** [paypal/PayPal-Android-SDK#368]
### Required Information

- Mode :Live
- PayPal Android SDK Version:2.15.0
- Android Version and Device :XiaoMi  Redmi Note 3 with Android 5.0.2
- PayPal-Debug-ID(s) :4d6f231395437

### Issue Description
request failure with http statusCode:422,exception:Unprocessable Entity
request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"4d6f231395437","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

**Comment by pp-randy** [comment]
@qwertyezi this appears to be a payment related issue and not an issue with the SDK at this time.  
Please reach to PayPal Customer Support here:  https://www.paypal.com/help and they should be able to assist you further.
