### ISSUE TITLE
request failed with server response:stream was reset: INTERNAL_ERROR

### ISSUE THREAD

**Issue by carlos-ballester** [paypal/PayPal-Android-SDK#369]
Getting constantly the same error while integrating PayPal Android SDK: request failed with server response:stream was reset: INTERNAL_ERROR
SERVER_COMMUNICATION_ERROR

- Sandbox mode
- Version PayPal Android SDK 2.15.1
- Android 7.0 running on Google Nexus 5X
- Available logs: 
11-17 19:50:22.424 2282-2282/com.sowi.android W/paypal.sdk: PayPalService created. API:24 PayPalSDK/PayPal-Android-SDK 2.15.1 (Android 7.0; LGE Nexus 5X; )
11-17 19:50:22.723 2282-2867/com.sowi.android E/paypal.sdk: request failed with server response:stream was reset: INTERNAL_ERROR
11-17 19:50:22.723 2282-2282/com.sowi.android E/paypal.sdk: SERVER_COMMUNICATION_ERROR

The error happens sometimes as soon as I launch PayPal service in the activity's onCreate and sometimes once inside the PayPal login flow (sometimes before the login screen, sometimes on the login screen when submitting credentials, sometimes after this screen when accepting the Future Payment agreement)

![paypal_failure](https://cloud.githubusercontent.com/assets/7714696/20399145/30554a78-acf0-11e6-88a9-216caa775e96.png)

**Comment by jaypatel512** [comment]
Hey @carlos-ballester !

We were not able to reproduce the issue. We were having some issues with payments in sandbox last week, and I think you were affected by that. Can you please try again and see if you are getting success now. If not, please re-open the issue. Thanks.

**Comment by anandraj16992** [comment]
Its occurs only sometimes not everytime. So please test it in different devices on different time
