### ISSUE TITLE
System Error Please Try Again Late

### ISSUE THREAD

**Issue by salmanashraf** [paypal/PayPal-Android-SDK#370]
### Required Information

- Mode (Sandbox):
- PayPal Android SDK Version:  PayPalAndroidSDK-2.9.11.jar
- Samsung S7 with Android 6.0
- PayPal-Debug-ID(s) (from any logs):

I am trying to payment with Android sdk and I am seeing this error
"System Error, Please Try Again Later"

Please suggest any solution for this
![screenshot_20161118-171631](https://cloud.githubusercontent.com/assets/2988051/20429945/70daa516-adb3-11e6-941f-07995c2e68bc.png)

**Comment by jaypatel512** [comment]
Hey @salmanashraf !

We were not able to reproduce the issue. We were having some issues with payments in sandbox last week, and I think you were affected by that. Can you please try again and see if you are getting success now. If not, please re-open the issue. Thanks.
