### ISSUE TITLE
INTERNAL SERVICE ERROR STATUS CODE 500

### ISSUE THREAD

**Issue by antonio92cop** [paypal/PayPal-Android-SDK#371]
### Required Information

- Mode (Sandbox):
- PayPal Android SDK Version: 2.14.4
- Android Version and Device (ALL):
- PayPal-Debug-ID(s) (from any logs): {"name":"INTERNAL_SERVICE_ERROR","debug_id":"e25546d031c9d","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}

### Issue Description
> Hello, there is an error when I make payment. When I press the button to pay you show this error INTERNAL_SERVICE_ERROR","debug_id":"e25546d031c9d","message":"An internal service error has occurred". Why?

**Comment by jaypatel512** [comment]
Hey @antonio92cop !

We were not able to reproduce the issue. We were having some issues with payments in sandbox last week, and I think you were affected by that. Can you please try again and see if you are getting success now. If not, please re-open the issue. Thanks.
