### ISSUE TITLE
need proguard rules

### ISSUE THREAD

**Issue by Khoosham** [paypal/PayPal-Android-SDK#373]
app becomes too large when importing the sdk around 15 MB more
can you provide proguard rules to use thanks :)

**Comment by lkorth** [comment]
@Khoosham: the consumer ProGuard file is already included inside of the AAR for this SDK. The large increase in size is a result of card.io `*.so` files included with the SDK. To disable direct credit card payments and card.io, see the [README](https://github.com/paypal/PayPal-Android-SDK#disabling-direct-credit-card-payments)
