### ISSUE TITLE
Payment via Card In Android  App Integration

### ISSUE THREAD

**Issue by akashqss** [paypal/PayPal-Android-SDK#374]
Hello 
I have a PayPal Pro account and try to pay via credit card issue by Indian bank. I am getting below response. I am doing payment in Australian dollar.

E/paypal.sdk: request failure with http statusCode:401,exception:Unauthorized
E/paypal.sdk: request failed with server response:{"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT","debug_id":"7742f9626fe54"}
E/paypal.sdk: UNAUTHORIZED_PAYMENT  

Please suggest me how to resolve this.

**Comment by ppmtscory** [comment]
@akashqss unfortunately the direct credit card option is not available for Australia users at this time.  This SDK runs off of our REST API and the eligibility for direct credit cards can be found [here](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/#direct-credit-card-payments).
