### ISSUE TITLE
When I pay, pop-up dialog

### ISSUE THREAD

**Issue by chinahyong** [paypal/PayPal-Android-SDK#379]
### Required Information

- Mode (Mock/Sandbox/Live): Live
- PayPal Android SDK Version:2.15.1
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...):OPPO R9 with Android 5.1,Le X528 with Android 6.0.1
- PayPal-Debug-ID(s) (from any logs):
Pop-up dialog: 
        titile:We'r sorry
        content:This device connot communicate with PayPal because this version of Android is too old. Please upgrade Android or try a newer device.

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

**Comment by xiaoleih41** [comment]
As it's a live issue. If you are still experiencing this issue, please contact https://www.paypal-techsupport.com/app/ask.
