### ISSUE TITLE
Invalid User

### ISSUE THREAD

**Issue by Kaushik1502** [paypal/PayPal-Android-SDK#380]
`SandBox` payment is not working

> 
> E/paypal.sdk: request failure with http statusCode:401,exception:Unauthorized
> E/paypal.sdk: request failed with server response:{"error":"invalid_user","error_description":"Invalid user credentials"}
> E/paypal.sdk: invalid_user
> 

Getting these response while trying to login. I have also tried after changing the password and also tried creating new buyer account.

```
private static final String CONFIG_ENVIRONMENT = PayPalConfiguration.ENVIRONMENT_SANDBOX;
private static final String CONFIG_CLIENT_ID = "my_client_id_for_sandbox";
private static final int REQUEST_CODE_PAYMENT = 1;
private static PayPalConfiguration config = new PayPalConfiguration()
            .environment(CONFIG_ENVIRONMENT)
            .clientId(CONFIG_CLIENT_ID).merchantName("Test");

//Inside onCreate
Intent intent = new Intent(this, PayPalService.class);
intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
startService(intent);

//In button click
PayPalPayment thingToBuy = getThingToBuy(PayPalPayment.PAYMENT_INTENT_SALE);
Intent intent = new Intent(this, PaymentActivity.class);
intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
intent.putExtra(PaymentActivity.EXTRA_PAYMENT, thingToBuy);
startActivityForResult(intent, REQUEST_CODE_PAYMENT);

private PayPalPayment getThingToBuy(String paymentIntent) {
return new PayPalPayment(new BigDecimal("0.1"), "USD", "buy",
                paymentIntent);
}

//OnActivityResult
if (requestCode == REQUEST_CODE_PAYMENT) {
            if (resultCode == Activity.RESULT_OK) {
                PaymentConfirmation confirm =
                        data.getParcelableExtra(PaymentActivity.EXTRA_RESULT_CONFIRMATION);
                if (confirm != null) {
                    try {
                        Log.i(TAG, confirm.toJSONObject().toString(4));
                        Log.i(TAG, confirm.getPayment().toJSONObject().toString(4));
                        /**
                         *   send 'confirm' (and possibly confirm.getPayment() to your server for verification
                         * or consent completion.
                         * See https://developer.paypal.com/webapps/developer/docs/integration/mobile/verify-mobile-payment/
                         * for more details.
                         *
                         * For sample mobile backend interactions, see
                         * https://github.com/paypal/rest-api-sdk-python/tree/master/samples/mobile_backend
                         */
                        /*Toast.makeText(
                                getApplicationContext(),
                                "You have donated successfully", Toast.LENGTH_LONG)
                                .show();*/

                    } catch (JSONException e) {
                        Log.e(TAG, "an extremely unlikely failure occurred: ", e);
                    }
                }
            } else if (resultCode == Activity.RESULT_CANCELED) {
                Log.i(TAG, "The user canceled.");
            } else if (resultCode == PaymentActivity.RESULT_EXTRAS_INVALID) {
                Log.i(
                        TAG,
                        "An invalid Payment or PayPalConfiguration was submitted. Please see the docs.");
            }
        }

```

Gradle dependency
```
compile('com.paypal.sdk:paypal-android-sdk:2.15.1') {
    exclude group: 'io.card'
 }
```

**Comment by pp-randy** [comment]
Sorry for the delay in follow up.  Are you still seeing this issue?

**Comment by Kaushik1502** [comment]
I have tested that 2 weeks earlier. Production mode is working fine but sandbox mode is not working

**Comment by pp-randy** [comment]
Are you using your sandbox client id and secret or are you using your production values in sandbox?  You have two different sets.

**Comment by pp-randy** [comment]
Also if you have a PayPal-Debug-ID from the error, I would be happy to look into it further to see if I can get more details.

**Comment by pp-randy** [comment]
Closing the issue due to lack of response.

**Comment by aijaz070110** [comment]
I am using PayPalConfiguration.ENVIRONMENT_PRODUCTION, and the correct credentials.
I can login with sandbox mode but not in production mode.

paypal.sdk: request failure with http statusCode:401,exception:Unauthorized
/paypal.sdk: request failed with server response:{"error":"invalid_user","error_description":"Invalid user credentials"}


while all the credentials and environment variables are ok.

**Comment by pp-randy** [comment]
@aijaz070110 please ensure you are using the client id and secret from the Live tab of your REST Application, it defaults to sandbox and the credentials are not the same.

**Comment by aijaz070110** [comment]
Yes, I know that. I am using live credentials..

**Comment by pp-randy** [comment]
Can you provide a debug id?

**Comment by aijaz070110** [comment]
debug id>> where from I will get that?

**Comment by pp-randy** [comment]
Is this happening when the buyer is logging in or during the API call?  

If this is during the API call then are you able to plug the phone in and use logcat?

**Comment by pp-randy** [comment]
The debug_id should be in the response headers, or in the response JSON for an error.

**Comment by aijaz070110** [comment]
No there is not any

On Jul 21, 2017 7:34 PM, "Randy" <notifications@github.com> wrote:

The debug_id should be in the response headers, or in the response JSON for
an error.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/paypal/PayPal-Android-SDK/issues/380#issuecomment-317017649>,
or mute the thread

**Comment by pp-randy** [comment]
Is this happening when the buyer is logging in or during the API call?

**Comment by aijaz070110** [comment]
Its when buyer is logging in

**Comment by pp-randy** [comment]
Outside of double checking the buyer credentials or suggesting testing with another account there is not much I can do at this point.  If you can confirm the same credentials can be used to log into https://www.paypal.com then I suggest contacting PayPal Technical Support here: https://www.paypal-techsupport.com/app/ask.

**Comment by aijaz070110** [comment]
brother, I am able to login on website with the credentials.
I can login using sandbox credentials
but, when I change it to production mode with merchant id and also the keys , I get that error :(

**Comment by pp-randy** [comment]
Make sure the account isn't the same as the receiver is my last idea, but I think that throws a different error.  Regardless get with Technical Support they should be able to help.

**Comment by aijaz070110** [comment]
Sandbox Info
//   public static final String PAYPAL_SENDBOX_ACCOUNT= "amahmud.qa-facilitator@gmail.com";
//   public static final String PAYPAL_CLIENT_ID= "AdJjNbEMYcnlucuR5feHHoqcsGk6A-fCzQ593oB6-j4BzrYBJeTQKT5RaKa0-MdUf3eVMTcIZ2ax3uPZ";
//   public static final String PAYPAL_CLIENT_SECRET ="EOc8B32AAbFTXdjoC4XVRgxa_unGh28VIJxzQfx2S6oY4rNgpYiLZ_rHlnLaDIfdITP5jkhoUnHG0CrD";

//   Live Info

    public static final String PAYPAL_SENDBOX_ACCOUNT= "manazat.contact@gmail.com";
    public static final String PAYPAL_CLIENT_ID= "AfJRhXJ26IIA_A19o08uZ3_PfrHXT1rwlutY9GLWZFYflqGG2abQ8cbtJVhbTaKDrIMXOeuCc9MsJYc7";
    public static final String PAYPAL_CLIENT_SECRET ="ENkjtfJFPus9dBUu-MQ3u07x3qaYI1jm2C6CCwq5EyTuTbVWCaK3fFFzqWVtlAxJJWp25Z2052sKvUXh";

**Comment by aijaz070110** [comment]
please send then I will delste this

**Comment by pp-randy** [comment]
Talk to Technical Support and change your REST Credentials Immediately there are others on this thread.

**Comment by aijaz070110** [comment]
are you from paypal team?

**Comment by pp-randy** [comment]
Yes, I work at PayPal.  I help with sandbox integration issues here on GitHub. However,  I do not have access to troubleshoot the production issue you are facing.  You will need to contact Technical Support here:  https://www.paypal-techsupport.com/app/ask/.

**Comment by aijaz070110** [comment]
hmm thanks
