### ISSUE TITLE
: request failure with http statusCode:422,exception:Unprocessable Entity 01-19 06:38:17.969 29515-27549/com.shatika E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"8e8634c2a7703","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"} 01-19 06:38:17.970 29515-29515/com.shatika E/paypal.sdk: PAYMENT_CREATION_ERROR

### ISSUE THREAD

**Issue by Darshit2790** [paypal/PayPal-Android-SDK#381]
### Required Information

- Mode (Mock/Sandbox/Live):
- PayPal Android SDK Version:
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

**Comment by Darshit2790** [comment]
01-19 06:38:17.969 29515-27549/com.shatika W/paypal.sdk: fd SN:27 PayPal Debug-ID: 8e8634c2a7703 [live, 2.15.1;release]
01-19 06:38:17.969 29515-27549/com.shatika E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
01-19 06:38:17.969 29515-27549/com.shatika E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"8e8634c2a7703","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
01-19 06:38:17.970 29515-29515/com.shatika E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by bluk** [comment]
@Darshit2790 Since this is a live service issue, please contact [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask). You may also want to detail the frequency of the error, and if you get the same error with a different buyer account.
