### ISSUE TITLE
Back Button ?? HELP. 

### ISSUE THREAD

**Issue by damianos123** [paypal/PayPal-Android-SDK#382]
We have problem and question.

We need BACK BUTTON in this aplication or AUTO BACK in 15minutes.

We want to use this app in built version tablet of the application (the kiosk mode).

If user will not pay and leave this, will be for ever :|

**Comment by pp-randy** [comment]
I discussed this with an SDK engineer; unfortunately, the feature it not something we would build in the SDK. 

However, you may be able to accomplish using some accessibility code to check the screen the user is on and press the back button after a timeout.
