### ISSUE TITLE
Paypal SDK test card issue

### ISSUE THREAD

**Issue by chakradhar451** [paypal/PayPal-Android-SDK#387]
Hello team,
I am getting following error while testing my sandbox account with the below credentials; 

Card n0 - 4311195535619237
mmdd - 01/22
CVV - 123

Not only this card any other cards you have mentioned in your site as test cards are producing the same error. Please help me with the issue.

request failed with server response:{"name":"DUPLICATE_REQUEST_ID","message":"PayPal-Request-Id header was already used.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#DUPLICATE_REQUEST_ID","debug_id":"7867932868d99"}

**Comment by pp-randy** [comment]
The card numbers are probably for our Payflow Gateway product.  Try using the Generate Card number button at the bottom of this FAQ https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413 and let me know if the problem persists.  

We are tracking the issue with common card numbers here: https://github.com/paypal/PayPal-REST-API-issues/issues/22

But please let me know if a new generated card works for you or not.
