### ISSUE TITLE
Sandbox, credit card payment, unknown_error

### ISSUE THREAD

**Issue by gbtt** [paypal/PayPal-Android-SDK#389]
Hi,
I am testing the payment system with credit card.
I am in the sandbox environment and am using the credit card generator ( https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413 ), but when I click on the button to pay I get a generic system error alert.
In the debug console, I see:

```
W/paypal.sdk: fd SN:30 PayPal Debug-ID: c6214803384df [sandbox, 2.15.3;release]
E/paypal.sdk: request failure with http statusCode:400,exception:Bad Request
E/paypal.sdk: request failed with server response:{"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"c6214803384df"}
E/paypal.sdk: UNKNOWN_ERROR
```

**Comment by niteshsirohi1** [comment]
I am also getting the same error
 E/paypal.sdk: request failure with http statusCode:400,exception:Bad Request
 E/paypal.sdk: request failed with server response:{"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"9b341a44799f8"}
 E/paypal.sdk: UNKNOWN_ERROR

**Comment by pp-randy** [comment]
Is this still an on-going issue?  I apologize for the delay, if I could get a newer paypal debug id that would be helpful.

**Comment by pp-randy** [comment]
Closing due to lack of response.

**Comment by GouseBaig** [comment]
4ad27ba8de103
This is the newer paypal debug id

**Comment by pp-randy** [comment]
@GouseBaig is this happening different generated credit cards as well?  The example looks like a temporary system to me and this time since nothing is standing out currently in your API request.

**Comment by pp-randy** [comment]
You should considering include a fake last name and fake cvv2 as well, since without those on live you would most likely get declines.

**Comment by jid001** [comment]
@pp-randy I am also getting the same error while making payment from debit or credit card from any region or bank. 
E/paypal.sdk: request failure with http statusCode:400,exception:Bad Request
E/paypal.sdk: request failed with server response:{"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"4273a758dad2a"}
E/paypal.sdk: UNKNOWN_ERROR

**Comment by xiaoleih41** [comment]
@jid001 It looks like you didn't enter a valid complete billing address.  I
