### ISSUE TITLE
Alert Box -Android Device is too Old on Low Networks Connectivity

### ISSUE THREAD

**Issue by gotoark** [paypal/PayPal-Android-SDK#390]
SDK : paypal-android-sdk:2.15.3    
* Environment: Both Production and SandBox
Android Version:  Marshmallow 6.0.1(API 23) 
Test Device : Xiomi Redmi 3s Prime(with MIUI 8)

### Issue description
While testing the Sandbox and Production getting An Alert Box with the Following Text
**LoginFailed**
> _This Device Cannot Communicate with PayPal. because, this version of Android isToo Old.Please Upgrade Android or try new Device_
This is not Occurs Frequently.Only when the Network Connection was too low.
Log:
 **E/paypal.sdk: request failed with server response:unexpected end of stream on Connection{api-m.paypal.com:443, proxy=DIRECT@ hostAddress=api-m.paypal.com/23.74.230.74:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
E/paypal.sdk: SERVER_COMMUNICATION_ERROR**
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@caa0afd
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@6df3f2
**E/paypal.sdk: request failed with server response:Connection closed by peer
E/paypal.sdk: DEVICE_OS_TOO_OLD**
![screenshot_2017-03-16](https://cloud.githubusercontent.com/assets/13600105/23981624/f2b832ac-0a2d-11e7-8016-4472a4f579ac.png)

**Comment by pp-randy** [comment]
Are you seeing this error with only the `Xiomi Redmi 3s Prime` device or with other devices as well?

**Comment by gotoark** [comment]
I haven't Tested this on Other Devices....!!!

**Comment by pp-randy** [comment]
I apologize I lost the context of low network.  I was down the rabbit hole of this being an OS issue... Sorry again for that.

**Comment by gotoark** [comment]
Thanks for Your Response.Hope You will do it. Keep Rocking..!!!

**Comment by jaypatel512** [comment]
Looking further into source code, we realized that we throw this error in case of any `SSLException`, which primarily includes a non TLS connection. However, there is no way for us to differentiate between non-TLS and a low network connection failure.
