### ISSUE TITLE
request failure with http statusCode:422,exception:Unprocessable Entity checkout-session not created

### ISSUE THREAD

**Issue by carlos-ballester** [paypal/PayPal-Android-SDK#391]
### General information

* SDK/Library version: AndroidSDK / v2.15.3 release
* Environment: Sandbox
* `PayPal-Debug-ID` values: 2475320260bc0
* Android Version and Device: Nexus5X with Android 7.1.1

### Issue description

Since this morning (16.03.2017) Paypal payments in Sandbox do not work anymore. Every time I try to do a payment to test our app functionality, I get the same error:

```
W/paypal.sdk: fc SN:10 PayPal Debug-ID: 2475320260bc0 [sandbox, 2.15.3;release]

03-16 12:56:28.529 E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity

03-16 12:56:28.530 E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"2475320260bc0","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

03-16 12:56:28.538 E/paypal.sdk: PAYMENT_CREATION_ERROR
```

Is it a problem with the Sandbox servers, or something else? And if something else, any other info I should provide or anything that should be done to solve it?

Thanks in advance.

**Comment by pp-randy** [comment]
@carlos-ballester I apologize for the delay. Would you be able to get me a new debug-id if you are still having this issue?

**Comment by pp-randy** [comment]
Closing the issue to do lack of response.  Please let me know if further assistance is needed.

**Comment by sagarikadas91** [comment]
i am facing problem in pay pal android sdk. Every time I am getting the same issue. Please its urgent. Help me.
11-10 15:05:49.827 30851-8987/example.paypal.paymentsample W/paypal.sdk: fc SN:26 PayPal Debug-ID: 1bf5738f5f74 [sandbox, 2.15.3;release]
11-10 15:05:49.828 30851-8987/example.paypal.paymentsample E/paypal.sdk: request failure with http statusCode:422,exception:
11-10 15:05:49.828 30851-8987/example.paypal.paymentsample E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"1bf5738f5f74","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
11-10 15:05:49.829 30851-30851/example.paypal.paymentsample E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by pp-randy** [comment]
@sagarikadas91 This looks like it could be sender and receiver country limitation I am not familiar with.  Have you discussed with PayPal Business Support?  https://www.paypal.com/in/webapps/mpp/merchant. 

If you need to discuss the integration further, please file a new issue I see updates on other issues and would prefer to work with you directly in a single issue here.

**Comment by pp-randy** [comment]
I have locked this thread, if you encounter this error please file a new issue for troubleshooting.
