### ISSUE TITLE
Error Internal Server Error

### ISSUE THREAD

**Issue by kamonth** [paypal/PayPal-Android-SDK#392]
I found this error  how to solve

03-17 14:19:01.214 13675-14077/....../paypal.sdk: request failure with http statusCode:500,exception:Internal Server Error
03-17 14:19:01.214 13675-14077/.......E/paypal.sdk: request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","debug_id":"5160e8c80aa4","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR"}
03-17 14:19:01.226 13675-14077/..... E/CellLocation: create GsmCellLocation

**Comment by pp-randy** [comment]
I apologize for the delay. Are you still seeing this error?  If you are can you provide a new debug_id.

**Comment by kamonth** [comment]
Thanks , I solved this problem (my mistake) I forgot method onDestroy.

2017-03-30 4:34 GMT+07:00 Randy <notifications@github.com>:

**Comment by pp-randy** [comment]
Thank you for providing your resolution.
