### ISSUE TITLE
Sandbox Mode -  Amount Limit

### ISSUE THREAD

**Issue by DevNigam** [paypal/PayPal-Android-SDK#393]
### General information

* SDK/Library version: 2.15.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: f7201ec130e14
* Android Version and Device: Android 4.4

### Issue description

I tried to bill an amount of **$5000.0**, for which I got error. After some expermient, I tried with **$50.0** and the issue is gone. So, is there any **Amount Limit** for the Sandbox Mode.

**Comment by bluk** [comment]
Please contact [PayPal Tech Support](https://developer.paypal.com/support/) to check if your sandbox account has a restriction on it. If you intend to also charge this same amount in production, I would also ask PayPal Support to ensure that your production merchant account is not restricted.
