### ISSUE TITLE
request failure with http statusCode:422,exception:Unprocessable Entity

### ISSUE THREAD

**Issue by Mehul-Gajjar** [paypal/PayPal-Android-SDK#394]
### General information

* SDK/Library version: using 'com.paypal.sdk:paypal-android-sdk:2.15.1' gradle
* Environment: issue in sandbox
* `PayPal-Debug-ID` values: e3355f955c16c
* Android Version and Device: Motorola Moto E 5.1

### Issue description

Today when click Pay with PayPal send this error.. before it was working well
debug_id = e3355f955c16c

request failure with http statusCode:422,exception:Unprocessable Entity
E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"e3355f955c16c","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
E/paypal.sdk: PAYMENT_CREATION_ERROR

Thank you.

**Comment by pp-randy** [comment]
@Mehul-Gajjar I apologize for the delay.  Could you get me a new debug_id value?

**Comment by Mehul-Gajjar** [comment]
Thanx @pp-randy now it is working fine without any code changes don't know why but is is working

**Comment by MukeshGreenDeveloper** [comment]
I have the same issue could u Help

E/paypal.sdk: request failure with http statusCode:422,exception:

{"name":"PAYMENT_CREATION_ERROR","debug_id":"8d9ee12d1d37","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
#ASAP
#PAYMENT_CREATION_ERROR

Integration: Android
Demo app Source : https://github.com/probelalkhan/android-paypal-integration-example


![device-2018-09-14-222531](https://user-images.githubusercontent.com/20937076/45564145-2ebec380-b86d-11e8-87f4-ea6a91f0742c.png)
