### ISSUE TITLE
 request failure with http statusCode:422,exception:Unprocessable Entity

### ISSUE THREAD

**Issue by PankajSavaliyaGit** [paypal/PayPal-Android-SDK#398]
### Issue description
My application working fine in sandbox version but when the application goes to live something getting error

request failed with server response:{“name”:“PAYMENT_CREATION_ERROR”,“debug_id”:“418d99d61c0f3",“message”:“checkout-session not created”,“information_link”:“https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR“}
paypal.sdk: PAYMENT_CREATION_ERROR

### debug_id:418d99d61c0f3

so my problem is when application in live mode.

**Comment by pp-randy** [comment]
Is this happening for every payment attempt?

**Comment by PankajSavaliyaGit** [comment]
I'm testing with different buyer account but same error getting look like as above. I have tired with this error. How can i solve? Need to solve this error in live mode @pp-randy

**Comment by pp-randy** [comment]
Please submit an issue to PayPal Technical Support here: https://www.paypal-techsupport.com/app/ask/
PayPal Technical Support will be better able to assist you with this production issue.

**Comment by PankajSavaliyaGit** [comment]
I have also created tick but doesn't any response from paypal. So why you have close this issue @pp-randy

**Comment by pp-randy** [comment]
Production issues that are not specifically related to to the SDK and need more urgent assistance are best handled by PayPal Technical Support.
