### ISSUE TITLE
Getting null PayPal Debug ID in Sandbox API Call History

### ISSUE THREAD

**Issue by parthitechnotion** [paypal/PayPal-Android-SDK#399]
### Getting null PayPal Debug ID in Sandbox API Call History

* i am doing payment from my android app
* i am testing but i didnt get debugid in my Sandbox API Call History

![image](https://cloud.githubusercontent.com/assets/23714792/25616352/b086d1f8-2f59-11e7-8d4b-268dceb550fb.png)

**Comment by pp-randy** [comment]
Thank you for reporting the issue.  I have moved this issue to https://github.com/paypal/PayPal-REST-API-issues/issues/71.  Please follow here for further tracking.

**Comment by pp-randy** [comment]
This should be resolved.
