### ISSUE TITLE
Why I am getting : Payments to this merchant are not allowed (invalid client id)?

### ISSUE THREAD

**Issue by stoichoandreev** [paypal/PayPal-Android-SDK#400]
Hi guys, 
I am getting in troubles to start using the Android SDK. My problem is that I am getting " Payments to this merchant are not allowed (invalid client id)" no matter if I use Production or SandBox environment. I saw there are similar issues in GutHub and StackOverflow but nothing works in my case.  This is my base PayPal configuration.
`
private static final String CONFIG_ENVIRONMENT = PayPalConfiguration.ENVIRONMENT_PRODUCTION;

private static final String LIVE_CONFIG_CLIENT_ID = "access_token$production$alotofcharactershere";

private PayPalConfiguration config = new PayPalConfiguration()
            .environment(CONFIG_ENVIRONMENT)
            .clientId(LIVE_CONFIG_CLIENT_ID);`

And this is how I am starting your base PaymentActivity
`
Intent intent = new Intent(this, PaymentActivity.class);

intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);

intent.putExtra(PaymentActivity.EXTRA_PAYMENT, thingToBuy);

startActivityForResult(intent, REQUEST_CODE_PAYMENT);`

I have tried the two environments (Production and Sandbox) with the corresponding CONFIG_CLIENT_IDs, but all the time I am getting the same dialog like a result. I saw in my console logs also those messages, which probably is because of the issue:
`
request failure with http statusCode:401,exception:Unauthorized
E/paypal.sdk: request failed with server response:{"error":"invalid_client","error_description":"Client Authentication failed"}
E/paypal.sdk: invalid_client`

BTW : I am testing on Genymotion and device without working Google play services - not sure if this could help for the issue.

**Comment by xiaoleih41** [comment]
Please provide a recent sandbox debug ID for us to better understand your issue.

**Comment by stoichoandreev** [comment]
this is my token for sandbox environment : access_token$sandbox$cj2rz8nfc874g566$b47902870f2e8b6461b3a241e5f3b560

**Comment by pp-randy** [comment]
I apologize for the confusion, the token you provided is for the Braintree SDK.  

Below where your Braintree SDK access token is you will see a Create a REST API app section https://developer.paypal.com/developer/applications/
![image](https://cloud.githubusercontent.com/assets/6819909/25749569/9cea391a-3174-11e7-925e-e4034ec86738.png)

This will have the Sandbox and Live client ids. The below image is Sandbox indicated by the blue sandbox tab.  
![image](https://cloud.githubusercontent.com/assets/6819909/25749667/f2cef280-3174-11e7-9241-43e0a5b442bf.png)

**Comment by xiaoleih41** [comment]
When you make your API call in sandbox, you should get API response.  please look for Debug_Id in the header of the API response.

**Comment by pp-randy** [comment]
Closing the issue since the above comment should resolve this for you.  Please let us know if you have further questions.

**Comment by stoichoandreev** [comment]
Yes the issue could be closed because you guys just help me to understand the mistake. I have been playing with Braintree ids not with paypal ids, which is the confusing thing for me personally. I think Braintree and PayPal need to be separated somehow , to be more visible where you are at the moment, because the PayPal url leed me to https://developer.paypal.com/developer which is mix between Braintree and PayPal dashboard. 
Thanks you guys for your help and support!

**Comment by pp-randy** [comment]
Good call out, I will follow up.

**Comment by pp-randy** [comment]
I have created a new issue in our centralized track repository for further follow up https://github.com/paypal/PayPal-REST-API-issues/issues/75.

**Comment by Shourabhshrama** [comment]
I am facing same issue my android studio logcat says - E/paypal.sdk: request failure with http statusCode:401,exception:
    request failed with server response:{"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"c8e5f81811fd"}
11-23 03:59:41.611 19687-19687/com.exbizcard.qss E/paypal.sdk: UNAUTHORIZED_PAYMENT

It is working with sandbox client id but when I switch to live client id it is not allowing me to do payment

**Comment by Shourabhshrama** [comment]
My PayPal Debug-ID: c8e5f81811fd
