### ISSUE TITLE
READ_PHONE_STATE  Payment failure

### ISSUE THREAD

**Issue by fanxl91** [paypal/PayPal-Android-SDK#405]
### General information

* SDK/Library version: 2.15.3
* Environment: Production
* `PayPal-Debug-ID` values: 55ecf837a55c8
* Android Version and Device: Android 5.0

### Issue description
Hello everyone, 
In my project, I downloaded your SDK and worked properly. But after I added the ‘android.permission.READ_PHONE_STATE’ permissions, the payment failed and the following error was thrown:

05-19 19:54:17.668 2613-9620/com.promethean.market E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
05-19 19:54:17.668 2613-9620/com.promethean.market E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"55ecf837a55c8","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
05-19 19:54:17.694 2613-2613/com.promethean.market E/paypal.sdk: PAYMENT_CREATION_ERROR

Thank you.

**Comment by pp-randy** [comment]
This does not appear to be an SDK issue from what I can determine, and to me looks more like a payment issue.  

Please reach out to PayPal Technical Support for assistance https://www.paypal-techsupport.com/app/ask since this is impacting your production integration.
