### ISSUE TITLE
The vendor cannot receive payments at this time.

### ISSUE THREAD

**Issue by shashank26ashu** [paypal/PayPal-Android-SDK#406]
### General information

* SDK/Library version: 2.15.3
* Environment: Production
* `PayPal-Debug-ID` values: 
* Android Version and Device: RedMi 4 Android 6.0. 

### Issue description

Showing this dialog every time when I pay for something in my app. (The vendor cannot receive payments at this time.)
Attaching Screenshot.
![whatsapp image 2017-05-26 at 1 33 30 pm](https://cloud.githubusercontent.com/assets/8605096/26493461/58e63fce-4237-11e7-8e5f-a5e30c31c0ff.jpeg)

**Comment by xiaoleih41** [comment]
This will be something with the receiver's PayPal account. Is this in sandbox environment or live environment? Do you have a `debug_Id` for this transaction?

**Comment by shashank26ashu** [comment]
This is live environment. In the sandbox environment everything seems to work fine.

**Comment by xiaoleih41** [comment]
Close this issue as the issue appears to be identified and solved.
