### ISSUE TITLE
PayPal Transaction using AndroidSDK are still happening even after deleting the app from PayPal Console. 

### ISSUE THREAD

**Issue by pingothedoer** [paypal/PayPal-Android-SDK#410]
### General information

* SDK/Library version: 2.14.2
* Environment: SandBox
* `PayPal-Debug-ID` values: 
* Android Version and Device: 

### Issue description

I have deleted the app from PayPal Console, but still I can make a transaction from my android application.

**Comment by xiaoleih41** [comment]
Please double check if your Android SDK is using the same App credentials that the app you have deleted. As this is not a SDK specific question, you may want to file a [PayPal tech support ticket](https://www.paypal-techsupport.com/) if the issue persists.

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
