### ISSUE TITLE
about Specify Desired Information for Sharing problems.

### ISSUE THREAD

**Issue by bradXie1992** [paypal/PayPal-Android-SDK#411]
![default](https://user-images.githubusercontent.com/20900353/27369684-aa187516-568b-11e7-9fcb-cd05a544f5ce.png)
![default](https://user-images.githubusercontent.com/20900353/27369800-31bf7172-568c-11e7-886b-121d466226f6.png)
![default](https://user-images.githubusercontent.com/20900353/27369828-4bde4056-568c-11e7-8c34-7a57be96593e.png)
![default](https://user-images.githubusercontent.com/20900353/27369866-739aaab2-568c-11e7-9cf0-5fc85b5d1cfa.png).

This is a screenshot of the data I returned when I logged in to SDK. This data is clearly different from the data on the document, missing names and other information. What should I do?

**Comment by xiaoleih41** [comment]
What are the `scopes` you have passed to PayPal.  Do you have the API call minus the password?

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit when you have further questions.
