### ISSUE TITLE
About paypal-android-sdk:2.15.3

### ISSUE THREAD

**Issue by zzgzzzx** [paypal/PayPal-Android-SDK#412]
### General information

* SDK/Library version: 2.15.3
* Environment: Production
* `PayPal-Debug-ID` values: abfb6fd829f31
* Android Version and Device:All devices

### Issue description

06-22 09:53:35.389 6283-6321/com.paypal.example.paypalandroidsdkexample.debug E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
06-22 09:53:35.399 6283-6321/com.paypal.example.paypalandroidsdkexample.debug E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"abfb6fd829f31","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
06-22 09:53:35.399 6283-6283/com.paypal.example.paypalandroidsdkexample.debug E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by xiaoleih41** [comment]
What kind of payment are you trying to make? What are the sender and receiver accounts?

**Comment by zzgzzzx** [comment]
PAYMENT_INTENT_SALE,
sender account:irene.lin@zeasn.com
receiver accoutn:renee.liu@zeasn.com

**Comment by xiaoleih41** [comment]
In the transaction history of the receiver account, I saw an invoice was sent to the receiver himself. It was not an invoice sent to the sender. You cannot send invoice to yourself. The error message above indicated that the payee (receiver) account is not valid. Please make sure the receiver was coded correctly.

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit if you have any further questions.
