### ISSUE TITLE
Payment Failed Paypal

### ISSUE THREAD

**Issue by kiyos1221** [paypal/PayPal-Android-SDK#413]
when trying to pay with card the alert box "System failed, please try again appears"

**Comment by biruk360** [comment]
![image](https://user-images.githubusercontent.com/5463139/27760018-92e45744-5e46-11e7-80be-81c51ad0baf3.png)
Having the same issue.
After seeing the issue I checked my card transactions and even though the payment has been initated its still pending.

**Comment by pp-randy** [comment]
Is this issue ongoing?   Live or Sandbox?

**Comment by biruk360** [comment]
Yes, still the same was just testing this.

**Comment by pp-randy** [comment]
Can you confirm if this issue is on Live or Sandbox, I tested in Sandbox and it is working in my testing. 

Do you have a paypal-debug-id?

**Comment by biruk360** [comment]
I can confirm we're doing live test
The PayPal-debug-id is cc4bc58a498ff

**Comment by pp-randy** [comment]
I suggest trying a different funding source, and if the error persists contact PayPal Technical Support.  

I did find this FAQ based on the error which seems to explain the same https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1394&expand=true&locale=en_US
