### ISSUE TITLE
Balance not increase in my business sandbox account

### ISSUE THREAD

**Issue by prashantvidja** [paypal/PayPal-Android-SDK#414]
Hello

I used PayPal-Android-SDK:2.15.3 in my android 6.0 version...
When I try to pay by PayPal only I pay with debit card in the live transaction, not with PayPal balance...

I used your SDK for test and use Sandbox account for testing when I try to make payment so transaction completed but the main balance of business account not increase but it so only in transaction history...

Thanks...

**Comment by pp-randy** [comment]
Can you give a transaction id from when this happened in Sandbox and I will take a look?

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit when you have further questions.
