### ISSUE TITLE
There was a problem setting up this payment. Please visit the paypal website to check your account.

### ISSUE THREAD

**Issue by sufutian** [paypal/PayPal-Android-SDK#415]
Hello:
  I had a problem with the sandbox payment:

  paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"bc4ca0a628000","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
paypal.sdk: PAYMENT_CREATION_ERROR

Thanks for your help.

**Comment by pp-randy** [comment]
It appears you are trying to pay with the same account receiving the payment.   

Try create a buyer account after logging into here: https://developer.paypal.com/developer/accounts/create.

**Comment by sufutian** [comment]
Automatically create user account in the sandbox seems to be no password, try to log in has failed. I have modified the sandbox automatically created users password, then log in test is ok. Thank you very much for your answer.
