### ISSUE TITLE
PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT

### ISSUE THREAD

**Issue by sufutian** [paypal/PayPal-Android-SDK#416]
I'm sorry to disturb you again:
When I tested the formal environment, payments ran into some problems.

The Error:
paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT","debug_id":"d942ca21ca48","message":"session is NON_PAYABLE","information_link":"https://github.com/paypal/PayPal-Android-SDK/blob/master/docs/supplemental_errors.md"}
paypal.sdk: PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT

The card of this personal account is China's credit card. The company's financial information tells me that this card can be paid in double currency.
But the error was reported. I want to know the details of this bug.
Thanks very much!

**Comment by xiaoleih41** [comment]
What's the sender's account email address?

**Comment by pp-randy** [comment]
The China Support landing page is here as well: https://cn.paypal-techsupport.com/app/ask
