### ISSUE TITLE
failure with http statusCode:422,exception:Unprocessable Entity

### ISSUE THREAD

**Issue by visingh016** [paypal/PayPal-Android-SDK#417]
I create two sandbox account 1)Personal and 2) Business with countries United states, as i find that its having some issue in country India, my debug id is "debug_id":"171de800e9a0b". I tried with country as india as well as country united states, but getting the same error. Please guide me through this error

**Comment by pp-randy** [comment]
It looks like the sandbox account associated to your REST Application is closed.  Try creating a new business account and new REST Application.

**Comment by visingh016** [comment]
i used different email with totally fresh client id, but still getting same error,
request failure with http statusCode:422,exception:Unprocessable Entity
request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"508571ded5ee0","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

my code:
   PayPalPayment payment = new PayPalPayment(new BigDecimal(String.valueOf(paymentAmount)), "USD", "Testing Payments",
                PayPalPayment.PAYMENT_INTENT_SALE);

        //Creating Paypal Payment activity intent
        Intent intent = new Intent(this, PaymentActivity.class);

        //putting the paypal configuration to the intent
        intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);

        //Puting paypal payment to the intent
        intent.putExtra(PaymentActivity.EXTRA_PAYMENT, payment);

        //Starting the intent activity for result
        //the request code will be used on the method onActivityResult
        startActivityForResult(intent, PAYPAL_REQUEST_CODE);
I have business as well as sandbox account too, but by default country is india,do i need to create new sandbox account?

**Comment by visingh016** [comment]
![sandboxaccount](https://user-images.githubusercontent.com/30048202/28052415-b1d4b678-6628-11e7-8536-2b1cf63d9b1a.png)
