### ISSUE TITLE
Hi, I am getting below error when I am using PayPal API integration for recurring payments through Pro account - /v1/payments/billing-agreements	23e205c9d8a67

### ISSUE THREAD

**Issue by EdusysBharath** [paypal/PayPal-Android-SDK#418]
Hi, I am getting below error when I am using PayPal API integration for recurring payments through Pro account - /v1/payments/billing-agreements	23e205c9d8a67

<img width="698" alt="capture" src="https://user-images.githubusercontent.com/1997845/28557119-3944224c-7128-11e7-9806-90dce3cd8931.PNG">

**Comment by xiaoleih41** [comment]
What credit card number were you using? Please refer to https://github.com/paypal/PayPal-Android-SDK/issues/409 for possible solution.

**Comment by pp-randy** [comment]
Generating a new test credit card number using the link in the solution will resolve this specific issue.  I looked it over and it is overused in the sandbox. 

You don't need all the steps to get a new testing card number, just use the button at the bottom of this FAQ to generate a new credit card https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413 .
