### ISSUE TITLE
Sulochana

### ISSUE THREAD

**Issue by MNGsulochana** [paypal/PayPal-Android-SDK#419]
### General information

* SDK/Library version: paypal sdk 2.15.3
* Environment: both Sandbox or Production
* `PayPal-Debug-ID` values: <PayPal Debug-ID: 45de33de568ef [sandbox, 2.15.3;release] -->
* Android Version and Device: 

### Issue description

paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity

E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"45de33de568ef","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by pp-randy** [comment]
This appears to be a currency issue and unfortunately I do not know how to resolve it. 

Please reach out to PayPal Technical Support here: https://www.paypal-techsupport.com/app/ask
