### ISSUE TITLE
UNAUTHORIZED_PAYMENT

### ISSUE THREAD

**Issue by GemiDroid** [paypal/PayPal-Android-SDK#421]
![12](https://user-images.githubusercontent.com/19525004/28882368-50563b80-77ab-11e7-93b7-8840932093ee.PNG)

![screenshot_2017-08-02-18-00-58 1](https://user-images.githubusercontent.com/19525004/28882829-b33ed198-77ac-11e7-90e8-720ffa5f5dc5.png)

The issue in detail : 

1- I have a business account for a company located in arabic country, they created their app on developer.PayPal then I created an business account and get Client ID, and make this in code 

 private static final String CONFIG_ENVIRONMENT = PayPalConfiguration.ENVIRONMENT_PRODUCTION;

    private static PayPalConfiguration config = new PayPalConfiguration()
            .environment(CONFIG_ENVIRONMENT)
            .clientId(CLIENT_ID_LIVE)
2- I tried my Visa to check transaction but get in log like in img, also get message as :

**Comment by pp-randy** [comment]
Direct Credit Card payments are not supported for all countries please see https://developer.paypal.com/docs/faq/#international-developer-questions.

Do your PayPal payments work?

**Comment by GemiDroid** [comment]
In developer.paypal  country registered for Buyer and Merchant is USA , but Live account country is UAE (United Arab Emirates)

It works fine for SandBox and in Live not working

**Comment by pp-randy** [comment]
The Merchant Account needs to go https://developer.paypal.com/developer/accountStatus/.

Then request to get Enabled for Direct Credit Cards in the Live column.
![image](https://user-images.githubusercontent.com/6819909/28884719-a7a0d4aa-7778-11e7-91cf-52f9e63c2978.png)

**Comment by GemiDroid** [comment]
Note: Direct credit card processing is not available when you use REST APIs. Although your sandbox credentials work for testing, your live credentials do not work for direct credit card processing for your country.

**Comment by pp-randy** [comment]
You should still be able to accept PayPal payments with this SDK if that is the case. 

For Direct Credit Cards you might be able to see if you are eligible for Braintree https://www.braintreepayments.com/.  Braintree is a PayPal company.

**Comment by pp-randy** [comment]
Here are some instructions for disabling direct card payments https://github.com/paypal/PayPal-Android-SDK#disabling-direct-credit-card-payments in this SDK.

**Comment by GemiDroid** [comment]
If I disabled Direct Credit Cards in my app, is that mean that all client (Buyer) must have PayPal account to pay to Merchant ??

**Comment by pp-randy** [comment]
Yes, I do not see Guest Checkout option in my testing.

**Comment by GemiDroid** [comment]
Please, to make sure that I understood well .. 
1- If I need to provide DCC  should use Braintree SDK not PayPal SDK  ? 
2- All buyers using my app and need to pay should have PayPal Account ?

**Comment by pp-randy** [comment]
> 1-  If I need to provide DCC should use Braintree SDK not PayPal SDK ?

Yes, but make sure you are eligible for credit card payments before integration work.

> 2- All buyers using my app and need to pay should have PayPal Account ?

From my testing that is the case, I do not see a Guest Checkout option.

**Comment by GemiDroid** [comment]
Thanks a lot @pp-randy  and sorry if I interrupted you :)

**Comment by pp-randy** [comment]
No problem.  I hope you are able to get a solution figured out.
