### ISSUE TITLE
 Get Shipping Address From Paypal Android SDK

### ISSUE THREAD

**Issue by prawal** [paypal/PayPal-Android-SDK#424]
Hello EveryOne,

I have one query, I want to get shipping address when transaction complete, so please let me know or guide me , how I can get the shipping address when my transaction complete through payment gateway.

Thanks
Pawan

**Comment by pp-randy** [comment]
Can you review https://github.com/paypal/PayPal-Android-SDK/issues/395

If you enable shipping address, then it should be able to be returned.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
