### ISSUE TITLE
After Paying, I need Data indicates that that client has paid, I made logs , but all I get is 08-15 17:10:38.981 5981-6464/com.orchtech.edaradotcom W/paypal.sdk: ez SN:11 PayPal Debug-ID: 9351763f76d4 [sandbox, 2.15.3;release] 08-15 17:10:39.646 5981-6464/com.orchtech.edaradotcom E/paypal.sdk: request failed with server response:Canceled

### ISSUE THREAD

**Issue by GemiDroid** [paypal/PayPal-Android-SDK#425]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Android Version and Device:

**Comment by GemiDroid** [comment]
08-15 17:10:38.981 5981-6464/com.orchtech.edaradotcom W/paypal.sdk: ez SN:11 PayPal Debug-ID: 9351763f76d4 [sandbox, 2.15.3;release]
08-15 17:10:39.646 5981-6464/com.orchtech.edaradotcom E/paypal.sdk: request failed with server response:Canceled

**Comment by GemiDroid** [comment]
I made a payment and bank notified user that his salary is reduced by amount X 
But I haven't  get in log like in Image 
![image](https://user-images.githubusercontent.com/19525004/29322907-8997c3e4-81df-11e7-9161-8d701406ebca.png)

@pp-randy 
  protected void onActivityResult(int requestCode, int resultCode, Intent data) {

        if (requestCode == REQUEST_CODE_PAYMENT) {
            if (resultCode == Activity.RESULT_OK) {

                PaymentConfirmation confirm =
                        data.getParcelableExtra(PaymentActivity.EXTRA_RESULT_CONFIRMATION);
                if (confirm != null && confirm.getProofOfPayment().getState().equals("approved")) {



                    Log.d(TAG, "onActivityResult: " + "Payment has done");

                    try {
                        Log.d(TAG, confirm.toJSONObject().toString(4));
                        Log.d(TAG, confirm.getPayment().toJSONObject().toString(4));

                        /**
                         *  TODO: send 'confirm' (and possibly confirm.getPayment() to your server for verification
                         * or consent completion.
                         * See https://developer.paypal.com/webapps/developer/docs/integration/mobile/verify-mobile-payment/
                         * for more details.
                         *
                         * For sample mobile backend interactions, see
                         * https://github.com/paypal/rest-api-sdk-python/tree/master/samples/mobile_backend
                         */
                        displayResultText("PaymentConfirmation info received from PayPal");
                        Toast.makeText(this, "Successed", Toast.LENGTH_SHORT).show();
                        /*Intent i = new Intent(this, ActivityHomePage.class);
                        i.putExtra("payment_status", confirm.getProofOfPayment().getState());*/
                        //  this.finish();

                        // Toast.makeText(this,confirm.getProofOfPayment().getState(),Toast.LENGTH_SHORT).show();

                    } catch (JSONException e) {
                        Log.e(TAG, "an extremely unlikely failure occurred: ", e);
                    }
                } else {
                    Log.d(TAG, "onActivityResult: " + "Payment has failed");
                }

            } else if (resultCode == Activity.RESULT_CANCELED) {
                Log.d(TAG, "The user canceled.");
            } else if (resultCode == PaymentActivity.RESULT_EXTRAS_INVALID) {
                Log.d(
                        TAG,
                        "An invalid Payment or PayPalConfiguration was submitted. Please see the docs.");
            }
        } else if (requestCode == REQUEST_CODE_FUTURE_PAYMENT) {
            if (resultCode == Activity.RESULT_OK) {
                PayPalAuthorization auth =
                        data.getParcelableExtra(PayPalFuturePaymentActivity.EXTRA_RESULT_AUTHORIZATION);
                if (auth != null) {
                    try {
                        Log.i("FuturePaymentExample", auth.toJSONObject().toString(4));

                        String authorization_code = auth.getAuthorizationCode();
                        Log.i("FuturePaymentExample", authorization_code);

                        sendAuthorizationToServer(auth);
                        displayResultText("Future Payment code received from PayPal");

                    } catch (JSONException e) {
                        Log.e("FuturePaymentExample", "an extremely unlikely failure occurred: ", e);
                    }
                }
            } else if (resultCode == Activity.RESULT_CANCELED) {
                Log.i("FuturePaymentExample", "The user canceled.");
            } else if (resultCode == PayPalFuturePaymentActivity.RESULT_EXTRAS_INVALID) {
                Log.i(
                        "FuturePaymentExample",
                        "Probably the attempt to previously start the PayPalService had an invalid PayPalConfiguration. Please see the docs.");
            }
        } else if (requestCode == REQUEST_CODE_PROFILE_SHARING) {
            if (resultCode == Activity.RESULT_OK) {
                PayPalAuthorization auth =
                        data.getParcelableExtra(PayPalProfileSharingActivity.EXTRA_RESULT_AUTHORIZATION);
                if (auth != null) {
                    try {
                        Log.d("ProfileSharingExample", auth.toJSONObject().toString(4));

                        String authorization_code = auth.getAuthorizationCode();
                        Log.d("ProfileSharingExample", authorization_code);

                        sendAuthorizationToServer(auth);
                        displayResultText("Profile Sharing code received from PayPal");

                    } catch (JSONException e) {
                        Log.d("ProfileSharingExample", "an extremely unlikely failure occurred: ", e);
                    }
                }
            } else if (resultCode == Activity.RESULT_CANCELED) {
                Log.d("ProfileSharingExample", "The user canceled.");
            } else if (resultCode == PayPalFuturePaymentActivity.RESULT_EXTRAS_INVALID) {
                Log.d(
                        "ProfileSharingExample",
                        "Probably the attempt to previously start the PayPalService had an invalid PayPalConfiguration. Please see the docs.");
            }
        }
    } 

Any help !

**Comment by jaypatel512** [comment]
Please refer to the message in the issue https://github.com/paypal/PayPal-Android-SDK/issues/311
> If the transaction is successful, and you notice no other effects, then I suggest ignoring this message. The Android SDK automatically retrieves another access_token for a subsequent payment, but that can be canceled if you stop the service while that operation in progress.

Please make sure on the server side that the payment is successful by fetching the payment details, and making sure of the state.

**Comment by GemiDroid** [comment]
Thanks @jaypatel512

**Comment by xiaoleih41** [comment]
I am closing this issue as the answer has been provided.
