### ISSUE TITLE
Looking for Payapl Here sdk to interact with Papal here reder that plugs into audio jack 

### ISSUE THREAD

**Issue by AbdulSalamAli0018** [paypal/PayPal-Android-SDK#427]
I have a Paypal here card reader that plugs into the mobile. I have a small requirement and that is reading the card and saving the information of card . 

I want the following information from the card data 

1) Card Number 
2) Card Holder name 
3) expiry data

Then After getting the card information i wanted to call my on webservices. 

Please let me know if that is possible. ? How can I make the Paypal here card reader to give me required data. .. ....

**Comment by ppmtscory** [comment]
All of the information is encrypted at the time of the swipe so you won't be able to get the unencrypted information to send to your web service.  Also, the correct Github repo for the PayPal Here product is [here](https://github.com/paypal/paypal-here-sdk-android-distribution).
