### ISSUE TITLE
request failure with http statusCode:422,exception

### ISSUE THREAD

**Issue by HRCJ7** [paypal/PayPal-Android-SDK#429]
### General information

* SDK/Library version: 2.14.2
* Environment: Sandbox
* `PayPal-Debug-ID` values: 114986a1306a
* Android Version and Device: Samsung J2 ,Android 5.1
```

09-08 13:41:54.227 12937-16462/com.example.rajitha.paypal E/paypal.sdk: request failure with http statusCode:422,exception:
09-08 13:41:54.227 12937-16462/com.example.rajitha.paypal E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"114986a1306a6","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
09-08 13:41:54.232 12937-12937/com.example.rajitha.paypal E/paypal.sdk: PAYMENT_CREATION_ERROR
```
Is this error occured due which reason?
Thank you all.

**Comment by xiaoleih41** [comment]
It looks like it has something to do with your Indian merchant account receiving USD payments and holding USD payments in the account. Indian PayPal should not be able to hold any balance at all. I am not sure why it allowed it. Can you try with a US  merchant account to see if the issue persists?

**Comment by HRCJ7** [comment]
Thank you, I resolved it.
