### ISSUE TITLE
NullPointerException on handling activity result

### ISSUE THREAD

**Issue by snakelizzard** [paypal/PayPal-Android-SDK#430]
### General information

* SDK/Library version: 2.15.1
* Environment: production
* Android Version and Device: TCL (A466BG) with Android 6.0, LG L39C with Android 4.1.2

### Issue description

Got this exception on at least two devices. This stack is automatically reported. Sorry, can not provide more details. 

```
Caused by java.lang.NullPointerException
com.paypal.android.sdk.payments.l.a (Unknown Source)
com.paypal.android.sdk.payments.m.onActivityResult (Unknown Source)
android.app.Activity.dispatchActivityResult
```

**Comment by xiaoleih41** [comment]
Do you have a `debugId` ?

**Comment by snakelizzard** [comment]
No. This happens on processing result from some secondary Paypal SDK activity. I am not sure transaction even started.

**Comment by xiaoleih41** [comment]
Can you please provide steps on how to recreate this error?

**Comment by snakelizzard** [comment]
Sorry, no steps for this one. The stack is sent by the automatic error collector from several end user devices.

**Comment by xiaoleih41** [comment]
This SDK is now deprecated. Please consider to integrate Braintree direct or Express Checkout with Braintree SDK. For more detail, please check [here](https://developer.paypal.com/docs/integration/mobile/mobile-sdk-overview/#paypal-mobile-sdks)
