### ISSUE TITLE
Error while making payment from debit & credit card from any region

### ISSUE THREAD

**Issue by jid001** [paypal/PayPal-Android-SDK#432]
* SDK/Library version: 2.15.3
* Environment: Live
* `PayPal-Debug-ID` values: 4273a758dad2a
* Android Version and Device: Nexus 5X

### Issue description

STEPS ->Pay with card
2. Entered card details 
3. Charge card.
4. The below error occurred.
![screenshot_20170918-000904](https://user-images.githubusercontent.com/16589316/30523875-fd71deb2-9c06-11e7-9f61-3a1a445e39fb.png)

E/paypal.sdk: request failure with http statusCode:400,exception:Bad Request
E/paypal.sdk: request failed with server response:{"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"4273a758dad2a"}
 E/paypal.sdk: UNKNOWN_ERROR

**Comment by xiaoleih41** [comment]
It shows that there's no complete billing address entered.  Please make sure to enter a complete billing address.

**Comment by jid001** [comment]
I don't find a place to enter billing address while using this library nor it provides input fields like that. 
Can you confirm how I am supposed to send billing address?

![img_20170919_013528](https://user-images.githubusercontent.com/16589316/30562217-4b2ab2d0-9cdb-11e7-8bad-d9756e98b575.jpg)

**Comment by xiaoleih41** [comment]
It could be your PayPal account setting.  You need to have it set to request the buyer's billing address.
