### ISSUE TITLE
Error while making payment from debit & credit card from any region (cont)

### ISSUE THREAD

**Issue by jid001** [paypal/PayPal-Android-SDK#433]
* SDK/Library version: 2.15.3
* Environment: Live
* `PayPal-Debug-ID` values: 4273a758dad2a
* Android Version and Device: Nexus 5X

The error confirmed from Paypal support is that I am not sending billing address. But, I don't find a place to enter billing address while using this library nor it provides input fields like that.
Can you confirm how I am supposed to send billing address?

![img_20170919_013528](https://user-images.githubusercontent.com/16589316/30562470-26b4fbf8-9cdc-11e7-9944-62e1101aec00.jpg)

**Comment by xiaoleih41** [comment]
The passing billing address feature might not have been enabled. Please contact customer service listed on your account to see if they can enable for you.

**Comment by xiaoleih41** [comment]
Close the issue as the possible cause of issue has been provided. Please resubmit if you have any further questions.
