### ISSUE TITLE
Android Paypal SDK Payment, Authorization and Order at the same time

### ISSUE THREAD

**Issue by edumolins** [paypal/PayPal-Android-SDK#435]
I am using Android Paypal SDK and I need to receive a payment and also set an authorization and Order the rest. I know how to do it in 3 steps but I am wondering if it is possible to do it in one step (same object). Tried put multiple Intent PayPalPayment but doesn't work. Thanks

`PayPalPayment payment1 = new PayPalPayment(new BigDecimal("1.75"), "USD", "hipster jeans",
                PayPalPayment.PAYMENT_INTENT_SALE);
PayPalPayment payment2 = new PayPalPayment(new BigDecimal("100"), "USD", "Warranty",
                PayPalPayment.PAYMENT_INTENT_AUTHORIZE);    
Intent intent = new Intent(this, PaymentActivity.class); intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config); intent.putExtra(PaymentActivity.EXTRA_PAYMENT, payment1);
intent.putExtra(PaymentActivity.EXTRA_PAYMENT, payment2);
startActivityForResult(intent, 0);`

**Comment by xiaoleih41** [comment]
You cannot submit multiple transactions in one step. You will have to submit separately.

**Comment by xiaoleih41** [comment]
Close the issue as the issue has been addressed.
