### ISSUE TITLE
Getting Error No virtual method startsWith(Lokio/ByteString;)Z in latest version of sdk.

### ISSUE THREAD

**Issue by Maqsood007** [paypal/PayPal-Android-SDK#436]
I was using Paypal-android-sdk version **compile 'com.paypal.sdk:paypal-android-sdk:2.14.2'** and all thing was going fine and i was doing successful sandbox transaction and as i updated Paypal-android-sdk version to **compile 'com.paypal.sdk:paypal-android-sdk:2.15.3'** , its getting an errorgiven below just on starting PayPal Service in **protected void onCreate(Bundle savedInstanceState)**.

**Error:**
java.lang.NoSuchMethodError: No virtual method startsWith(Lokio/ByteString;)Z in class Lokio/ByteString; or its super classes (declaration of 'okio.ByteString' appears in /data/app/com.kaimeramedia.mobilexp-1/base.apk:classes42.dex)

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by xiaoleih41** [comment]
This SDK is now deprecated. Please consider to integrate Braintree direct or Express Checkout with Braintree SDK. For more detail, please check [here](https://developer.paypal.com/docs/integration/mobile/mobile-sdk-overview/#paypal-mobile-sdks)

**Comment by jaypatel512** [comment]
Hey @Maqsood007 !

Do you have a dependency that uses okhttp, and if so, do you know what version of okhttp is being used in your app ?

Thanks

**Comment by Maqsood007** [comment]
@jaypatel512 ,
Hello sir,
  No i am not using okhttp, because i just imported the okhttp dependency to check any duplication, but its works fine.

**Comment by xiaoleih41** [comment]
@Maqsood007 Was your issue solved? If so, could you please close the issue?

**Comment by Maqsood007** [comment]
@xiaoleih41 , I reverted PayPal dependency version to  *2.14.2*, because you told that  *2.15.3* is deprecated. so should i close the thread or any fixes done with *2.15.3*.

**Comment by jaypatel512** [comment]
Hey @Maqsood007 ! 

we were unable to reproduce this error on 2.15.3. We tested this using our Sample app, on both Android Studio 2.x and 3.x. 

<img width="1915" alt="screen shot 2017-10-30 at 12 43 06 pm" src="https://user-images.githubusercontent.com/1309895/32186601-8023cfa2-bd70-11e7-95fc-3dd373fef294.png">

Could you please download this repository, and try our sample app to see if you are still getting the same error on your side. This should help us identify the issue much quicker. Thanks @Maqsood007 for your help.

**Comment by jaypatel512** [comment]
And @Maqsood007 ! about @xiaoleih41 's comment. We are encouraging all developers to use newer integration methods mentioned [here](https://developer.paypal.com/docs/integration/mobile/mobile-sdk-overview/#paypal-mobile-sdks).

**Comment by Maqsood007** [comment]
Its working fine now on Android Studio 3.0. Error was occurred on my previous Android studio version 2.3.x. So Thanks to all of you for a warm response so now i am closing the issue.
Thanks to all.
