### ISSUE TITLE
Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} while pressing back on payment activity in Kotlin

### ISSUE THREAD

**Issue by aarif04march** [paypal/PayPal-Android-SDK#437]
### General information

* SDK/Library version: 2.15.3
* Environment: Sandbox/Production both
* Android Version and Device: On every version and every device

### Issue description

I have used Kotlin for the development of my app. I have integrated the code successfully and its working fine when i am doing payment. But once i press back button on Payment activity, Application crashed with below mentioned error.

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data

However I Have fixed the issue by making a small change which is mentioned below.

override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent) {}

update the above mentioned method as below

override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {}

data should be defined as nullable i.e. data: Intent?

**Comment by xiaoleih41** [comment]
Can you submit a pull request and we will review it.

**Comment by jaypatel512** [comment]
Hey @aarif04march ! I am no kotlin expert, but do you wish to update the SampleActivity `onActivityResult` method ? I just wanted to confirm.

**Comment by aarif04march** [comment]
Hey @jaypatel512 You just need to add ? with `Intent` in `onActivityResult` as the data can be null if user cancels the transaction or anything goes wrong. So we need to define `data` as nullable in `onActivityResult`

Just replace `onActivityResult` signature of SampleActivity with below:

`override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?)`

**Comment by jaypatel512** [comment]
Cool ! That's exactly what I thought. I will go ahead and make this change, and get the samples updated as soon as possible. Thanks @aarif04march for your help.

**Comment by xiaoleih41** [comment]
The change has been made. The new version will be released soon.
