### ISSUE TITLE
REST API issues failure with http statusCode:400

### ISSUE THREAD

**Issue by djx1986sky** [paypal/PayPal-Android-SDK#441]
REST API issues
* SDK/Library version:  [live, 2.15.3;release]
* Environment: Production
* `PayPal-Debug-ID` values:  a80c0a6899e9d
* Android Version and Device: Oppo  with Android 4.3 
request failed with server response:{"name":"TRANSACTION_REFUSED","debug_id":"c37f7b7a9ffbc","message":"The request was refused","information_link":"https://developer.paypal.com/docs/api/#TRANSACTION_REFUSED"}

**Comment by xiaoleih41** [comment]
This has something to do with the transaction funding source. It is not a technical issue. Please have the send try a different funding method or contact customer service to get more detail on this.
