### ISSUE TITLE
Callback function return null  after handelActivityResult()

### ISSUE THREAD

**Issue by NguyenPhong276** [paypal/PayPal-Android-SDK#442]
### General information
* SDK/Library version: 2.15.3
* Environment: Sandbox 
* Android Version and Device: Samsung Galaxy J2 Prime with Android 6.0.1

### Issue description
Hi everybody,
I have problem with my app React Native and I haven't a solution for this bug.. I have integrated Paypal Android SDK. 
Please see the screens shot.
![screenshot 12](https://user-images.githubusercontent.com/18061490/31584575-3caa8cd4-b1db-11e7-9ac6-a1abaab50bda.png)
![screenshot 13](https://user-images.githubusercontent.com/18061490/31584579-4645f242-b1db-11e7-8950-5633a0b8fbd7.png)
![screenshot 14](https://user-images.githubusercontent.com/18061490/31584580-4b236a7e-b1db-11e7-9534-f16df98a5edd.png)
![screenshot 15](https://user-images.githubusercontent.com/18061490/31584581-4fc5197e-b1db-11e7-8fca-0dd2ad48db0c.png)
![screenshot 16](https://user-images.githubusercontent.com/18061490/31584585-62595b54-b1db-11e7-8d06-b6afc9748583.png)
![screenshot 17](https://user-images.githubusercontent.com/18061490/31584611-c2fc00ba-b1db-11e7-824e-65efe505c11a.png)
![screenshot 18](https://user-images.githubusercontent.com/18061490/31584613-cb703a86-b1db-11e7-9e87-b22320c2205e.png)
![screenshot 19](https://user-images.githubusercontent.com/18061490/31584607-af493ed4-b1db-11e7-8b59-6270601dedc6.png)

I don't understand my callback function return null after call payment request (startActivityForResult)  with 3 prameters: params, success function and error function.
Everybody can help me, please?. Thank you so much.

My payment request have return a response from server SANDBOX:
confirm:
{
  "client": {
    "environment": "sandbox",
    "paypal_sdk_version": "2.15.3",
    "platform": "Android",
    "product_name": "PayPal-Android-SDK"
  },
  "response": {
    "create_time": "2017-10-13T08:41:50Z",
    "id": "PAY-1B6699940E959792TLHQHYLY",
    "intent": "sale",
    "state": "approved"
  },
  "response_type": "payment"
}

**Comment by xiaoleih41** [comment]
PayPal is in the process of deprecating this SDK. Please consider to integrate https://github.com/braintree/braintree_android instead for the PayPal feature.

**Comment by xiaoleih41** [comment]
Close this issue as the SDK has been deprecated and new integration has been recommended.
