### ISSUE TITLE
How to solve this > merchantName & Extras is invalid?

### ISSUE THREAD

**Issue by AlaaZarifa** [paypal/PayPal-Android-SDK#443]
* SDK/Library version: 2.14.4  
* Environment: Sandbox 
 * Android Version and Device:   HTC M8 with Android 6.0  

### Issue description
 
I want to set up  **`FuturePayment`** into my app, I followed the steps in this [docs](https://github.com/paypal/PayPal-Android-SDK/blob/master/docs/future_payments_mobile.md#obtain-customer-consent).
in the first step wihch is "Obtain Customer Consent" I did everything normally, but I keep getting this error?
```

  E/PayPalFuturePaymentActivity: merchantName is invalid.  Please see the docs.
  E/PayPalFuturePaymentActivity: merchantPrivacyPolicyUrl is invalid.  Please see the docs.
  E/PayPalFuturePaymentActivity: merchantUserAgreementUrl is invalid.  Please see the docs.
  E/PayPalFuturePaymentActivity: Extras invalid.  Please see the docs.
```

- The merchant name that I added is `Credit Card Statement Name` as it said in this [docs](https://developer.paypal.com/docs/classic/admin/setup-account/).
- the urls are the same in the example since it's a sandbox.

 **So why I'm getting this error? how can I get the valid info..?**

### My Code

```
// inside PaymentActivity..

  public void initPayPal() {

    config = new PayPalConfiguration()
        .environment(PayPalConfiguration.ENVIRONMENT_SANDBOX)
        .clientId(getResources().getString(R.string.PAYPAL_CONFIG_CLIENT_ID_SANDBOX))
        .merchantName("BELxxxxxx")
        .merchantPrivacyPolicyUri(Uri.parse("https://www.example.com/privacy"))
        .merchantUserAgreementUri(Uri.parse("https://www.example.com/legal"));

    Intent intent = new Intent(this, PayPalService.class);
    intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
    startService(intent);
  }

    public void PayButtonPress() {
        Intent intent = new Intent(PaymentActivity.this, PayPalFuturePaymentActivity.class);
        intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
        startActivityForResult(intent, REQUEST_CODE_FUTURE_PAYMENT);
    }
```

**Comment by xiaoleih41** [comment]
Do you have a `debugId` associated with this API call? Also, as future payment has been deprecated from REST API. I don't believe PayPal will approve anymore new future payment application.  Please make sure you have got approval for live production before continue this integration.  I would suggest you to integration Braintree SDK from developers.braintreepayments.com. It supports multiple payment methods including PayPal.

**Comment by xiaoleih41** [comment]
Close this issue as PayPal-Android-SDK has been deprecated.
