### ISSUE TITLE
Payment method type error

### ISSUE THREAD

**Issue by akashmi** [paypal/PayPal-Android-SDK#444]
Getting below error while try to make payment.
"the merchant does not accept payments of this type"

**Comment by xiaoleih41** [comment]
Can you please provide more detail such as a `debugId` of the API call?

**Comment by akashmi** [comment]
request failed with server response 
"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"44f785fb9e13d"}

**Comment by xiaoleih41** [comment]
If the account is not approved for direct credit card processing, you will get this error. As PayPal has deprecated the direct credit card processing feature for REST API. Please consider to integrate  https://github.com/braintree/braintree_android instead for both PayPal and Braintree  processing.
