### ISSUE TITLE
Getting INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by Eccelor** [paypal/PayPal-Android-SDK#445]
* SDK/Library version: sandbox, 2.15.3; release
* Environment: SandBox
* `PayPal-Debug-ID` values: f84f7990eeebb
* Android Version and Device: Android Emulator - Android 8.0 with Google API and Play Store

### Issue description

This issue occurs whenever the user tries to make direct card payment using stored card.
Steps to reproduce,
1. Create a transaction by adding credit card (Pay using Card, without logging in to PayPal)
2. Transaction is completed successfully
3. Attempt a different transaction and while making payment select Pay using Card with saved card information - Error Message - System Error. Please try again later.
4. Within same transaction, go back and clear card information.
5. Make payment by adding new card like step 1. Transaction is completed successfully.

**Comment by xiaoleih41** [comment]
PayPal has deprecated the direct card processing feature on REST API.l Please consider Braintree payments on Braintreepayments.com instead if you are considering supporting multiple payment methods including credit card and PayPal on vault feature. For more detail please refer to the [README.md](https://github.com/paypal/PayPal-Android-SDK) of this repository.

**Comment by haseelrefl** [comment]
Facing the same issue here. This was not a direct card payment but payment using paypal account on sandbox.

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 4bb5116f3a70c, 4bb5116f3a70c [sandbox, PayPal iOS SDK 2.16.1]

**Comment by xiaoleih41** [comment]
PayPal is in the processing of deprecating REST Android SDK. if you have not yet been in production on this integration, please consider to integrate https://github.com/braintree/braintree_android on the PayPal feature.

**Comment by Eccelor** [comment]
The thing is, Braintree does not allow/support the use case we are integrating for. We had used Braintree. But due to unsupported use case we cannot use it anymore.

**Comment by xiaoleih41** [comment]
@Eccelor What is the use case? I would strongly suggest you to contact sales team through the contact us number listed on your account. You will need a sales person to help you get the approval for production  usage before investing time and energy on the development.

**Comment by Eccelor** [comment]
@xiaoleih41 We are building a typical marketplace application but without us being in the middle and handle payouts and etc. We were using Braintree Direct and whenever a user wants to make payment to a specific vendor, we would load merchant id of that vendor which is stored in our database and make a transaction directly to the vendor. So at the end it will be a one on one direct transaction.

We have contacted the sales team on phone. They said that they cannot allow such kind of integration because it is considered as payment aggregation even if the payment in only one to one.

**Comment by xiaoleih41** [comment]
If I heard it right. your account will not touch the funds and the payment will be sent directly from the buyer to the seller.  If that's the case, it is not aggregation. PayPal has opened it up  the `payee` object. Please check into [this](https://www.paypal-engineering.com/2017/01/03/setting-payee/)  As the REST SDK has been deprecated. You may talk to sales on using Express Checkout through braintree option instead.  Additional account setting maybe needed.

**Comment by Eccelor** [comment]
Yes that is correct. Our account will not touch the funds and payment will be directly sent to the seller. Thanks for pointing that out. We'll check with both PayPal and Braintree on using the solution you suggested.

**Comment by xiaoleih41** [comment]
I will close this ticket as possible solution has been suggested.
