### ISSUE TITLE
http statusCode:422 , debug_id":"ccbc1adb75753

### ISSUE THREAD

**Issue by peijinliang** [paypal/PayPal-Android-SDK#447]
paypal.sdk: request failure with http statusCode:422,exception:
paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"ccbc1adb75753","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
 E/paypal.sdk: PAYMENT_CREATION_ERROR

Is it my account issue ?

**Comment by xiaoleih41** [comment]
You cannot pay yourself. The sender and receiver have to be different accounts.

**Comment by pp-randy** [comment]
Closing the issue as the solution has been provided.

**Comment by peijinliang** [comment]
thanks
