### ISSUE TITLE
is verified account required to receive payment in paypal android sdk

### ISSUE THREAD

**Issue by simontifo** [paypal/PayPal-Android-SDK#45]
I want to know if it is required to have a verified paypal account to receive money through paypal android sdk

because even I have set the environment to production and set live credentials

private static final String CONFIG_ENVIRONMENT = PaymentActivity.ENVIRONMENT_PRODUCTION;

I have that in the response knwoing that I have sent payment from a verified account wich contains solde paypal:

"payment_exec_status": "ERROR"

and payment is not performed

this is why I was wondering if the verified account is required to receive money

**Comment by SandeepRana** [comment]
When i'm click on send payment  i have get response i sendbox account "payment_exec_status": "ERROR"

**Comment by ppmtscory** [comment]
@SandeepRana can you please provide the full response so that we can see the debug_id?  Also, if you're not using the latest version of the SDK, I'd recommend doing so.

**Comment by SandeepRana** [comment]
this is response i'm geting
![device-2015-01-28-102810](https://cloud.githubusercontent.com/assets/10665360/5932749/0748aed6-a6da-11e4-9097-17e3e533404c.png)

**Comment by ppmtscory** [comment]
@SandeepRana Please upgrade your app to use the latest version of the SDK which is 2.8.4.  The version you are running is running on a different platform for PayPal payments than what is used today.  Once you are done upgrading, if you still have errors, please open a new issue and post the full response there.
