### ISSUE TITLE
Paypal android sdk issue

### ISSUE THREAD

**Issue by sagarikadas91** [paypal/PayPal-Android-SDK#452]
### General information

* SDK/Library version: 2.15.3
* Environment: Sandbox
* `PayPal-Debug-ID` values: 1bf5738f5f74
* Android Version and Device: LYF with android marshmallow, Redmi Note4 with android nougat

### Issue description
I am facing problem in pay pal android sdk. Every time I am getting the same issue. Please its urgent. Help me.
11-10 15:05:49.827 30851-8987/example.paypal.paymentsample W/paypal.sdk: fc SN:26 PayPal Debug-ID: 1bf5738f5f74 [sandbox, 2.15.3;release]
11-10 15:05:49.828 30851-8987/example.paypal.paymentsample E/paypal.sdk: request failure with http statusCode:422,exception:
11-10 15:05:49.828 30851-8987/example.paypal.paymentsample E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"1bf5738f5f74","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
11-10 15:05:49.829 30851-30851/example.paypal.paymentsample E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by AnonymousGod** [comment]
Facing same issue with sandbox testing with Android sdk. Here is the logcat
E/paypal.sdk: request failure with http statusCode:422,exception:
E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"85e5b1d341cf4","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by xiaoleih41** [comment]
@sagarikadas91 It has something to do with transaction receiving limit on the receiver's account. You may contact www.paypal-techsupport.com to report this issue. @AnonymousGod  The debugId doesn't look to be valid anymore.  This error normally indicates account setting related issue.  It's not an integration issue.  With the right buyer and seller account, you will not get this issue. Please check the setting of both account settings and make sure that they are eligible to make the type of API calls that you are making.

**Comment by himanshu1706** [comment]
I am getting same error;

paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"3550e355c6299","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

I am using sandbox env. Please guide me to resolve the error.

**Comment by himanshu1706** [comment]
Ok I got it resolved by creating new merchant account. May be there is some problem with old merchant account. Thanks to paypal community.

**Comment by alaadeego** [comment]
@himanshu1706  i would like to ask you does it wrok fine for live state?
 i'm confused that in read me i read that:
**Important: PayPal Mobile SDKs are now Deprecated and only existing integrations are supported. For all new integrations, use Braintree Direct in supported countries. In other countries, use Express Checkout and choose the Braintree SDK integration option.**

so does it mean its workking so i can use or not ??

**Comment by himanshu1706** [comment]
@alaadeego You can use it but it will not have future updates.

**Comment by xiaoleih41** [comment]
@alaadeego There will be no future updates and certain advance features may not be approved for live production.

**Comment by xiaoleih41** [comment]
Close as the answer has been given.
