### ISSUE TITLE
PayPal-Android-SDK Deprecated

### ISSUE THREAD

**Issue by alaadeego** [paypal/PayPal-Android-SDK#453]
i have noticed it this  note but i don't undersand what **Deprecated**  mean , does  it mean i can still use this sdk  or not  
**Important: PayPal Mobile SDKs are now Deprecated and only existing integrations are supported. For all new integrations, use Braintree Direct in supported countries. In other countries, use Express Checkout and choose the Braintree SDK integration option.**
i would like  to know if i still can use this or not ?

**Comment by xiaoleih41** [comment]
It means that no more new application will be approved if there's any advanced feature such as direct credit card process will not be approved for new integration. If you have launched the product before it was deprecated, you can still access the info for reference but we don't encourage any new integrations.
