### ISSUE TITLE
Enforce decimal rounding

### ISSUE THREAD

**Issue by AllanWang** [paypal/PayPal-Android-SDK#454]
SDK: 2.15.3

The API requires either no decimal or exactly two decimal places.

Floating point numbers often have slight rounding issues, so why not call `BigDecimal.setScale(2, flag)` directly in the sdk? Developers will still be able to scale themselves beforehand, but there will be a fallback to ensure that float errors (eg 10.079999999) never happen.

**Comment by pp-randy** [comment]
This SDK is deprecated in favor of our Braintree offerings, more information can be found at the top of the [README.md](https://github.com/paypal/PayPal-Android-SDK/blob/master/README.md).  

Closing the issue based on a similar situation on the iOS SDK https://github.com/paypal/PayPal-iOS-SDK/issues/502.  The developer should ultimately decide to round up, down, or truncate a decimal value.
