### ISSUE TITLE
PaymentCreation Error in Sandbox

### ISSUE THREAD

**Issue by MubinaHb** [paypal/PayPal-Android-SDK#455]
I am getting below error while payment processing in sandbox mode
getting statusCode:422

{"name":"PAYMENT_CREATION_ERROR","debug_id":"7baa29f9efa32","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}

Using  compile('com.paypal.sdk:paypal-android-sdk:2.15.3')

**Comment by pp-randy** [comment]
What is the transaction amount?  It looks like a possible issue with the amount, does a lower amount work in your integration?

**Comment by MubinaHb** [comment]
I have checked with the amount of 0.01USD and 10USD then I have created the new Paypal account and using the sandbox credentials of that account Payment process works fine but using previous paypal credentials it is giving me this error exactly don't know what the issue with previous Paypal account.

**Comment by xiaoleih41** [comment]
It is normally account related issue. Close this issue as the issue appears to be solved.
