### ISSUE TITLE
PayPalFuturePaymentActivity help

### ISSUE THREAD

**Issue by nigelbro** [paypal/PayPal-Android-SDK#456]
### General information

* SDK/Library version: 2.15.3
* Environment: Sandbox
* `PayPal-Debug-ID` values: 2fb25c09dc29f
* Android Version and Device: 7.0 galaxy note 8

### Issue description

I have been using paypal single payments in my application and just recently started trying to use future payments the issue that im having is that i keep getting this message :

 E/PayPalFuturePaymentActivity: merchantName is invalid.  Please see the docs.
 E/PayPalFuturePaymentActivity: merchantPrivacyPolicyUrl is invalid.  Please see the docs.
 E/PayPalFuturePaymentActivity: merchantUserAgreementUrl is invalid.  Please see the docs.
 

What does this mean and where do I find this information because I can not find any place that I would have set the user agreement or privacy policy and what is the merchant name? The name the shows on my developer app account is not working ?

**Comment by pp-randy** [comment]
Future Payments looks to be needing some Log In With PayPal details. 

Go to your Rest App here https://developer.paypal.com/developer/applications/
Expand the Log in with PayPal Advanced Options
![image](https://user-images.githubusercontent.com/6819909/34490128-722925a8-efa4-11e7-9f96-813e937779be.png)

You should see the input for Privacy and the User Agreement.  Let me know if that doesn't correct it after providing those.

**Comment by bluk** [comment]
@nigelbro Note that if you are just starting to use Future Payments, I would recommend seeing if you can get a [Braintree](https://www.braintreepayments.com/) Account (a PayPal service) and using the [Vaulted payment flow](https://developers.braintreepayments.com/guides/paypal/vault/android/v2).

**Comment by xiaoleih41** [comment]
Close this issue as future payments feature has been deprecated. A new product feature has been suggested.
