### ISSUE TITLE
Request failure with http statusCode:422,exception

### ISSUE THREAD

**Issue by VicJcc** [paypal/PayPal-Android-SDK#458]
### General information

* SDK/Library version: 2.15.3
* Environment: Sandbox
* `PayPal-Debug-ID` values: 8f0da350ed70e
* Android Version and Device: Oppo R11 with Android 7.1

### Issue description

01-15 18:16:48.867 7820-8383/com.taole.seek E/paypal.sdk: request failure with http statusCode:422,exception:
01-15 18:16:48.867 7820-8383/com.taole.seek E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"8f0da350ed70e","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
01-15 18:16:48.869 7820-7820/com.taole.seek E/paypal.sdk: PAYMENT_CREATION_ERROR

Thank you

**Comment by VicJcc** [comment]
PS：facilitator and buyer accounts is C2 (China?)

**Comment by pp-randy** [comment]
I think for a China merchant you need two accounts if you want domestic and international payments.  The `C2` account is for accepting payments from other countries, and `CN` would be used for domestic payments.  

Have you discussed with a sales team regarding your account configurations? https://www.paypal.com/c2/webapps/mpp/merchant

**Comment by xiaoleih41** [comment]
Also, how much were you trying to send? Please try an amount lower than the account balance instead to see if it works.

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity. Please resubmit if issue hasn't been solved.
