### ISSUE TITLE
PAYMENT_CREATION_ERROR

### ISSUE THREAD

**Issue by KUSH9148** [paypal/PayPal-Android-SDK#459]
### General information

* SDK/Library version: android-sdk:2.15.3
* Environment: Production
* `PayPal-Debug-ID` values: Debug-ID: c8238d08d445
* Android Version and Device: Xiaomi Mi A1 with Android 8.0.0, Pixel_XL with Android 6.0

### Issue description
After logging in paypal account its showing a dilog with message; 'There was a problemsetting up this payment. Please visit the paypal website to check your account.'

**Comment by pp-randy** [comment]
That message to me indicates an account issue, and you should contact PayPal customer support for assistance with the payer account https://www.paypal.com/help.
