### ISSUE TITLE
PAYMENT_CREATION_ERROR

### ISSUE THREAD

**Issue by Adriani6** [paypal/PayPal-Android-SDK#460]
### General information

* SDK/Library version: Latest provided by Paypal-Mobile-Cordova (Version 3.5.0)
* Environment: Sandbox
* `PayPal-Debug-ID` values: 

01-20 14:02:15.557 11659-11775/io.cordova.myapp062cee W/paypal.sdk: fc SN:11 PayPal Debug-ID: 9d9ae0b01371b [sandbox, 2.15.3;release]
01-20 14:02:15.557 11659-11775/io.cordova.myapp062cee E/paypal.sdk: request failure with http statusCode:422,exception:
01-20 14:02:15.557 11659-11775/io.cordova.myapp062cee E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"9d9ae0b01371b","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
01-20 14:02:15.570 11659-11659/io.cordova.myapp062cee E/paypal.sdk: PAYMENT_CREATION_ERROR

* Android Version and Device: Various Emulators + Samsung Galaxy S7 Edge with latest Android update.

### Issue description

I have created a Busienss account with 0 balance (UK), and Personal account with over 1k balance and also from UK. In my paypal app I added the Business account. When checking out on mobile I login as the personal account and I get the above. If I keep hitting Retry button, 1 out of 100 times it would process that stage but would fail on the next one where I select the shipping address and finalise the payment. 

It is worth noting that this issue has never occured before. It was working just fine. I use the paypals shipping address on checkout.

Where is my data that I try to pass in (the data types are correct as per documentation, the output from debugger just strips the quotation marks out)

````
PayPalItem:{
   currency:GBP,
   name:23761,
   price:30,
   quantity:1,
   sku:null
}

PayPalPaymentDetails:{
   shipping:10.00,
   subtotal:30.00,
   tax:0.00
}

PayPalPayment{
   amount:40.00,
   bnCode:PhoneGap_SP,
   currency:GBP,
   details:PayPalPaymentDetails,
   intent:Sale,
   items:[
      PayPalItem
   ],
   shortDescription:Mobile Order
}

**Comment by xiaoleih41** [comment]
The account is closed for some reason. Please create a transaction and app under an active account.

**Comment by Adriani6** [comment]
Issue was somewhere else. 
I have deleted the old apps & accounts to see if that would help and it did not, however...
after 3 days since discovery the system, going through lots of pain with deleting, creating and updating app and accounts it works again just fine without code changes. Thanks.
