### ISSUE TITLE
The merchant does not accept payments of this type

### ISSUE THREAD

**Issue by phyooos** [paypal/PayPal-Android-SDK#464]
### Log

```
E/paypal.sdk: request failure with http statusCode:401,exception:
 
E/paypal.sdk: request failed with server response:{"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"f2ae89e6eeb0a"}

E/paypal.sdk: UNAUTHORIZED_PAYMENT
```

### Code
I am very confused

SDK Version     `compile  com.paypal.sdk:paypal-android-sdk:2.15.3`

Android Version     `23`

```

    /**
     * init payserver
     */
    public void initPayPalServer() {
        configuration = new PayPalConfiguration()
                .acceptCreditCards(true)
                .rememberUser(true)
                .environment(PayPalConfiguration.ENVIRONMENT_PRODUCTION)
                .clientId(LIVE_TOKEN);

        //to pay
        Intent intent = new Intent(mActivity, PayPalService.class);
        intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, configuration);
        mActivity.startService(intent);
    }
```

**Comment by bluk** [comment]
It seems that your live account is not enabled correctly. If this is an existing integration, please contact [PayPal Technical Support](https://developer.paypal.com/support/).

If this is a new integration, you should use [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct) in [supported countries](https://www.braintreepayments.com/country-selection). In other countries, use [Express Checkout](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) and choose the Braintree SDK integration option. This SDK is Deprecated and only existing integrations are supported.
