### ISSUE TITLE
Request failure with http statusCode:422

### ISSUE THREAD

**Issue by nandkishormewara** [paypal/PayPal-Android-SDK#465]
* SDK/Library version: 'com.paypal.sdk:paypal-android-sdk:2.16.0'
* Environment: Sandbox
* `PayPal-Debug-ID` values: "79be1f145a9"
* Android Version and Device: moto xplay with android 7.0.1

request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"79be1f145a9","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by bluk** [comment]
It seems that your sandbox seller account is not setup correctly to receive the given currency from the buyer. I would contact [PayPal Technical Support](https://developer.paypal.com/support/) to ensure that your sandbox accounts are setup correctly.

Note that this SDK is deprecated so I would advise using the Braintree Direct or Express Checkout with Braintree SDKs for a mobile integration. From the README:

PayPal Mobile SDKs are now Deprecated and only existing integrations are supported. For all new integrations, use [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct) in [supported countries](https://www.braintreepayments.com/country-selection). In other countries, use [Express Checkout](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) and choose the Braintree SDK integration option.
