### ISSUE TITLE
request failure with http statusCode:422,exception:  &  checkout-session not created

### ISSUE THREAD

**Issue by gurjeetsalentro** [paypal/PayPal-Android-SDK#466]
Hi, 
I am facing issue in paypal.  here's the logcat below:
03-05 15:16:38.516 31891-23504/com.mytaskuser W/paypal.sdk: fg SN:55 PayPal Debug-ID: e1480959dab9d [sandbox, 2.16.0;release]
03-05 15:16:38.516 31891-23504/com.mytaskuser E/paypal.sdk: request failure with http statusCode:422,exception:
03-05 15:16:38.517 31891-23504/com.mytaskuser E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"e1480959dab9d","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
03-05 15:16:38.517 31891-31891/com.mytaskuser E/paypal.sdk: PAYMENT_CREATION_ERROR

![error](https://user-images.githubusercontent.com/25343481/36968783-9283f452-2089-11e8-81a6-8a96e5dd16a7.png)

**Comment by bluk** [comment]
It seems that your sandbox test accounts are not setup correctly to work with the mSDK. If this is an existing integration, you can contact [PayPal Technical Support](https://developer.paypal.com/support/) to help.

Note that this SDK is now Deprecated and only existing integrations are supported. For all new integrations, use [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct) in [supported countries](https://www.braintreepayments.com/country-selection). In other countries, use [Express Checkout](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) and choose the Braintree SDK integration option.
