### ISSUE TITLE
DE

### ISSUE THREAD

**Issue by biancamoreira93** [paypal/PayPal-Android-SDK#467]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Android Version and Device:

**Comment by bluk** [comment]
Please add details if there is an issue. Also, note that the PayPal Mobile SDKs are now Deprecated and only existing integrations are supported. For all new integrations, use [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct) in [supported countries](https://www.braintreepayments.com/country-selection). In other countries, use [Express Checkout](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) and choose the Braintree SDK integration option.
