### ISSUE TITLE
INTERNAL_SERVICE_ERROR and payment state "created"

### ISSUE THREAD

**Issue by Belozerow** [paypal/PayPal-Android-SDK#49]
I use sandbox. Often when I made payment with credit card, appears error dialog:

```
Payment Failed.
System error. Please try again later
```

with logcat message:

```
E/RequestError﹕ An internal service error has occurred, field:, issue:
E/PayPalService﹕ INTERNAL_SERVICE_ERROR
E/ViewRootImpl﹕ sendUserActionEvent() mView == null
```

The next time I press the button "Charge credit card", the message changes to:

```
E/RequestError﹕ The requested resource ID was not found, field:, issue:
E/PayPalService﹕ INVALID_RESOURCE_ID
E/ViewRootImpl﹕ sendUserActionEvent() mView == null
```

Or the same, but with DUPLICATE_REQUEST_ID code.
Or it can return PaymentConfirmation to 'onActivityResult' function, but the state of payment will be 'created', not 'approved':

``` json
{
    "payment": {
    "short_description": "I bet I do: both ",
    "amount": "15",
    "currency_code": "USD"
    },
    "client": {
    "platform": "Android",
    "paypal_sdk_version": "1.2.6",
    "product_name": "PayPal Android SDK; ",
    "environment": "sandbox"
    },
    "proof_of_payment": {
    "rest_api": {
    "state": "created",
    "payment_id": "PAY-0GK76363G8959271TKMC67JY"
}
}
}
```

**Comment by raviteja37** [comment]
Hi i am getting this error while paying through sandbox id 
request failure with http statusCode:422,exception:Unprocessable Entity
09-05 16:09:04.369 17840-21881/us.zoom.sdkexample E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"ee0213932758","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
09-05 16:09:04.372 17840-17840/us.zoom.sdkexample E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by Manikandanoptisol** [comment]
I facing "INTERNAL SERVICE ERROR" when i using paypal sample credit card details (Sandbox Mode).

 request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"9cd9fcd8e0f03"}

Could you known about this issue?

**Comment by pp-randy** [comment]
@Manikandanoptisol I apologize for the late response.  We did have issues around that time are things working for you now?

**Comment by tomwhipple** [comment]
This issue is from 2014 and was closed then. Please create a new issue if required.

(Though INTERNAL_SERVICE_ERROR is a transient bug within the PayPal backend.)
