### ISSUE TITLE
Docs: PaymentActivity.RESULT_PAYMENT_INVALID -> RESULT_EXTRAS_INVALID

### ISSUE THREAD

**Issue by wiiiimm** [paypal/PayPal-Android-SDK#59]
in step 6 of https://github.com/paypal/PayPal-Android-SDK/blob/master/docs/single_payment.md

PaymentActivity.RESULT_PAYMENT_INVALID should read PaymentActivity.RESULT_EXTRAS_INVALID

**Comment by elluminati10** [comment]
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:GMAdapter="http://svcs.paypal.com/mobile/adapter/types/pt" xmlns:tns1="http://svcs.paypal.com/types/common" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:annox="http://annox.dev.java.net" xmlns:ov="http://annox.dev.java.net/net.sf.oval.constraint" xsl:version="1.0"><soap:Body><GMAdapter:DeviceAuthenticationRequest><version>1.0</version><paypalAppId>APP-4CJ03898U8729380A</paypalAppId><mplVersion>1.5.6</mplVersion><authorizationType>Email</authorizationType><email>laurameneghin.m@gmail.com</email><password>Papone14875!</password><bypassEncryption>true</bypassEncryption><authorizeDevice>false</authorizeDevice><deviceReferenceToken>4TNG2P7FUCGVA00865C35XTHVSG811PWL365NH56RQL01U6KXYFASHMBJL10YUREKA</deviceReferenceToken><securityDetails><applicationNonce>wuncz23FvtQO9kAGlZYm5JLwBZSgxg25IYt2ZEGG9acAAAABgvwzPIroH6QaKafzoJVtLu9FlJ4ihasUHC9NHyMe1NpnLUQDW5rs9q8lcW9EjwMQ2BoeaDNFmjYOb3+F1uKBKL9jf8N2hs28eJdD4Bh7kJIiM+Hsv4IwCuwxPG7TCiS8AaL0SR3R3PHR2xLVY+HN+Y+ZJEJzoHuxFAbCux3a3YHmm48yOMXnRdwQdsyXyDqgFFuz2qwr5mjgX+2PgVEbYeefjJDxINO5Dq8hQHPHM8nqWMX8BvJfrbqnYWJaX8uY9KXXLDDv9Qff+s0DBGYoJA==</applicationNonce><deviceNonce>2/wYAH7EFQ0N7ay7/tdDWqyiBg0NeYlrxkWJ1HpltMoAAAAB/eYWUmQtSARLVmr+S5adELDpmQYAXiNqgV2ADP4G1gWS8oxC33DTN8pfM167NOL5u4oJGpp8rOhdTdP2P6xTkxLCRgjmYz/4nz03UuQthlEUw0QmpyRHwB0VvmHSHPYm4HbQ63rw+4sV3leZ0bg9p8pvPuBATEw/lDMdjN/XpIyGXg4jxjUn4+bFuKlNU1xp1gzzbY/4/Fxc08AkDaQeV9k2bMtwyeII+zb50yrwDZ4=</deviceNonce></securityDetails></GMAdapter:DeviceAuthenticationRequest></soap:Body></soap:Envelope>
04-29 05:42:23.117  2﹕ postXML do execute
04-29 05:42:25.550  2﹕ Resonse Header: Server = Apache-Coyote/1.1
04-29 05:42:25.550  2﹕ Resonse Header: X-EBAY-SOA-REQUEST-ID = 15460f7f-8200-a116-c1d3-e148ff7f550d!GMAdapter!10.17.108.29![]
04-29 05:42:25.550  2﹕ Resonse Header: X-PAYPAL-SERVICE-VERSION = 1.0.0
04-29 05:42:25.550  2﹕ Resonse Header: X-PAYPAL-SERVICE-NAME = {http://svcs.paypal.com/mobile/adapter/types/pt}GMAdapter
04-29 05:42:25.550  2﹕ Resonse Header: X-PAYPAL-MESSAGE-PROTOCOL = SOAP11
04-29 05:42:25.550  2﹕ Resonse Header: X-PAYPAL-OPERATION-NAME = DeviceAuthenticateUser
04-29 05:42:25.551  2﹕ Resonse Header: X-PAYPAL-RESPONSE-DATA-FORMAT = XML
04-29 05:42:25.551  2﹕ Resonse Header: Content-Type = text/xml;charset=UTF-8
04-29 05:42:25.551  2﹕ Resonse Header: Expires = Fri, 29 Apr 2016 07:42:25 GMT
04-29 05:42:25.551  2﹕ Resonse Header: Cache-Control = max-age=0, no-cache, no-store
04-29 05:42:25.551  2﹕ Resonse Header: Pragma = no-cache
04-29 05:42:25.551  2﹕ Resonse Header: Date = Fri, 29 Apr 2016 07:42:25 GMT
04-29 05:42:25.551  2﹕ Resonse Header: Content-Length = 1315
04-29 05:42:25.551  2﹕ Resonse Header: Connection = keep-alive
04-29 05:42:25.551  2﹕ postXML setup to read reponse
04-29 05:42:25.551  2﹕ postXML do read response
04-29 05:42:25.552  2﹕ createQuickPayment error endpoint - https://mobileclient.paypal.com/GMAdapter/DeviceAuthenticateUser
04-29 05:42:25.564  2﹕ createQuickPayment error request - <?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:GMAdapter="http://svcs.paypal.com/mobile/adapter/types/pt" xmlns:tns1="http://svcs.paypal.com/types/common" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:annox="http://annox.dev.java.net" xmlns:ov="http://annox.dev.java.net/net.sf.oval.constraint" xsl:version="1.0"><soap:Body><GMAdapter:DeviceAuthenticationRequest><version>1.0</version><paypalAppId>APP-4CJ03898U8729380A</paypalAppId><mplVersion>1.5.6</mplVersion><authorizationType>Email</authorizationType><email>laurameneghin.m@gmail.com</email><password>Papone14875!</password><bypassEncryption>true</bypassEncryption><authorizeDevice>false</authorizeDevice><deviceReferenceToken>4TNG2P7FUCGVA00865C35XTHVSG811PWL365NH56RQL01U6KXYFASHMBJL10YUREKA</deviceReferenceToken><securityDetails><applicationNonce>wuncz23FvtQO9kAGlZYm5JLwBZSgxg25IYt2ZEGG9acAAAABgvwzPIroH6QaKafzoJVtLu9FlJ4ihasUHC9NHyMe1NpnLUQDW5rs9q8lcW9EjwMQ2BoeaDNFmjYOb3+F1uKBKL9jf8N2hs28eJdD4Bh7kJIiM+Hsv4IwCuwxPG7TCiS8AaL0SR3R3PHR2xLVY+HN+Y+ZJEJzoHuxFAbCux3a3YHmm48yOMXnRdwQdsyXyDqgFFuz2qwr5mjgX+2PgVEbYeefjJDxINO5Dq8hQHPHM8nqWMX8BvJfrbqnYWJaX8uY9KXXLDDv9Qff+s0DBGYoJA==</applicationNonce><deviceNonce>2/wYAH7EFQ0N7ay7/tdDWqyiBg0NeYlrxkWJ1HpltMoAAAAB/eYWUmQtSARLVmr+S5adELDpmQYAXiNqgV2ADP4G1gWS8oxC33DTN8pfM167NOL5u4oJGpp8rOhdTdP2P6xTkxLCRgjmYz/4nz03UuQthlEUw0QmpyRHwB0VvmHSHPYm4HbQ63rw+4sV3leZ0bg9p8pvPuBATEw/lDMdjN/XpIyGXg4jxjUn4+bFuKlNU1xp1gzzbY/4/Fxc08AkDaQeV9k2bMtwyeII+zb50yrwDZ4=</deviceNonce></securityDetails></GMAdapter:DeviceAuthenticationRequest></soap:Body></soap:Envelope>
04-29 05:42:25.564  2﹕ createQuickPayment error reply - <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><ns2:DeviceAuthenticateUserResponse xmlns:ns2="http://svcs.paypal.com/mobile/adapter/types/pt"><timestamp>2016-04-29T00:42:24.857-07:00</timestamp><ack>Failure</ack><error><errorId>10803</errorId><message>Mobile Login failed.</message></error><correlationId>4a7436b54b2a2</correlationId><backendBuild>21463915</backendBuild><duration>568</duration><securityDetails><applicationNonce>puO3yP8tbXGJ6z7d7JEey7MARORfzHE+vpazfCIigSUAAAABgvwzPIroH6QaKafzoJVtLiWOMAlJ7vN/g1cO3OD6TJlnLUQDW5rs9q8lcW9EjwMQ2BoeaDNFmjYOb3+F1uKBKL9jf8N2hs28eJdD4Bh7kJIiM+Hsv4IwCuwxPG7TCiS8AaL0SR3R3PHR2xLVY+HN+f14unoS14J+Qzi5X5RjVtQ+rR3hhN7IStoXZtjLUsgo9amAWHTJk25B7BzeeCDF7PWpgFh0yZNuQewc3nggxez5lNSbJ1GnkHO9QPfErdKfJsAO5qZ9NtKg7dSMFnmFKYY5+MiZnA825VRyvEeFo1M=</applicationNonce><deviceNonce>zzUZLPnmcOZyRN2NbOg369PsMAiYY31wNAtmhKE+bYMAAAAB/eYWUmQtSARLVmr+S5adEJcm/9IFtfn/mnzUXhB/4ROS8oxC33DTN8pfM167NOL5u4oJGpp8rOhdTdP2P6xTk8jUfl0LAUE2CKS+GWk2CPAUw0QmpyRHwB0VvmHSHPYm4HbQ63rw+4sV3leZ0bg9p92h7UidmZOgGdg2X6zwyXva/kT4LCDm87XUeu6Msn+k2v5E+Cwg5vO11HrujLJ/pNzQnOiCGs0HnG/JP0l7oM0U4G2eW9OmSLTxF4+q3doV</deviceNonce></securityDetails></ns2:DeviceAuthenticateUserResponse></soapenv:Body></soapenv:Envelope>
04-29 05:42:25.571  2MPL﹕ end LOGIN fail, Login failed. Please try again.
