### ISSUE TITLE
Android SDK : Merchant does not accept payments of this type

### ISSUE THREAD

**Issue by inspirationindigo** [paypal/PayPal-Android-SDK#75]
Hi friends I am getting an error when i proceed the payment via paypal Sdk in Android platform . I am getting an error as Merchant does not accept payments of this type. I am using the Production Environment and the live client id of the merchant from UK and i have used GBP in the currencies in the code and everything is popping up fine but the thing is when i proceed to payment using paypal or using the credit/debit card i will get the same error as stated above. 

The client id which i am using is UK client id which do not have pro permissions for that id and it is the business type.
And paypal people is not suggesting us correctly and the payment cant be made 

Friends please suggest me how to rectify this  error for GBP 
![paypal_merchanterror](https://cloud.githubusercontent.com/assets/7932616/3326568/e35e32fa-f79f-11e3-808b-6abb474e7029.png)

Thanks in advance

**Comment by decveen** [comment]
getting the same error while making card payment through paypal, i have also  enable the Allow payments sent to me in a currency I do not hold option in profile setting.
debug_id":"a29aa5d341883". please help.

complete response : {"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNAUTHORIZED_PAYMENT","debug_id":"a29aa5d341883"}

![capture](https://cloud.githubusercontent.com/assets/25954006/23210669/aa7b5826-f924-11e6-8e51-544bb59824a0.PNG)

**Comment by pp-randy** [comment]
@decveen if you are still seeing this issue please create a new issue and we will look further.
