### ISSUE TITLE
Build system application failed in kitkat

### ISSUE THREAD

**Issue by martincz** [paypal/PayPal-Android-SDK#91]
When I build a System app with paypal sdk, It's failed.

Tell me:
Error: Can't read [proguard.ClassPathEntry@7c6159c4] (Can't process class [com/paypal/android/sdk/aZ.class] (Unsupported version number [51.0] for class format))

Android Kitkat use ProGuard, version 4.4.

**Comment by jaypatel512** [comment]
Hey @martincz !

I think the issue could be closed now, as we have made some major changes to the build tools. The newer version dependency should work just fine for most major versions.
