### ISSUE TITLE
Internal Server Error when create a payment

### ISSUE THREAD

**Issue by aragornh** [paypal/PayPal-Android-SDK#99]
I use sandbox account to create a payment. It works yesterday but today it fails all the time.
The error is as bellow.

10-01 07:29:56.265: E/paypal.sdk(2475): request failure with http statusCode:500,exception:org.apache.http.client.HttpResponseException: Internal Server Error
10-01 07:29:56.265: E/paypal.sdk(2475): request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"afb5f219dc3d5"}

**Comment by ShivangiAgrawal** [comment]
Same problem for me even now also. Yesterday it was running properly but when today i tried to run showing same error with same credentials

**Comment by pp-randy** [comment]
@ShivangiAgrawal there was a sandbox issue earlier causing the 500 internal error, but should now be resolved. Please create a new issue and provide your error response if the issue persists.
